### ISSUE TITLE
Crash when launching game

### ISSUE THREAD

**Issue by freerangerstudios** [bernie-g/geckolib#100]
Not much to say other than what the title already says, I'm using the latest version. I actually cant even paste the crash report since it's so frickin long :(

**Comment by bernie-g** [comment]
Use pastebin. Not sending us a a crash log is about as helpful as demanding a doctor help you without telling him what symptoms you have.

**Comment by freerangerstudios** [comment]
True, cant even paste it at pastebin tho
I could of course just paste the first 100 lines or something since that should be enough to determine the problem, so here it is: 
[](https://pastebin.com/AyHUtFtH)

**Comment by bernie-g** [comment]
There's literally no reason why you cannot upload the full log. Is this in dev or prod?

**Comment by freerangerstudios** [comment]
Yes there is a reason, it exceeds the max file size for a free pastebin account, version of mod is 1.16.5-3.0.10

**Comment by bernie-g** [comment]
Then use one of the dozen pastebin services, i.e. hastebin, paste.gg, paste.ee, gist.github.com, etc.

I also need to know if you are in a production environment or you are developing a mod.

**Comment by freerangerstudios** [comment]
Production environment, using it because the mod Ars Nouveau needs it.
Here's the error message (yes its pretty bloody long): https://paste.gg/p/anonymous/636e3612089443d5bfd253e1ac62fc7b

**Comment by AzureDoom** [comment]
Make sure you are using Java 8 and redownload the jar to make sure as your jar looks broken.

**Comment by freerangerstudios** [comment]
Oh I'm using jdk 13, will try with jre 8

**Comment by AzureDoom** [comment]
Yeah we target 8 due to the launcher shipping with 8. Anything past is Use At Your Own Risk

**Comment by freerangerstudios** [comment]
Alright, good to know. Putting it on the homepage on curse would probably be a good idea to avoid unneccessary crash reports from people like me :D

**Comment by AzureDoom** [comment]
This as assumed thing as Forge itself has the same policy

**Comment by freerangerstudios** [comment]
Whoops, my bad.
I'll perform a test run and then I'll close the issue if I don't get any more issues with geckolib during startup

**Comment by freerangerstudios** [comment]
No issues with geckolib remaining, seems like the issue was just me not using java 8. For anyone else having the same issue, java 13 is not recommended :)
