### ISSUE TITLE
New version crash?

### ISSUE THREAD

**Issue by AdnanuReeves** [bernie-g/geckolib#114]
Downloaded the newest version released for forge 1.16.5 and the game crashed
https://paste.ubuntu.com/p/bnczZcbTt4/

**Comment by DenimRed** [comment]
Huh, the class name of `GeoModelException` was apparently changed to `GeckoLibException` on version 3.0.15; a temporary fix would be to use version 3.0.14 until mods switch to the new name.
You may want to notify relevant mod authors about the name change (the author of `arsnouveau` in this case) if they're not already aware.

**Comment by AzureDoom** [comment]
Correct, this would be an issue with ars with was fixed with https://github.com/baileyholl/Ars-Nouveau/commit/649e97f1ed8de2e91e113c660dd55ec6c751e644
