### ISSUE TITLE
Changelog incorrect on Curse?

### ISSUE THREAD

**Issue by greysondn** [bernie-g/geckolib#122]
>  Updated the Library to 1.16.5 and official mappings, there is no reason to still be using 1.16.5, update if you want support. #AzureDoom

... What I see is that (as I write this) 1.16.5 is the latest official release of Minecraft.  1.17 is still in pre-release.

Did I miss something or is that a typo?

**Comment by bernie-g** [comment]
It is a typo. Supposed to say 1.16.4.
