### ISSUE TITLE
Even if you specify no loop, the animation repeats after it finishes playing

### ISSUE THREAD

**Issue by NekoCaffeine** [bernie-g/geckolib#123]
Hi, I'm using Gecko to make a creature.
But I found that I can't get the animation to stay on the last frame.

Although the animation state is set to stopped here.
https://github.com/bernie-g/geckolib-core/blob/be284092a0281d531d051939030671aaa7403ef7/src/main/java/software/bernie/geckolib3/core/controller/AnimationController.java#L521

Then it is set back to running here.
https://github.com/bernie-g/geckolib-core/blob/be284092a0281d531d051939030671aaa7403ef7/src/main/java/software/bernie/geckolib3/core/controller/AnimationController.java#L384

So even if I specify loop as false, it doesn't help.

```
Minecraft 1.12.2
MinecraftForge 1.12.2-14.23.5.2854
GeckoLib 3.0.0-beta.7
```
```java
protected AnimationBuilder hide = new AnimationBuilder().addAnimation("sandworm.hide", false);
    
protected PlayState animationHide(AnimationEvent<?> event) {
    event.getController().setAnimation(hide);
    return PlayState.CONTINUE;
}
```

**Comment by bernie-g** [comment]
In order to make an animation hold on the last frame you must play another still animation on loop after the first one finishes. Please join our discord if you need more help with this.

**Comment by GnRSlash** [comment]
> 

Hi, will this be the last comment?
Are you planing to change this behaviour?  because it is not cool to create another animation just to stay in loop...

**Comment by bernie-g** [comment]
I don't plan on adding it anytime soon as it works fine in its current state, just a little bit inconvenient. Feel free to PR this feature if you want it.
