### ISSUE TITLE
Geckolib 36.1.1 issue.

### ISSUE THREAD

**Issue by Kameemee** [bernie-g/geckolib#126]
Hello. So, I tried to turn on atm6 modpack and minecraft said that I don't have the geckolib 36.1.1 version... But I looked online for it and there's no such thing as of yet... I don't think I'm playing minecraft, the minecraft's playing me....

**Comment by bernie-g** [comment]
Please post a screenshot of the actual error message.

**Comment by AzureDoom** [comment]
It means you don't have Forge version 36.1.1, you need to update the forge version of ATM6
