### ISSUE TITLE
absolutely have no idea how to install 

### ISSUE THREAD

**Issue by OmniEcho3814** [bernie-g/geckolib#130]
I went to the installation page and tried to find the build.gradle but could not find it what so ever thus i am unable to start my game as it is required for a mod I'm using. I'm trying to install the 1.15.2 version.

**Comment by bernie-g** [comment]
Drag and drop the mod into your mods folder. The wiki is for developers only. https://www.curseforge.com/minecraft/mc-mods/geckolib/files/3034409
