### ISSUE TITLE
Errors during game load

### ISSUE THREAD

**Issue by SamuelInaebnit** [bernie-g/geckolib#138]
The guys over at the Forge forums directed me here. Apparently having your library in my mod list causes loads of issues while loading the game. Trying to load without it seems to confirm that because it works in that case.

Here's the link to the post i made on the forge forums which should contain info regarding the Issue (and log files):
[https://forums.minecraftforge.net/topic/100620-my-forge-always-fails-to-load-with-a-mod-setup-that-works-for-everyone-else-who-tried-it/](https://forums.minecraftforge.net/topic/100620-my-forge-always-fails-to-load-with-a-mod-setup-that-works-for-everyone-else-who-tried-it/)

**Comment by AzureDoom** [comment]
None of those issues are with Geckolib
