### ISSUE TITLE
GeckoLib has failed to load correctly

### ISSUE THREAD

**Issue by zipstie** [bernie-g/geckolib#142]
I'm trying to put some mods together for fun. It would appear that GeckoLib is the root of my issue. I believe the other mods that are failing require GeckoLib. I attached the log, but here is the error they give off:
java.lang.NoClassDefFoundError: Could not initialize class software.bernie.geckolib3.network.GeckoLibNetwork

[crash-2021-06-07_14.04.34-fml.txt](https://github.com/bernie-g/geckolib/files/6611437/crash-2021-06-07_14.04.34-fml.txt)

**Comment by Spudstak** [comment]
Having this same issue.

[crash-2021-06-07_21.00.07-fml.txt](https://github.com/bernie-g/geckolib/files/6612575/crash-2021-06-07_21.00.07-fml.txt)

**Comment by AzureDoom** [comment]
This is an issue with aoa3, who shades the library instead of using it as an extra requirement, this is due to the changes with networking. Rollback AoA3 to stop the crash.

**Comment by PresquePlayed** [comment]
The AoA dev says Geckolib has to fix an issue before AoA can ensure compability

**Comment by AzureDoom** [comment]
> The AoA dev says Geckolib has to fix an issue before AoA can ensure compability

https://github.com/Tslat/Advent-Of-Ascension/issues/2621#issuecomment-856814000

**Comment by AzureDoom** [comment]
This will be fixed in AoA next update. Closing this
