### ISSUE TITLE
1.12.2 geckolib 3.0.0 beta 7

### ISSUE THREAD

**Issue by AlexChecker** [bernie-g/geckolib#146]
When trying to load this library it throws me error and freezes all.
It starts when it ries to load bat animations:
[software.bernie.geckolib3.GeckoLib]: Couldn't load geckolib3:animations/bat.animation.json
But this file presents in jar, and it in correct place.

**Comment by AzureDoom** [comment]
1.12.2 is honestly out of support, unless Gecko himself fixes but I wouldn't hold out for it.
