### ISSUE TITLE
[Fabric] AbstractMethodError

### ISSUE THREAD

**Issue by LonelyMusicDisc** [bernie-g/geckolib#148]
[Here's the log
](https://pastebin.com/Rznngb3P)

at first I thought this was an issue with gradle, so I downgrade, but that didn't do anything, then I thought it was with loom so I downgraded that but same result; I realized I was using JDK 16 so I switch to 8 and same result.

~~already posted this on the discord, but why not here too.~~

**Comment by AzureDoom** [comment]
![image](https://user-images.githubusercontent.com/7415711/123560775-5bb89880-d772-11eb-9378-0e783d4bb720.png)
![](https://i.imgur.com/AhYAlfG.png)
![](https://i.imgur.com/6nZ8LQF.png)
It's on your end somewhere 🤷🏻 it's loading just fine here

**Comment by Conclure** [comment]
This is not an issue from his side. I believe in newer versions of Fabric API 1.16.5 the abstract method `ResourceReloader#reload(ResourceReloader.Synchronizer, ResourceManager, Profiler, Profiler, Executor, Executor)`. By the looks of the class GeckoLib's first anonymous class instantiates a new instance of IdentifiableResourceReloadListener which has the abstract methods `IdentifiableResourceReloadListener#getFabricId()` and `IdentifiableResourceReloadListener#getFabricDependencies()`. Thing is that it actually extends the ResourceReloader interface, with other words it an implementation of IdentifiableResourceReloadListener would need to override getFabricId(), getFabricDependencies() and reload(...). However as of now [GeckoLib](https://github.com/bernie-g/geckolib/blob/fabric/1.16/src/main/java/software/bernie/geckolib3/GeckoLib.java) does not do that and subsequently causes a LinkageError (AbstractMethodError).

**Comment by Conclure** [comment]
Nevermind

**Comment by AzureDoom** [comment]
Yeah @Conclure I am testing on the newest and same version of Fabric API and loader as him and it's loading just fine

**Comment by Conclure** [comment]
Although the issue persists. I think I found why.

```java
	public static void initialize() {
		if (!hasInitialized) {
			ResourceManagerHelper.get(ResourceType.CLIENT_RESOURCES)
					.registerReloadListener(new IdentifiableResourceReloadListener() {
						@Override
						public Identifier getFabricId() {
							return new Identifier(GeckoLib.ModID, "models");
						}

						@Override
						public CompletableFuture<Void> reload(Synchronizer synchronizer, ResourceManager manager,
								Profiler prepareProfiler, Profiler applyProfiler, Executor prepareExecutor,
								Executor applyExecutor) {
							return GeckoLibCache.getInstance().reload(synchronizer, manager, prepareProfiler,
									applyProfiler, prepareExecutor, applyExecutor);
						}
					});
		}
		hasInitialized = true;
	}
```
The problem occurs here. GeckoLibCache#reload takes a ResourceReloadListener.Synchronizer instance whilst the unimplemented method specifies a ResourceReload.Synchronizer.
![image](https://user-images.githubusercontent.com/63319713/123562999-5c711f00-d7b2-11eb-8744-1d41d94daf4f.png)

Needless to say I am uncertain whether I use the wrong version of it's you.

**Comment by AzureDoom** [comment]
Thanks Fabric https://github.com/FabricMC/yarn/pull/2131 love your breaking changes, truly learning from Forge I see. Revert back to at least '0.29.4+1.16' for your ide, as shown the production version doesn't care so until I can fix my java issues thanks to Java 16, just do this for now.

**Comment by Conclure** [comment]
> Thanks Fabric [FabricMC/yarn#2131](https://github.com/FabricMC/yarn/pull/2131) love your breaking changes, truly learning from Forge I see. Revert back to at least '0.29.4+1.16' for your ide, as shown the production version doesn't care so until I can fix my java issues thanks to Java 16, just do this for now.

I would like to say that you should rather revert back to yarn mappings version `1.16.5+build.3` to make it work. If you wanna use  GeckoLib as of now @LonelyMusicDisc.
