### ISSUE TITLE
[Forge 1.16.x] Color in projectile renderer has green and blue flipped.

### ISSUE THREAD

**Issue by mcpecommander** [bernie-g/geckolib#152]
https://github.com/bernie-g/geckolib/blob/51db4b26e99bf400e194e496b50146d53d5d011a/src/main/java/software/bernie/geckolib3/renderers/geo/GeoProjectilesRenderer.java#L60
The green and blue are in the wrong order

**Comment by AzureDoom** [comment]
Closing as PR was merged
