### ISSUE TITLE
[Forge 1.16.5] Non-Array Custom Instruction Keyframes Causing Crash

### ISSUE THREAD

**Issue by BobMowzie** [bernie-g/geckolib#155]
Geckolib seems to expect all custom instruction keyframes to be defined in the animation jsons as lists, and will crash otherwise. Here is the crash log: [https://pastebin.com/qzRcn02N](https://pastebin.com/qzRcn02N)

Blockbench saves single-instruction keyframes as singletons, however:
![image](https://user-images.githubusercontent.com/7550579/125340003-ecb97300-e31f-11eb-9ccc-1407a1ec0c61.png)
This can be easily circumvented by manually placing each script into a list. But animation files are edited and saved over in Blockbench frequently, requiring these corrections to be reapplied each time.

**Comment by bernie-g** [comment]
Yeah I've known about this for awhile and never fixed it, gonna push out a fix soon.
