### ISSUE TITLE
[Forge 1.15.2] Geckolib Example Mod has failed to load correctly

### ISSUE THREAD

**Issue by Rinventor** [bernie-g/geckolib#156]
I created my first animated entity. Game crashes during loading, saying Geckolib Example Mod and my TransportMod has failed to load correctly. Even when I don't initialize Geckolib in my mod constructor the game Geckolib Example Mod still fails to load correctly. Any Idea what could cause this crash? Thanks.

Forge: 1.15.2-31.2.46
Geckolib: forge-1.15.2-3.0.32
latest.log: https://pastebin.com/ricGPdSR

**Comment by AzureDoom** [comment]
1.15.2 is honestly unmaintained at this point.
