### ISSUE TITLE
1.17.1 Dev Crash with GeckoLib or GeckoLib is crashing in 1.17.1 development environments

### ISSUE THREAD

**Issue by Mysticpasta1** [bernie-g/geckolib#157]
I was coding 1.17.1 for my mod and I ran into this as soon as I touch the creative menu in gameplay. 
Idk what is happening exactly I know that it is a gecko lib issue. Unless I'm somehow using the wrong version of it

The Crash Report from the 1.17.1 dev environment
https://paste.hypherionmc.me/azixuwubar.yaml

**Comment by AzureDoom** [comment]
Fixed in 3.0.9
