### ISSUE TITLE
[Forge 1.16.5] getRenderType and getRenderColor are redundant and useless in ItemGeoRenderer

### ISSUE THREAD

**Issue by mcpecommander** [bernie-g/geckolib#159]
Starting from this line:
https://github.com/bernie-g/geckolib/blob/549fbe9d5648528aac0c0183580aaecbdf739b1c/src/main/java/software/bernie/geckolib3/renderers/geo/GeoItemRenderer.java#L98
The two methods mentioned in the title are useless and don't get called. There are two identically named methods in IGeoRenderer that are used in the render method instead.
https://github.com/bernie-g/geckolib/blob/549fbe9d5648528aac0c0183580aaecbdf739b1c/src/main/java/software/bernie/geckolib3/renderers/geo/IGeoRenderer.java#L113
While these two methods don't hurt or crash anything, they are quite confusing since overriding them instead of the IGeoRenderer's ones will not run the code.
If you can possibly delete these two methods, it would make it clearer which to use.

**Comment by AzureDoom** [comment]
closing as fix you pr'd was merged
