### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Index: -1, on latest.log

### ISSUE THREAD

**Issue by aburone** [bernie-g/geckolib#163]
This doesn't seem critical or anything but quite anoying
https://pastebin.pl/view/7beb75a3

**Comment by bernie-g** [comment]
Send your animation file, you have invalid molang.

**Comment by aburone** [comment]
The what?
You mean the entire log file?
What's a molang?

**Comment by bernie-g** [comment]
No, your animation json.

**Comment by aburone** [comment]
I don't have any file called "animation.json" or anything containing "animation" on it's name.
I'm not a mod developer

**Comment by bernie-g** [comment]
Then you need to contact whichever mod author is using geckolib in your pack. They have invalid molang.

Closing because this isn't an issue with Geckolib.

**Comment by aburone** [comment]
> Then you need to contact whichever mod author is using geckolib in your pack. They have invalid molang

Done, thanks. It's Ars Noveau

**Comment by red2blue** [comment]
Apparently everyone has a bad molang. I think its you that are using molang wrong, lmfao. Mojang can't have a bad component its you who is using the components wrong.
