### ISSUE TITLE
[1.17.x Fabric] Entity animations with sound effects bug if the shouldLoop animation field is set to false

### ISSUE THREAD

**Issue by ikerleon02** [bernie-g/geckolib#172]

**Comment by ikerleon02** [comment]
When an entity animation (haven't checked block or item) is set to not loop (_shouldLoop_ false), it looks like the sound listener is called multiple times per animation.  **_(See gyazo link below)_**

When an entity is spawned the sound matches perfectly the animation and it is played perfectly. The problem starts when a second entity is spawned near it. When 2+ entities are close together, only one plays the normal sound. The others play the sound multiples times.

As mentioned by Gecko in the discord, it might be the _markNeedsReload(_) of the controller with the _shouldLoop_ set to false.

Other scenarios played:
 - Without _markNeedsReload()_ and the _shouldLoop_ set to true it works as expected
 - **With** _markNeedsReload()_ and the _shouldLoop_ set to true it works as expected

https://gyazo.com/a9ab82b34692b6d2f715cd12f7e963b2

**Comment by AzureDoom** [comment]
Can you try this on the newest version I just pushed for 1.17.1? `3.0.29`

**Comment by ikerleon02** [comment]
Sure, i will try it this week. I let you know

**Comment by ikerleon02** [comment]
I gave it a try, since i had all setted up, and unfortunately it doesn't work either

**Comment by AzureDoom** [comment]
Hi @ikerleon02 we did some changes to the core since this, please try on the latest 1.18.1 as 1.17.1 is no longer supported.

**Comment by AzureDoom** [comment]
@ikerleon02 keyframes got an update in 1.18.1 via a core update, if you can try this in that.
