### ISSUE TITLE
Loadloop caused by any 1.17.1 Fabric version past 3.0.10

### ISSUE THREAD

**Issue by Muffintiem** [bernie-g/geckolib#174]
Any time I try to update Geckolib past version 3.0.10 it gets stuck in a loading loop. I made sure I wasn't downloading a Forge version. I'm not sure what's causing it as it doesn't give me any kind of crash report.

**Comment by AzureDoom** [comment]
Please provide a log on latest

**Comment by AzureDoom** [comment]
![image](https://user-images.githubusercontent.com/7415711/132967710-1e34426a-58ce-4fb5-bf7f-4befe0149fc8.png)
Not reproduceable.
