### ISSUE TITLE
[1.12.x Forge]  build.gradle error

### ISSUE THREAD

**Issue by Moosyu** [bernie-g/geckolib#175]
I tried importing geckolib via build.gradle and got this error:
https://pastebin.com/8FRi87G1

**Comment by AzureDoom** [comment]
Can you show your build.gradle please?

**Comment by Moosyu** [comment]
https://pastebin.com/8LdwZJaJ

**Comment by AzureDoom** [comment]
1. Those don't go in the bottom.
2. You have have TWO depends blocks of course it won't work. Use the one already provided by the build.gradle and put the repo block above it.
