### ISSUE TITLE
[1.17.1 Forge]  Client crash NullPointerException: Registry Object not present: geckolib3:geoexampleentity

### ISSUE THREAD

**Issue by ProsperCraft** [bernie-g/geckolib#180]
https://gist.github.com/ProsperCraft/e21eb20a51cd6246b0551086924651e0

Reproduced with only Gekolib

https://gist.github.com/ProsperCraft/352686dcdea003d6750676ded2a28887

**Comment by AzureDoom** [comment]
Fixed in latest build heading to CF now
