### ISSUE TITLE
i cant use geckolib1.17.1fabric in ide when i bulid

### ISSUE THREAD

**Issue by fkyah3** [bernie-g/geckolib#181]
A problem occurred configuring root project 'untitled4'.
> Could not resolve all files for configuration ':modCompileClasspath'.
   > Could not find software.bernie.geckolib:geckolib-fabric-1.17:3.0.13.
     Searched in the following locations:
       - file:/H:/untitled4/.gradle/loom-cache/remapped_mods/software/bernie/geckolib/geckolib-fabric-1.17/3.0.13/geckolib-fabric-1.17-3.0.13.pom
       - https://maven.fabricmc.net/software/bernie/geckolib/geckolib-fabric-1.17/3.0.13/geckolib-fabric-1.17-3.0.13.pom
       - https://libraries.minecraft.net/software/bernie/geckolib/geckolib-fabric-1.17/3.0.13/geckolib-fabric-1.17-3.0.13.pom
       - https://repo.maven.apache.org/maven2/software/bernie/geckolib/geckolib-fabric-1.17/3.0.13/geckolib-fabric-1.17-3.0.13.pom
       - file:/C:/Users/as/.gradle/caches/fabric-loom/3.0.13/geckolib-fabric-1.17-dev.jar
       - file:/H:/untitled4/.gradle/loom-cache/3.0.13/geckolib-fabric-1.17-dev.jar
     Required by:
         project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by fkyah3** [comment]
plugins {
    id 'fabric-loom' version '0.10-SNAPSHOT'
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

repositories {
    // Add repositories to retrieve artifacts from in here.
    // You should only use this when depending on other mods because
    // Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
    // See https://docs.gradle.org/current/userguide/declaring_repositories.html
    // for more information about repositories.
}

dependencies {
    // To change the versions see the gradle.properties file
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    // Fabric API. This is technically optional, but you probably want it anyway.
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    // PSA: Some older mods, compiled on Loom 0.2.1, might have outdated Maven POMs.
    // You may need to force-disable transitiveness on them.
}

processResources {
    inputs.property "version", project.version
    filteringCharset "UTF-8"

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

def targetJavaVersion = 16
tasks.withType(JavaCompile).configureEach {
    // ensure that the encoding is set to UTF-8, no matter what the system default is
    // this fixes some edge cases with special characters not displaying correctly
    // see http://yodaconditions.net/blog/fix-for-java-file-encoding-problems-with-gradle.html
    // If Javadoc is generated, this must be specified in that task too.
    it.options.encoding = "UTF-8"
    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        it.options.release = targetJavaVersion
    }
}

java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
    archivesBaseName = project.archives_base_name
    // Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
    // if it is present.
    // If you remove this line, sources will not be generated.
    withSourcesJar()
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.archivesBaseName}" }
    }
}

// configure the maven publication
publishing {
    publications {
        mavenJava(MavenPublication) {
            // add all the jars that should be included when publishing to maven
            artifact(remapJar) {
                builtBy remapJar
            }
            artifact(sourcesJar) {
                builtBy remapSourcesJar
            }
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        // Add repositories to publish to here.
        // Notice: This block does NOT have the same function as the block in the top level.
        // The repositories here will be used for publishing your artifact, not for
        // retrieving dependencies.
        maven { url 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/' }
    }

    dependencies {
        modImplementation 'software.bernie.geckolib:geckolib-fabric-1.17:3.0.13:dev'
    }
}

**Comment by AzureDoom** [comment]
Please file a proper report with logs and update to the latest version

**Comment by fkyah3** [comment]
> Please file a proper report with logs and update to the latest version

find problem bulid gradle not right thx for your help
