### ISSUE TITLE
[1.17.x Fabric] Cannot Remap AW From Namespace 'named'

### ISSUE THREAD

**Issue by halotroop2288** [bernie-g/geckolib#182]
## Version Info
**Minecraft**: Java Edition 1.17
**GeckoLib**: 3.0.13
**Loader**: Fabric

## Issue
After adding Geckolib to the Gradle buildscript, Gradle complains that it cannot remap an accesswidener from namespace `named`. It expected `intermediary`.

- [x] Confirmed caused by adding Geckolib.
- [x] Does not occur if Geckolib is removed from the buildscript.

## Buildscript
- [x] Outside the `buildscript` block, next to the Minecraft, Fabric API, and Fabric Loader dependencies.

<details>

```build.gradle
repositories {
	maven {
		url 'https://maven.terraformersmc.com/releases'
		content {
			includeGroup('com.terraformersmc')
		}
	}
	maven {
		url "https://maven.shedaniel.me/"
		content {
			includeGroup('me.shedaniel')
		}
	}
	maven {
		url 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/'
		content {
			includeGroup('software.bernie.geckolib')
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
	modApi "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
	modApi "com.terraformersmc:modmenu:${project.modmenu_version}"

	modImplementation("software.bernie.geckolib:geckolib-fabric-1.17:${project.geckolib_version}:dev") {

	}
}
```

</details>

<details>

```gradle.properties
org.gradle.jvmargs = -Xmx1G
kotlin_version     = 1.5.30

minecraft_version  = 1.17.1
yarn_mappings      = 1.17.1+build.61
loader_version     = 0.11.7
fabric_version     = 0.40.1+1.17

mod_version        = 1.0.0
maven_group        = com.halotroop
archives_base_name = mod-suite

modmenu_version    = 2.0.11
rei_version        = 6.0.279-alpha
geckolib_version   = 3.0.13
```

</details>

## Stacktrace:
<details>

```
Caused by: java.lang.IllegalArgumentException: Cannot remap access widener from namespace 'named'. Expected: 'intermediary'
	at net.fabricmc.accesswidener.AccessWidenerRemapper.visitHeader(AccessWidenerRemapper.java:53)
	at net.fabricmc.accesswidener.AccessWidenerReader.read(AccessWidenerReader.java:93)
	at net.fabricmc.accesswidener.AccessWidenerReader.read(AccessWidenerReader.java:73)
	at net.fabricmc.accesswidener.AccessWidenerReader.read(AccessWidenerReader.java:66)
	at net.fabricmc.loom.configuration.mods.ModProcessor.remapAccessWidener(ModProcessor.java:120)
	at net.fabricmc.loom.configuration.mods.ModProcessor.remapJars(ModProcessor.java:186)
...200+ more lines
```

</details>

**Comment by MiniDay** [comment]
I also encountered this problem, but I changed the `fabric-loom` to version 0.9 and it can be used normally. You can also try

**Comment by AzureDoom** [comment]
Update to 3.0.14 and reset please. Please check the CurseForge for any updates, wiki site is currently broken and not showing the updates. Site will be converted to Github Pages after my vacation.

**Comment by halotroop2288** [comment]
Yep. Still happens, despite your premature closure of the issue.

**Comment by AzureDoom** [comment]
I closed after a week of no reply. I have no issues with my own fabric mods. If you are using Parchment it's unsupported at this time

**Comment by halotroop2288** [comment]
Your issue template and posting guidelines (read: lack thereof) does not state a deadline for issues to be resolved. It's customary to wait for a response in these matters, unless explicitly stated otherwise.

As mentioned above by @MiniDay, this issue does not occur while using Loom 0.9, and is likely caused by incompatibility with Loom 0.10.

Please ensure Geckolib is compliant with the latest version of Loom. Thank you.

**Comment by AzureDoom** [comment]
Loom 10 is unsupported as its the unstable branch, we target the stable.

**Comment by AzureDoom** [comment]
https://fabricmc.net/versions.html
 http://imgur.com/a/vmI4Eg9
