### ISSUE TITLE
1.16.5 rendering error

### ISSUE THREAD

**Issue by ClockworkzAI** [bernie-g/geckolib#186]
[crash-2021-10-06_15.47.36-client.txt](https://github.com/bernie-g/geckolib/files/7297101/crash-2021-10-06_15.47.36-client.txt)
Don't know if it is the same issues but getting crash issues on start up. Saying it is rendering issues, delete if duplicate

**Comment by AzureDoom** [comment]
Same as #187 

Has to be fixed by Epic Fight dev
