### ISSUE TITLE
[Blockbench Plugin] Cannot Export Display Settings

### ISSUE THREAD

**Issue by MarbleGateKeeper** [bernie-g/geckolib#196]
Click File->Export -> Export Geckolib Display Settings, and there is no reaction. More specifically, there is no window popup.
Try reinstall plugin & blockbench also do not work. 

Blockbench Version: 4.0.4
Plugin Version: 3.0.1
System: Win 10 20H2 **&** Win 11 **&** Window Server.
GeckoLib Model Setting: Block/Item

There is a strange thing: I've tried it on blockbench web app through Chrome. At first Export Geckolib Display Settings did not, but after I closed Chrome and reopened web app, and clicked "recover" file, exporting suddenly works.

**Comment by AzureDoom** [comment]
Since it resolved itself, the only thing I can chulk it up to is a BB bug. Let me know if happens again.
