### ISSUE TITLE
[Blockbench Plugin] Item display settings export doesn't works

### ISSUE THREAD

**Issue by D4RKAR117** [bernie-g/geckolib#204]
Click File->Export -> Export Geckolib Display Settings, and there is no reaction. More specifically, there is no window popup.
Try reinstall plugin & blockbench also do not work.

Blockbench Version: 4.0.5
Plugin Version: 3.0.1
System: Win 10 
GeckoLib Model Setting: Block/Item
Saving Model Project as: .bbmodel (converted)

Related with #196 

Additional Info, console of blockbench app:
![image](https://user-images.githubusercontent.com/23545823/143523628-1109473d-5511-4da9-aee1-41049a21381a.png)

Maybe related with this [line ](https://github.com/bernie-g/blockbench-plugins/blob/49fae50f4aac7e7a038e0e4482a74d8f92b63cdd/src/animation_utils/codec.js#L264) at the plugin repo

Posible problems:
- Fetching unexisting metadata from .bbmodel file

Export models as .geo.json works fine.

**Comment by D4RKAR117** [comment]
Solved at the geckolib Discord. Thanks

**Comment by NILEG2mc** [comment]
@D4RKAR117 
thw link is down !

**Comment by E1Company** [comment]
Can anyone help with blockbench not exporting geckolib model as geo.json but insted its plain json cuz mcreator won't take plain  json as a animated entity
