### ISSUE TITLE
stderror spamming console along CQR

### ISSUE THREAD

**Issue by Tot7uafag** [bernie-g/geckolib#205]
Good morning, while trying to debug a crash i have for chocolate quest repoured since last update of both mods, i noticed these messages are spamming my console, as im not an expert i dont know if this may be related or is something i should worry about or something ill just have to ignore, would you help me providing me some information please?

this is the Std error message im getting:
https://pastebin.com/pW7dzhGK

Thanks in advance.

Im using geckolib-forge-1.12.2-3.0.11.jar

Edit:
also, found this when console stopped spamming messages:

https://pastebin.com/6TJgXMB2

it seems like .json animation by mobends cannot be loaded f or something, but then why is there a line referencing chocolate quest repoured? i dont understand

**Comment by Tot7uafag** [comment]
also, found this when console stopped spamming messages:

https://pastebin.com/6TJgXMB2

**Comment by AzureDoom** [comment]
Yes, this and mobends with be incompatible due to it's use of an animations folder. This is the same as #187 and can not be fixed by us.
