### ISSUE TITLE
Fabric 1.18 - Adding a looping animation to an animation chain not looping

### ISSUE THREAD

**Issue by miyo6032** [bernie-g/geckolib#206]
I noticed this issue after upgrading to fabric-1.18 - 3.0.20. When using animation builder like so:
`                AnimationBuilder()
                    .addAnimation("attack", false)
                    .addAnimation("idle", true)`
The attack animation would play normally, but the idle animation does not loop afterward. I have a temporary fix currently that replaces the loop with `.addRepeatingAnimation("idle", 20)` but I was wondering if something changed. Setting the idle animation without any other animation before it like this also works as expected:
`AnimationBuilder().addAnimation("idle", true)`

**Comment by AzureDoom** [comment]
Will be fixed here soon
