### ISSUE TITLE
Fabric 1.18 - Mojmap name conflict

### ISSUE THREAD

**Issue by The-PPWD** [bernie-g/geckolib#208]
In Fabric 1.18, Loom fails with the following error.

```
Mapping target name conflicts detected:
  METHODs software/bernie/geckolib3/renderers/geo/GeoProjectilesRenderer/[getTextureLocation, net/minecraft/class_897/method_3931](Lnet/minecraft/class_1297;)Lnet/minecraft/class_2960; -> getTextureLocation
There were unfixable conflicts.
```

If I change the `getTextureLocation` method in `IGeoRenderer` to something else (I used `_getTextureLocation` just for testing), then this error is not thrown.

Versions used:

Minecraft: 1.18
Loom: 0.10-SNAPSHOT (0.10.63)
Mappings: Mojmap
GeckoLib: 3.0.21 (Fabric)

**Comment by AzureDoom** [comment]
Mojmappings are not supported and won't be supported due to the conflicts between Yarn and Mojmap. Until Fabric itself runs on Mojmap it won't be fixed.
