### ISSUE TITLE
Model not found

### ISSUE THREAD

**Issue by LeonHenning** [bernie-g/geckolib#210]
I added GeckoLib correctly to my build.gradle and everything works except for the resources. When I try to load a world the game crashes because it can't find the geckolib3:geo/creeper.geo.json file, I attached the debug log for more information
[debug.log](https://github.com/bernie-g/geckolib/files/7696977/debug.log) (MC 1.18)

**Comment by AzureDoom** [comment]
That log doesn't have a crash in it. Reload the game and test again.

**Comment by LeonHenning** [comment]
I cant find line I mean in the log so here it is `software.bernie.geckolib3.geo.exception.GeckoLibException: geckolib3:geo/creeper.geo.json: Could not find model. If you are getting this with a built mod, please just restart your game.`

**Comment by AzureDoom** [comment]
Congratulations you found the cache bug thats 1 out of 1000 launches and is unfixable.

**Comment by LeonHenning** [comment]
I get this error everytime I launch the game in IntelliJ

**Comment by AzureDoom** [comment]
Update to 1.18.1 and update the mod. Read the wiki for the changes to the name. Works fine in Eclipse for my own mods as well.
