### ISSUE TITLE
Will not run with the only mod I need it for, "The Graveyard"

### ISSUE THREAD

**Issue by Amatheiya** [bernie-g/geckolib#213]
1.17 worked just fine for me, but 1.18 refuses to work. Tells me I need to update Gekolib3, which I have. I'm still told it is out of date. It's the version that was literally updated 6 hours ago. 3.0.3 (Fabric)

The exact message states;

"ModResoulutionException: Mod resolution encountered an incompatible mod set!

   A potential solution has been determined:

          Install geckolib3, version 3.0.20 or later."

Everything is updated as of 12/22/21. I'm not sure exactly where the problem is so I'm posting this here and on The Graveyard page. 

If I've done something wrong in the installation step, please tell me, I'm not super tech saavy. Thank you, merry winter's veil!

**Comment by AzureDoom** [comment]
You will need resolve this with the mod dev of that mod, not this.
