### ISSUE TITLE
[1.18.1 Forge] Change of functioning of Transition Ticks in newer versions, is it intended?

### ISSUE THREAD

**Issue by Nitespring** [bernie-g/geckolib#214]
~~Instead of merging the last frame of an animation into the first few ticks of the next one, Transition Ticks will reset all bone orientations to the default, making the model snap into its "t-pose" state.~~

Here is a comparison between the behaviour in 1.16.5 and 1.18.1, without changes in the code except for changes unrelated to Geckolib:

1.16.5: https://streamable.com/grf005
1.18.1: https://streamable.com/3q3pqn

Code (only pasted the least complex entity, issue is the same for any entity anyway): https://paste.gg/p/anonymous/2c18720c19664dc09a46d86d352cd5a4

**Comment by Nitespring** [comment]
Ok, after experimenting a bit more with my code and animations it appears that Transition Ticks now work in a different way from how they did in the last version I used, for Forge 1.16.5. Transition Ticks used to delay the start and end of the animation, now they won't delay the animation but only influence it's first ticks.
Is this behaviour intended?
I'd like to know so that I can decide what to do. If it's not working as intended I'll wait for an update, otherwise I'll have to change things on my side. 
Please, let me know as soon as you can, thank you.

**Comment by AzureDoom** [comment]
@Nitespring if you are having this issue, please try Geckos suggestion here: https://github.com/bernie-g/geckolib/issues/211#issuecomment-1015546272
