### ISSUE TITLE
Abstract Method Error While Attempting to Render in Entity

### ISSUE THREAD

**Issue by PrestoSquesto** [bernie-g/geckolib#215]
Greetings! I am currently trying to modify a modpack (FTB Revelation) with Chocolate Quest Repoured and had my game crash when attempting to render in a specific boss. I had looked in CQR's issues and was reported to not be reproducible by someone with the same error report as me ( https://github.com/TeamChocoQuest/ChocolateQuestRepoured/issues/310 ). They were directed to come here and I could not find a closed or open forum with this issue. From my understanding this seemed to be a geckolib error and not a CQR error. Hope this can be resolved soon.

Minecraft Version: 1.12.2
Chocolate Quest Version: 2.6.2B
Geckolib Version: 3.0.13
Boss Trying to Render: Exterminator Prototype

[crash-2021-12-31_04.26.53-client.txt](https://github.com/bernie-g/geckolib/files/7796004/crash-2021-12-31_04.26.53-client.txt)

**EDIT**
I went back to geckolib version 3.0.12 and it doesn't crash while using the same modpack. Works just fine. This was suggested in the other bug report that I linked above. I'll keep this up so it can be looked into in future updates.

**Comment by AzureDoom** [comment]
Talked with CQM devs and since it's not reproduce with the latest of both mods, it's not an issue.
