### ISSUE TITLE
[1.12.2] Can't get geckolib working in my intellij

### ISSUE THREAD

**Issue by SupremeMarshal** [bernie-g/geckolib#216]
This is for the maven:
```
maven {
        url = "https://repo.repsy.io/mvn/gandiber/geckolib"
    }
```
and this is for the dependencies:

`deobfCompile('software.bernie.geckolib:forge-1.12.2-geckolib:3.0.0-beta.7')`

Running setupDecompWorkspace give me this error:

Could not find software.bernie.geckolib:forge-1.12.2-geckolib:3.0.0-beta.7.

**Comment by DrasticLp** [comment]
Use this repo : 
`repositories {
    maven { url = 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/' }
}`

**Comment by AzureDoom** [comment]
Not sure where you are getting this info about are outdated af
