### ISSUE TITLE
Replace GeckoLibMod.DISABLE_IN_DEV with a system property

### ISSUE THREAD

**Issue by Daomephsta** [bernie-g/geckolib#217]
The current approach requires mods wishing to disable the examples to load before GeckoLib. 
This is impossible to consistently achieve for Fabric mods, as Fabric deliberately loads mod entrypoints in an arbitrary order relative to other mods. 
Using a system property (via `java.lang.Boolean.getBoolean(String)`) would be a much better approach, as system properties can be set via VM launch arguments.

**Comment by AzureDoom** [comment]
It's to keep the system the same in both Forge and Fabric. Version parity is a high requirement.

**Comment by Daomephsta** [comment]
@AzureDoom 
System properties are a Java feature, version parity would not be affected. 
The current solution is literally broken in Fabric. If your mod happens to load after GeckoLib, you cannot turn it off.

**Comment by AzureDoom** [comment]
It's not an important feature 🤷🏻 shit only exists in dev.
