### ISSUE TITLE
[Fabric 1.18] combining animations ?

### ISSUE THREAD

**Issue by Azagwen** [bernie-g/geckolib#218]
I have a blockEntity which has multiple "idle" animations depending on its state, one needing to constantly loop on all instances of it, and others being state-dependent.

However, when I add the animation in code testing on state, only the first animation added plays

So with the following code, only `pulseAnim` will play, and the controller seems to completely ignore `wingFlapAnim`
```java
var wingFlapAnim = "animation.strawberry.flap_wings_loop";
var pulseAnim = "animation.strawberry.pulse_loop";

controller.setAnimation(new AnimationBuilder().addAnimation(pulseAnim).addAnimation(wingFlapAnim));
```
same with the opposite, with the code below, only `wingFlapAnim` plays, and `pulseAnim` is nowhere to be seen
```java
var wingFlapAnim = "animation.strawberry.flap_wings_loop";
var pulseAnim = "animation.strawberry.pulse_loop";

controller.setAnimation(new AnimationBuilder().addAnimation(pulseAnim).addAnimation(wingFlapAnim));
```

my whole code in [this repo](https://gitlab.com/Azagwen/celeste_mc/-/blob/1.18/src/main/java/azagwen/celeste_mc/StrawBerryBlockEntity.java#L44) if it helps
in case it is of any importance, I would also like to note that I have code-driven animations [here](https://gitlab.com/Azagwen/celeste_mc/-/blob/1.18/src/main/java/azagwen/celeste_mc/StrawBerryBlockEntityRenderer.java#L42) for this block

**Comment by Azagwen** [comment]
After a bit of inspection, it seems that `addAnimation` adds to a Queue??
Is there a way to combine animations ?

**Comment by Draylar** [comment]
Each controller can only run a single animation at a time. This is modeled after the Bedrock animation system. By calling: 

```java
controller.setAnimation(new AnimationBuilder().addAnimation(first).addAnimation(second));
```
You are queueing up 2 animations in a row - the second will run when the first is finished. If you want 2 animations to run at the same time, you'll need to add 2 separate controllers to your animation handling class:

```java
@Override
public void registerControllers(AnimationData data) {
    data.addAnimationController(new AnimationController<>(this, "wings", 10, this::handleWings));
    data.addAnimationController(new AnimationController<>(this, "pulse", 10, this::handlePulse));
}
```
This will allow you to layer/stack animations. For more information, I would recommend reading through the [wiki article on this topic](https://github.com/bernie-g/geckolib/wiki/Animation-Basics), which answers your question in detail.

**Comment by Azagwen** [comment]
Thanks for this precision! It worked like a charm :D

I don't know if this was mentioned in the wiki, perhaps I missed it?

**Comment by Azagwen** [comment]
well this has been answered, so ima close it
