### ISSUE TITLE
Animation tree not displaying after open model, as do the modified values too

### ISSUE THREAD

**Issue by GnRSlash** [bernie-g/geckolib#220]
When you are working with animations, sometimes the bone tree is empty but the animation is there and you can play it. This happens when you open a model and go to animations tab, but it occurs often  when working. This is terrible to work.

Another issue is: if you rotate a cube, when you select the cube by clicking at the cube drawing, the values are not updated, but it works if you click on the name of the bone.  Did I make myself clear?

Can you quickly fix these things please? It's hard to work if you pause work to continue later.
Thank you!

**Comment by bernie-g** [comment]
Can you test these in vanilla blockbench to make sure it's actually a geckolib plugin issue and not vanilla blockbench behavior?

**Comment by AzureDoom** [comment]
Please state Geckolib plugin version and blockbench version.

**Comment by GnRSlash** [comment]
> Can you test these in vanilla blockbench to make sure it's actually a geckolib plugin issue and not vanilla blockbench behavior?

I don't know how to do it, I don't know what is vanilla blockbench, and this is a plugin, so vanilla doesn't have this.

GeckoLib plugin ->  3.0.2
BlockBench -> 4.1.3

**Comment by AzureDoom** [comment]
> When you are working with animations, sometimes the bone tree is empty but the animation is there and you can play it. This happens when you open a model and go to animations tab, but it occurs often when working.

This is a Blockbench issue, due to the new tab system. Not something we are in control of. 

>  if you rotate a cube, when you select the cube by clicking at the cube drawing, the values are not updated, but it works if you click on the name of the bone.

This is working as intended, you don't use cubes, you use bones.
