### ISSUE TITLE
[Bug] : Replaced entity renderer doesnt provide the head pitch/yaw

### ISSUE THREAD

**Issue by ThatGravyBoat** [bernie-g/geckolib#223]
As the title says the head pitch and yaw aren't provided/set in the EntityModelData for a replaced entity renderer even when they are already calculated. 

As you can see in the normal renderer its added https://github.com/bernie-g/geckolib/blob/1.18/src/main/java/software/bernie/geckolib3/renderers/geo/GeoEntityRenderer.java#L131

But in the Replaced Entity Renderer it doesn't add them even when they are calculated: https://github.com/bernie-g/geckolib/blob/1.18/src/main/java/software/bernie/geckolib3/renderers/geo/GeoReplacedEntityRenderer.java#L140
In the replaced entity renderer `f2` would be `netHeadYaw` and `f6` would be `headPitch`

**Comment by AzureDoom** [comment]
Fixed in newest version for 1.16.5 and 1.18.1 Forge/Fabric. 1.12.2 already had it
