### ISSUE TITLE
[1.16.5 Forge] drop fps

### ISSUE THREAD

**Issue by dayd21git** [bernie-g/geckolib#226]
**Mod:** [ars_nouveau-1.16.5-1.24.14](https://www.curseforge.com/minecraft/mc-mods/ars-nouveau/files/3598702)
**Screen:** [day-d.ru/logs/ars-nouveau/issues-435/scr0001.jpg](https://day-d.ru/logs/ars-nouveau/issues-435/scr0001.jpg)
**Forge:** 36.2.22
**Desc:** Hello. I turned to the author of the Ars-Nouveau mod for help, but he could not help me. The author claims that the problem with his mod is related to your GECKOLIB library. Could you help me understand the situation and find the cause of the problem?
**Issue:** [github.com/baileyholl/Ars-Nouveau/issues/435](https://github.com/baileyholl/Ars-Nouveau/issues/435)
@baileyholl

P.S. Google translate

**Comment by AzureDoom** [comment]
It's a known issue with a PR in the works by the Flywheel dev. No ETA.

**Comment by AzureDoom** [comment]
This will be only for 1.19+ as this becoming a full rewrite. 1.16.5 will not receive this update.
