### ISSUE TITLE
[1.12 Forge] String to List Crash 2 - Electric Boogaloo

### ISSUE THREAD

**Issue by CitrusHappy** [bernie-g/geckolib#227]
[crash report](https://paste.gg/376f9c47267c4b1c85dafec21bc351e4)

same issue as #197 

I've been trying to add instruction keyframes in my animation.json, but it keeps crashing regardless of my mod's code. Rather, removing the instruction keyframes prevents the crash.

To reproduce, simply create a Geckolib model with an instruction keyframe and attempt to render it in 1.12.x.

### I've dug up the relevant commits for ease of access:
[fix commit in 1.16](https://github.com/bernie-g/geckolib/commit/37ecac2a3d6930c6c2d7ef64b45c4527023b6fc3)
[attempted fix commit in 1.12](https://github.com/bernie-g/geckolib/commit/200cd5bf3093a093f6d8f593554ea806834cd804#diff-62871df73675bce75c9e1e54e8c30b01637dcb42df0483489776ed8dbfbea821)

**Comment by CitrusHappy** [comment]
Figured it out. Default Blockbench saves the json like this if there is only one line in the script box:
`			"timeline": {
				"0.0": "scriptname"
			}`

Geckolib is expecting a list (as it should) like this:
`			"timeline": {
				"0.0": ["scriptname"]
			}`

the second option works perfectly but requires manual editing. a solution to this would be to check first if it's a list or a single string, then react accordingly.

**Comment by AzureDoom** [comment]
That is a known issue with the plugin, I can't fix it. If anyone is good with JavaScript, I'd love a second look. https://github.com/bernie-g/blockbench-plugins/blob/master/plugins/animation_utils.js#L633-L646

**Comment by bernie-g** [comment]
> That is a known issue with the plugin, I can't fix it. If anyone is good with JavaScript, I'd love a second look. https://github.com/bernie-g/blockbench-plugins/blob/master/plugins/animation_utils.js#L633-L646

I don't think this is an issue with the plugin. We should just allow both a list and a single value in Geckolib.
