### ISSUE TITLE
geckolib 3.0.10 crashes Ars Nouveau

### ISSUE THREAD

**Issue by reddraegon** [bernie-g/geckolib#228]
game crashes after trying to render a "mage book" and crashes instantly.
if theres more files needed just ask.
[2022-01-29-4.log](https://github.com/bernie-g/geckolib/files/7963699/2022-01-29-4.log)
[latest.log](https://github.com/bernie-g/geckolib/files/7963693/latest.log)
EDIT: not geckolib 3.0.10 but geckolib 3.0.64 and .63 works fine

**Comment by AzureDoom** [comment]
PR already sent to Ars, this is an important fix that will be released on their side.
