### ISSUE TITLE
[1.16.5 Forge] GeckoLib 3.0.65 appears to cause rendering crash: java.lang.NoSuchFieldError: instructions

### ISSUE THREAD

**Issue by autumn-birds** [bernie-g/geckolib#229]
This issue appears when a specific mob added by Mana and Artifice tries to attack the player, and sometimes randomly when the mob is presumably wandering somewhere in the world. I am not sure if it is an issue with GeckoLib, or an issue with Mana and Artifice which GeckoLib "uncovered" with, i.e., a bug fix. Downgrading to GeckoLib 3.0.64 fixed this for me, but I thought it was worth making a note of -- sorry for any irritation.

Here is the crash log I got: https://pastebin.com/jAzRGPad

Issue on the Mana and Artifice repo: https://github.com/Mithion/Mana-And-Artifice/issues/424

**Comment by AzureDoom** [comment]
This is known and is on Mana and Artifice to fix. The dev is already aware and will be fixing it. Downgrade Geckolib for now.
