### ISSUE TITLE
Make GeoEntityRenderer render leash?

### ISSUE THREAD

**Issue by Conclure** [bernie-g/geckolib#234]
The leash does not render as shown below (just for the pig, not the other model which uses GeoEntityRenderer):
![2022-03-27_03 39 00](https://user-images.githubusercontent.com/63319713/160262992-85a1ad53-0ba4-4a4d-8e6e-6e568c0a1adc.png)
 
This image was taken using Fabric on 22w11a. To elucidate this issue, it seems like normal minecraft code renders the leash in (Mojang mappings) MobRenderer#renderLeash which is a private method. Conversely to geckolib as of now which does not have any rendering method/logic for leashes in  GeoEntityRenderer. Is this feature planned to be added in the near, forseeable future?

**Comment by AzureDoom** [comment]
This logic requires logic from Mob Entity and will require you to create a custom Renderer using that instead of living entity. This will not be be added to the base library
