### ISSUE TITLE
Translation ending in error

### ISSUE THREAD

**Issue by SaltyPotat0** [bernie-g/geckolib#236]
When trying to translate "net/minecraft/client/player/LocalPlayer.displayClientMessage" I recieve an error and a notification to report it.
<img width="449" alt="image" src="https://user-images.githubusercontent.com/74806654/161393980-ae0bd6b6-eb2e-4371-953a-dc7178e9dca7.png">

**Comment by AzureDoom** [comment]
That is a linkie issue, not a Geckolib issue.

**Comment by SaltyPotat0** [comment]
Sorry! I meant to post this on Linkies github and must have gotten confused.
