### ISSUE TITLE
Crash minecraft 1.18.2, forge 40.1.0, Gecolib forge from 3.0.12 to 3.0.15 version.

### ISSUE THREAD

**Issue by Dralink96** [bernie-g/geckolib#244]
By trying join in server or create my own single world i have crash with this log.

I know the issue is from your side, because without your mode everything is working correct. 
There is one mode that require your library is DragonSurvival 1.18.2 but also without him the game still crash only by removing that 2(dragon and your) mods it's start work correct.
The same issue from all checked versions from 0.12 to 0.15
[crash-2022-04-27_01.37.38-client.txt](https://github.com/bernie-g/geckolib/files/8567392/crash-2022-04-27_01.37.38-client.txt)
[crash-2022-04-27_01.39.33-client.txt](https://github.com/bernie-g/geckolib/files/8567393/crash-2022-04-27_01.39.33-client.txt)
[crash-2022-04-27_01.43.31-client.txt](https://github.com/bernie-g/geckolib/files/8567394/crash-2022-04-27_01.43.31-client.txt)
[crash-2022-04-27_01.48.48-client.txt](https://github.com/bernie-g/geckolib/files/8567395/crash-2022-04-27_01.48.48-client.txt)
[crash-2022-04-27_01.23.23-client.txt](https://github.com/bernie-g/geckolib/files/8567396/crash-2022-04-27_01.23.23-client.txt)

.

**Comment by Dralink96** [comment]
I think there is possible issue between your mode and another from list, but in any case, I provided the problem and how to solve it is up to you.

good luck :)

**Comment by Dralink96** [comment]
maybe find the problem
OptiFine_1.18.2_HD_U_H7

**Comment by AzureDoom** [comment]
Optifine is not supported and never will
