### ISSUE TITLE
Entity model flattens/flickers at the start of molang animations that affect the mob's scale

### ISSUE THREAD

**Issue by samedifferent** [bernie-g/geckolib#253]
### Mod Version

3.0.18

### Mod Loader

Forge

### Mod Loader Version

40.1.25

### What happened?

At the start of molang animations that affect the mob's scale, the model will flatten, but the animation continues normally after that. This occurred when transition length ticks were > 0.  When transition length ticks are set to 0, it fixes the flattening, but the model flickers for 1 tick. I was told to try removing markNeedsReload and setting transition length ticks to 1, but they did not fix the issue.

**Transition length ticks > 0:** https://cdn.discordapp.com/attachments/730913831026688157/981238251950075975/caterpillar.mp4
**Transition length ticks = 0:** https://cdn.discordapp.com/attachments/730913831026688157/981242568350248990/caterpillar3.mp4
**Animation json:** https://pastebin.com/XkqtDymg
**Animation controller and predicate:** https://pastebin.com/1dqjzEuH

I also reported this in your discord server, if you would like to see the messages: https://discord.com/channels/730912704776110121/730913831026688157/981238250746290237

**Comment by AzureDoom** [comment]
BTW Gecko did a core tweak that should help with this, please test the latest.

**Comment by AzureDoom** [comment]
Please reopen if still an issue with latest.
