### ISSUE TITLE
Crash on server startup. Index out of bounds

### ISSUE THREAD

**Issue by Buck525** [bernie-g/geckolib#256]
[debug-1.log](https://github.com/bernie-g/geckolib/files/8837282/debug-1.log)
[crash-2022-06-04_02.04.31-fml.txt](https://github.com/bernie-g/geckolib/files/8837287/crash-2022-06-04_02.04.31-fml.txt)

On server startup crashes with out of bounds exception.

Reverting to previous version (3.0.18) fixes the crash.

**Comment by thepriz** [comment]
I can confirm I am seeing this crash also.

**Comment by Potatomonium** [comment]
I too am having this issue for geckolib-1.18-forge-3.0.19.jar

**Comment by Phweeeee** [comment]
I don't know if this is the same issue. but I'm having a server startup error on 3.0.72. 1.16.5 forge. 

https://paste.gg/p/anonymous/ece755c4ab76423b9094c6c7386b884c

**Comment by AzureDoom** [comment]
![image](https://user-images.githubusercontent.com/7415711/172003198-5708824b-da77-4c53-aec4-6127ae03922c.png)
Please list what mods you are using, no issues here.

**Comment by AzureDoom** [comment]
wait nevermind, seen about server, let me double check.
