### ISSUE TITLE
No Forge 1.16.5 Code Bits in Block Animations Page on Wiki (I think).

### ISSUE THREAD

**Issue by ColbaltheWyvern** [bernie-g/geckolib#260]
I wasn't sure where to put this, so I just put it in issues, but in the wiki on the [Block Animations](https://github.com/bernie-g/geckolib/wiki/Block-Animations) page, there are only code bits for Forge/Fabric 1.18.1. 

(e.g.: 
`@Override public RenderShape getRenderShape(BlockState state) { return RenderShape.ENTITYBLOCK_ANIMATED; }` for Forge and 
`@Override public BlockRenderType getRenderType(BlockState state) { return BlockRenderType.ENTITYBLOCK_ANIMATED; }` for Fabric) 

But I was trying to use GeckoLib on Forge 1.16.5, and I was wondering if I just missed something (if I did I'm sorry I wasted your time) or there truly is nothing for 1.16.5, and if there isn't than can someone help me out with the code?

Thank you for your time,
ColbaltheWyvern

**Comment by AzureDoom** [comment]
The wiki is for 1.18+

**Comment by AzureDoom** [comment]
> Then I feel like it's kinda misleading that they're 1.16.5 code bits in Installation, but thanks for responding so quickly.

The example mod exists for all versions/branches, the wiki is just shows how to add for any version but examples are for latest.

**Comment by ColbaltheWyvern** [comment]
Ahh... I see. Ok, thank you for your time, great mod by the way.
