### ISSUE TITLE
The version of quilt is lower can't satisfy dependents

### ISSUE THREAD

**Issue by SettingDust** [bernie-g/geckolib#262]
`Depencency for mod 'bosses_of_mass_destruction' on geckolib3 versions [>=3.0.22] (0 valid options, 0 invalid options)`

`geckolib-quilt-1.18-3.0.9`

**Comment by SettingDust** [comment]
It's not same

**Comment by AzureDoom** [comment]
You can't use Quilt Geckolib with Fabric mods. Use the actual Fabric version.
