### ISSUE TITLE
Geckolib3 using deprecated Pollen animations

### ISSUE THREAD

**Issue by UnseenAcademical** [bernie-g/geckolib#267]
When checking the latest.log to help me track down a datapack error, it seemed to stem from the following line:

[Worker-Main-21/ERROR] [LocalAnimationLoader/]: Mod: geckolib3 is using deprecated Pollen animations. Animations should be relocated to 'assets/geckolib3/pinwheel/animations'

Leading to

java.lang.NullPointerException: Expected to wait for resource modifiers, but serverReloader was null
	at gg.moonflower.pollen.api.resource.modifier.ResourceModifierManager.getServerCompleteFuture(ResourceModifierManager.java:117) ~[pollen-forge-1.4.3+1.18.2.jar%23210!/:?]

**Comment by AzureDoom** [comment]
This a pollen issue, we have not integration with them, all integration is on Pollons side.
