### ISSUE TITLE
Clipping Problems on Geckolib Armor

### ISSUE THREAD

**Issue by TheSuum** [bernie-g/geckolib#270]
**Fabric Version:**
0.57.0

**Geckolib Version:**
3.1.5

**Minecraft Version:**
1.19

**The Issue:**
There is some kind of clipping problem in the armor as you can see on the pictures on the left. I've used an armor from the Doom mod of AzureDoom and an armor of my mod as examples of the problem. The pictures on the right are showing how the armor is looking like in the 1.19-3.1.6 Forge version.

![Comparison](https://user-images.githubusercontent.com/108454643/176623930-31b24e2f-1abb-4fb3-8313-f504e4f46e43.png)

**Comment by AzureDoom** [comment]
@TheSuum is your mod released? I'd like to pull it in for testing as pulling Doom currently is PITA due to some bugs.

**Comment by TheSuum** [comment]
I haven't released it yet, would you want that I setup a github for it ?

**Comment by AzureDoom** [comment]
> I haven't released it yet, would you want that I setup a github for it ?

If you can dm a jar, I can it private maven it and pull it in that way. Your armor would make it easier for me to test.

**Comment by TheSuum** [comment]
Yea sure, I'll send it to you on discord.
