### ISSUE TITLE
1.19 Latest Forge Crash

### ISSUE THREAD

**Issue by LoxiGoose** [bernie-g/geckolib#273]
Currently GeckoLib crashes on the latest versions of Forge upon startup.

Minecraft Version: 1.19
Forge Version: 41.0.94
Mod Version: 3.1.7

Crash Log: https://mclo.gs/tTcHEkl

**Comment by Baggytrousers27** [comment]
Fair enough.

**Comment by LoxiGoose** [comment]
Alright, that's fine. I can wait. Thanks for responding :)
