### ISSUE TITLE
mobs heads pop out of player

### ISSUE THREAD

**Issue by Misterglace27** [bernie-g/geckolib#274]
Forge Version:
36.2.35

Geckolib Version:
3.0.81

Minecraft Version:
1.16.5

The Issue:
(Even though I could only see this on mowie mobs attack animations, I think the problem is with the mod.) When I run an animation, the large mob heads come out of the characters with f5, (mob heads dragons, twilight forest trophy,...)
 for multiplayer, the heads will appear in front of the nearby players in addition to the f5.
 
![2022-07-14_18 26 17](https://user-images.githubusercontent.com/54781312/179032272-28a0d625-4e4e-4ac7-ab08-de660cd780ed.png)
![2022-07-14_18 26 28](https://user-images.githubusercontent.com/54781312/179032309-c55ac0d5-eeb4-4bda-9608-04db4d07fa9a.png)
![2022-07-14_18 30 37](https://user-images.githubusercontent.com/54781312/179032330-737883ee-ac98-4406-b8e1-8eabaa164ea2.png)

**Comment by AzureDoom** [comment]
You will need to make issue with mowzies.
