### ISSUE TITLE
Minecraft is Telling me that I'm missing geckolib3 (IT'S NOT)

### ISSUE THREAD

**Issue by ItsKondz** [bernie-g/geckolib#275]
So I downloaded gecko lib 3 for armorplus and added it in but for some reason it still says that it requires geckolib 3 and I will need help with this issue because i feel like minecraft just broke in front of me from some sort of illusion

![image](https://user-images.githubusercontent.com/109123759/180358757-2cd27353-6725-4427-a570-a4af2ed1d7c6.png)

![image](https://user-images.githubusercontent.com/109123759/180358879-c223802c-2bee-402b-b741-80277bde8ac4.png)

**Comment by ItsKondz** [comment]
What about the file name?

**Comment by AzureDoom** [comment]
Reading is important

**Comment by ItsKondz** [comment]
But I still dont get why tf it's asking me for the mod when it was literally the latest damn mod from curse forge

**Comment by bernie-g** [comment]
You are using the quilt version of Geckolib on Forge. Please check carefully before making Github issues, this is not what they are for. Locking this issue now.
