### ISSUE TITLE
Add project to modrinth.com

### ISSUE THREAD

**Issue by Sammcb** [bernie-g/geckolib#285]
Hi, would it be possible for you to add this mod to [modrinth](https://www.modrinth.com/)?

Modrinth is an open source alternative to CurseForge and offers a great API for users to interact with mods and modpacks. I am building a script to help manage modpacks that uses the modrinth API. Since this mod is a dependency of a lot of other mods, it would be really helpful to have it registered on modrinth so other mods could use use that API feature.

Thanks so much!

**Comment by AzureDoom** [comment]
Modrinth support will be pushed once they have removed the version system, which is slated for later this week. Until then Geckolib will not be postable.

**Comment by Sammcb** [comment]
Got it, thanks!
