### ISSUE TITLE
1.19 Version on Modrinth

### ISSUE THREAD

**Issue by ryleu** [bernie-g/geckolib#287]
Howdy! I'm looking for a 1.19 compatible version of gecklib, but I was not able to find it on Modrinth. If it's not too difficult, would you mind backporting it to 1.19 and adding it to the Modrinth page? I am trying to make a modpack, but many mods are still on 1.19.

**Comment by AzureDoom** [comment]
1.19 is only on CurseForge and not supported as well. We only support latest versions of a version.

**Comment by ryleu** [comment]
I know it's not supported, I'm just asking you to put it on modrinth as well as curseforge.

**Comment by AzureDoom** [comment]
We are only adding the latest version of a major release + any updates done to Modrinth. You can get any previous versions from CurseForge if you need it.
