### ISSUE TITLE
getWorldPosition() doesn't work (1.16.5)

### ISSUE THREAD

**Issue by AlexandersFunAndGames** [bernie-g/geckolib#293]
Trying to make particles spawn at a certain bone
but, when using getWorldPosition(), they spawn in different places depending on where you're looking
and getPosition() simply returns 0, 0, 0

**Comment by AlexandersFunAndGames** [comment]
Also seems to happen in 1.19.2, and with any model

**Comment by AzureDoom** [comment]
Closing as per discord discussions of getWorldPosition removal.
