### ISSUE TITLE
Shaders break everything (Fabric)

### ISSUE THREAD

**Issue by NordAct** [bernie-g/geckolib#295]
Using shaders smh breaks a lot of stuff. From bone hiding to animations

Video with demonstration: https://youtu.be/yPwOsZBQNL0

Mods used for demo: 
Cloth Config API (ver. 8.2.88): https://www.curseforge.com/minecraft/mc-mods/cloth-config/files/3972420
Geckolib (ver. 3.1.20): https://www.curseforge.com/minecraft/mc-mods/geckolib/files/3989825
Sodium (ver. 0.4.4): https://www.curseforge.com/minecraft/mc-mods/sodium/files/3957319
Indium (ver. 1.0.9): https://www.curseforge.com/minecraft/mc-mods/indium/files/3957480
Iris (ver. 1.3.1): https://www.curseforge.com/minecraft/mc-mods/irisshaders/files/3981799
Useless Reptile (ver. 0.1.1): https://www.curseforge.com/minecraft/mc-mods/useless-reptile/files/3998332

Used shaders for demo: https://www.curseforge.com/minecraft/customization/bsl-shaders/files/3868240 (although I saw people having issues with other shaders too)

Logs: [latest.log](https://github.com/bernie-g/geckolib/files/9640585/latest.log)

P.S. Useless Reptile is my mod, so feel free to contact if more info needed

**Comment by AzureDoom** [comment]
Iris works fine with Geckolib, its not an issue with our side. I use shaders with my own Fabric mods that use Geckolib
