### ISSUE TITLE
Geckolib v1.1.20 causes crash but v3.1.19 works fine, on Fabric 1.19.2

### ISSUE THREAD

**Issue by TalEdd** [bernie-g/geckolib#296]
Attached is crash report: [crash-2022-09-25_22.19.27-client.txt](https://github.com/bernie-g/geckolib/files/9640955/crash-2022-09-25_22.19.27-client.txt)

**Comment by AzureDoom** [comment]
Issue with bwplus, not Geckolib. Report to that dev.
