### ISSUE TITLE
Gecko lib causes crash

### ISSUE THREAD

**Issue by MOOOOs** [bernie-g/geckolib#297]
[crash-2022-09-25_19.00.21-client.txt](https://github.com/bernie-g/geckolib/files/9641186/crash-2022-09-25_19.00.21-client.txt)

**Comment by AzureDoom** [comment]
Not a Geckolib issue.

**Comment by MOOOOs** [comment]
So what issue then?

**Comment by AzureDoom** [comment]
Check your mods but that crash log does state Geckolib in it at all.
