### ISSUE TITLE
[1.12.2]The model is offset up a bit&Smooth interpolation is not supported

### ISSUE THREAD

**Issue by Ironnoob73** [bernie-g/geckolib#307]
As the question suggests, the model rendered in the game is offset upwards a little.
![image](https://user-images.githubusercontent.com/67966070/195643587-e40214f6-20b0-4b4c-9f50-1b67dcd68c05.png)
Smooth interpolation added for animations in blockbench is not recognized correctly.
![image](https://user-images.githubusercontent.com/67966070/195644410-81887c30-fea2-4e3b-9054-33c9468fe098.png)
The small action with the interpolation will not played.

**Comment by AzureDoom** [comment]
Yes, it's offset due to a lighting bug with tile entities and we do not support the bedrock animation format, we have our own.
