### ISSUE TITLE
In game description shows old versions

### ISSUE THREAD

**Issue by Mr1cecream** [bernie-g/geckolib#308]
The in game description which can be viewed in ModMenu shows versions up to Minecraft 1.16 as seen in screenshot below:
![image](https://user-images.githubusercontent.com/88837169/195902329-d7c79418-6175-4212-b729-d94e821a40a1.png)

**Comment by AzureDoom** [comment]
Just out-dated info is all, will be updated at some point but it doesn't affect anything.
