### ISSUE TITLE
Dedicated server crash with 3.0.47 for Forge 1.18.2

### ISSUE THREAD

**Issue by katubug** [bernie-g/geckolib#317]
Hi! I'm running

Minecraft: 1.18.2
Forge: 40.2.84
GeckoLib: 3.0.47

And I get the following log when I try loading up my dedicated server: https://pastebin.com/qmy1m6bY

It does not produce a crash report, so all I have is the console log. I have tested with version 3.0.46 and the issue does not occur. Thanks for your time!

**Comment by drakray** [comment]
Single player also refuse to boot up, forge 84, Geckolib 47, rolling back to 46 fixes

**Comment by AzureDoom** [comment]
Will be fixed in this update here, merging another fix then releasing.
