### ISSUE TITLE
Game not Loading

### ISSUE THREAD

**Issue by Daihok41** [bernie-g/geckolib#318]
With the newest Fabric version 1.19.2 -3.1.27 for some reason game not loading it just sticks at loading screen about 3/4th of the way loaded. reverting back to 3.1.26 runs fine

**Comment by TheeMrCheeky** [comment]
Ya my game won't load as well on forge version

**Comment by ffuentesm** [comment]
Same problem, geckolib-forge-1.19-3.1.29.jar has a problem when trying to launch.

**Comment by AzureDoom** [comment]
Two different issues here: 

> Same problem, geckolib-forge-1.19-3.1.29.jar has a problem when trying to launch.

> With the newest Fabric version 1.19.2 -3.1.27 for some reason game not loading it just sticks at loading screen about 3/4th of the way loaded. reverting back to 3.1.26 runs fine

Main issue is a shaded library issue, fixed now. 

> ![image](https://user-images.githubusercontent.com/96976998/197881285-868ddd07-8ed1-41f6-9553-25b3e1e0bf70.png) Ya my game won't load as well on forge version I went back to this version and it works geckolib-forge-1.19-3.1.28.jar

your issue was a CurseForge issue with the latest file.
