### ISSUE TITLE
causing error on server startup?

### ISSUE THREAD

**Issue by Thisguyneedshelp** [bernie-g/geckolib#320]
Theres no crash report and the logs dont show really anything the best i can give you are these lines from the server console 
25.10 22:11:20 [Server] INFO Exception in thread "main" java.lang.module.ResolutionException: Modules geckolib3 and com.google.gson export package com.google.gson.reflect to module powershot
25.10 22:11:20 [Server] INFO at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
25.10 22:11:20 [Server] INFO at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:815)
25.10 22:11:20 [Server] INFO at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:736)
25.10 22:11:20 [Server] INFO at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
25.10 22:11:20 [Server] INFO at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
25.10 22:11:20 [Server] INFO at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
25.10 22:11:20 [Server] INFO at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:75)
25.10 22:11:20 [Server] INFO at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:60)
25.10 22:11:20 [Server] INFO at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.run(Launcher.java:104)
25.10 22:11:20 [Server] INFO at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
25.10 22:11:20 [Server] INFO at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
25.10 22:11:20 [Server] INFO at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.8/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
25.10 22:11:20 [Server] INFO at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)

**Comment by AzureDoom** [comment]
Update your mod, this was already fixed.

**Comment by Thisguyneedshelp** [comment]
i see, curseforge auto updated to the second latest one
