### ISSUE TITLE
What happened?

### ISSUE THREAD

**Issue by krjencik** [bernie-g/geckolib#325]
[crash-2022-10-28_15.26.28-client.txt](https://github.com/bernie-g/geckolib/files/9888845/crash-2022-10-28_15.26.28-client.txt)

**Comment by AzureDoom** [comment]
One of your mods need to be updated

**Comment by krjencik** [comment]
> One of your mods need to be updated

which one? Im using curseforge launcher...

**Comment by AzureDoom** [comment]
AoA3

**Comment by krjencik** [comment]
tyyyyy
\
