### ISSUE TITLE
Crash on server with Animations/Critters and Companions

### ISSUE THREAD

**Issue by katubug** [bernie-g/geckolib#327]
Hi! I'm crashing on my server when I attempt to go to a particular area, presumably with a ferret in it?

Minecraft: 1.18.2
Forge: 40.1.84
Geckolib: 3.0.49
Critters and Companions: 1.0.2

Crash log: https://bytebin.lucko.me/CyNrDZrnzu

**Comment by AzureDoom** [comment]
They need to update
