### ISSUE TITLE
Laggy transition between controllers/Looping animations are completely broken

### ISSUE THREAD

**Issue by NerdyPuzzle** [bernie-g/geckolib#330]
I tested versions 3.0.49/3.0.50 and 3.1.31/3.1.32 and in both, when transitioning between controllers, a frame of the default pose will appear in between. 

This persists between all the versions that I tested in multiple projects. Also, looping animations will either not stop or not start at all. I've tested the example car model and the issue is present, so I know it is neither my code nor models that are causing this. (only on versions 3.0.50 and 3.1.32)

Reverting back down to 3.1.30 or 3.0.48 seems to fix everything.

https://imgur.com/9hRQKTe.mp4

This was recorded in a new, completely clean 1.19.2 project with version 3.1.32

**Comment by MajAlva** [comment]
Same issues and more https://imgur.com/NEkpcuz.mp4

3.1.29 breaks model parts
3.1.31 breaks animation controllers (laggy transition)
3.1.32 (not shown in the video) broke all of my looping animations even after updating to the new methods

**Comment by MajAlva** [comment]
Actually, in 3.1.32 my poor model was even more broken with some parts not even being part of the body anymore...

**Comment by AzureDoom** [comment]
This is fixed in dev with more fixes coming, no ETA on release.
