### ISSUE TITLE
Crash with geckolib-fabric-1.19-3.1.30.

### ISSUE THREAD

**Issue by Cr4fTJuNkiE** [bernie-g/geckolib#331]
Just had a crash with the new version.

[crash-2022-10-30_14.23.36-client.txt](https://github.com/bernie-g/geckolib/files/9896566/crash-2022-10-30_14.23.36-client.txt)

**Comment by FreeFull** [comment]
I've just hit the exact same crash on Forge, so it's not fabric-specific.

**Comment by AzureDoom** [comment]
graveyard has to compile against latest changes. Intended.

**Comment by Cr4fTJuNkiE** [comment]
Aaah. Okay. Thanks.

**Comment by Cr4fTJuNkiE** [comment]
Just made a issue on the graveyad github.

**Comment by Daihok41** [comment]
Yea the newest versions of Gecko forcing alot of mods to update Mythic mounts graveyard useless reptiles list is big lol. I will stick to .26 version till everyone else fixs i guess
