### ISSUE TITLE
Problem with geckolib installation for forge 1.19

### ISSUE THREAD

**Issue by DetectiveEleonoreCC** [bernie-g/geckolib#333]
I've followed the installation steps layed out here: https://github.com/bernie-g/geckolib/wiki/installation, using the Forge 1.19.2 snippets (I'm using 1.19 and not 1.19.2 but there was no 1.19 one, only 1.18 and 1.19.2, so I assumed 1.19.2 would work). It gives me an error when I try to load gradle changes. Here are the errors: 

"Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find software.bernie.geckolib:geckolib-forge-1.19:3.1.36."

"Could not resolve all files for configuration ':runtimeClasspathCopy'.
> Could not find software.bernie.geckolib:geckolib-forge-1.19:3.1.36_mapped_official_1.19.
  Searched in the following locations:
    - file:/C:/Users/[name removed]/.gradle/caches/forge_gradle/bundeled_repo/software/bernie/geckolib/geckolib-forge-1.19/3.1.36_mapped_official_1.19/geckolib-forge-1.19-3.1.36_mapped_official_1.19.pom
    - file:/C:/Users/[name removed]/.gradle/caches/forge_gradle/bundeled_repo/software/bernie/geckolib/geckolib-forge-1.19/3.1.36_mapped_official_1.19/geckolib-forge-1.19-3.1.36_mapped_official_1.19.jar
  Required by:
      project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html"

And here is my build.gradle file: https://pastebin.com/euQ38d85

Any help is appreciated, thanks :) Also, sorry if the answer is obvious, I'm pretty new at minecraft modding lol.

**Comment by AzureDoom** [comment]
1.19 is not supported
