### ISSUE TITLE
Help with geckolib installation for 1.19.2

### ISSUE THREAD

**Issue by DetectiveEleonoreCC** [bernie-g/geckolib#335]
I previously signaled a similar issue but I was using the wrong version, 1.19 instead of 1.19.2. Seeing the response that 1.19 wasn't supported, I updated my forge version to 1.19.2-43.1.1 (the recommended version), and I know it updated correctly because I can run the game and it shows up as 1.19.2, however, when adding the geckolib installation line in my build.gradle file, I still get the same errors as before when trying to load gradle changes! 
I also tried various different versions of 1.19.2 including 1.19.2-43.1.47 (most recent) and 1.19.2-43.1.3, but they didn't work. 
Here are the errors:

Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find software.bernie.geckolib:geckolib-forge-1.19:3.1.36.

Could not resolve all files for configuration ':runtimeClasspathCopy'.
> Could not find software.bernie.geckolib:geckolib-forge-1.19:3.1.36_mapped_official_1.19.2.
  Searched in the following locations:
    - file:/C:/Users/[name removed]/.gradle/caches/forge_gradle/bundeled_repo/software/bernie/geckolib/geckolib-forge-1.19/3.1.36_mapped_official_1.19.2/geckolib-forge-1.19-3.1.36_mapped_official_1.19.2.pom
    - file:/C:/Users/[name removed]/.gradle/caches/forge_gradle/bundeled_repo/software/bernie/geckolib/geckolib-forge-1.19/3.1.36_mapped_official_1.19.2/geckolib-forge-1.19-3.1.36_mapped_official_1.19.2.jar
  Required by:
      project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

Here's my build.gradle file: https://pastebin.com/kWUQH4r7

**Comment by AzureDoom** [comment]
Look at the examples clearly linked on the wiki.
