### ISSUE TITLE
1.18.2 fabric crashing from 3.0.70 onward

### ISSUE THREAD

**Issue by Abalieno** [bernie-g/geckolib#340]
I suppose one of the problem is the Graveyard mod that isn't getting updated anymore for 1.18.2 ?
Is that all?

Among all the errors there's still one reported previously:

[Render thread/INFO]: Caught error loading resourcepacks, removing all selected resourcepacks
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: No enum constant software.bernie.geckolib3.core.builder.ILoopType.EDefaultLoopTypes.FALSE
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.4) ~[?:?]

The rest is all:
java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 0

[latest - Copy.log](https://github.com/bernie-g/geckolib/files/10009830/latest.-.Copy.log)

**Comment by AzureDoom** [comment]
That would be likely graveyard, it's on their end to update.
