### ISSUE TITLE
animationLength Crash on World Load

### ISSUE THREAD

**Issue by Gamerbolts** [bernie-g/geckolib#341]
Hello!

I am creating a rather large modpack and upon loading into the world I crashed. Here are the logs. Any help is appreciated thank you!

[crash-2022-11-15_15.19.00-client.txt](https://github.com/bernie-g/geckolib/files/10016315/crash-2022-11-15_15.19.00-client.txt)
[latest.log](https://github.com/bernie-g/geckolib/files/10016317/latest.log)

**Comment by Gamerbolts** [comment]
This is also with the latest version of Geckolib for Fabric 3.1.36

**Comment by AzureDoom** [comment]
Report to mythicmounts.

**Comment by Gamerbolts** [comment]
I did post to them as well. Thanks.
