### ISSUE TITLE
Iris is "not compatible" with GeckoLib

### ISSUE THREAD

**Issue by ZGStuff** [bernie-g/geckolib#344]
Recently I launched my new modpack, Ultimatum, with Iris Shaders, and inside the modpack is GeckoLib and Wonderous Wilds. After loading into a world, it said that geckolib is not compatible with Iris Shaders. Is this fixed, or an ongoing issue? I'm using GeckoLib version 3.1.26 for Fabric 1.19/1.19.2.

**Comment by AzureDoom** [comment]
That's someone on the Iris team to look at they make changes to client ticking.

**Comment by ZGStuff** [comment]
ah ok
