### ISSUE TITLE
Crash on init

### ISSUE THREAD

**Issue by DavyJonesSocks** [bernie-g/geckolib#35]
Hey, I just wanted to load my animation from Blockbench with your library. But right when I was to run the client, this error occured. I couldn't find anything online really. So I guess it is a bug...

Stacktrace:
```
[17:00:50] [modloading-worker-2/ERROR] [ne.mi.fm.ja.FMLModContainer/LOADING]: Failed to create mod instance. ModID: smiths_forgeryreloaded, class com.drimogg.forgeryreloaded.ForgeryReloaded
java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: net/minecraftforge/fml/DistExecutor$SafeRunnable
	at software.bernie.geckolib.GeckoLib.initialize(GeckoLib.java:22) ~[?:3.0.0-beta.7] {re:classloading}
```

I am no Java developer so I'm not really sure, what is wrong... but is seems like this `DistExecutor` is causing the error.
If you need anything else let me know. Thanks in advance!

OS: Windows 10
Forge: 1.15.2
GeckoLib: 3.0.0-beta.7
Java: JDK 1.8.0_221

**Comment by bernie-g** [comment]
Hm this is really strange. Is your code on github? I'd need to take a look myself to debug.

**Comment by DavyJonesSocks** [comment]
Hey thanks for the quick response!

I asked a friend which knows a bit more about java development than I do. Today I found out that my forge snapshot was pretty old thus ran the buildscripts not properly. Because of this it didn't download the sources from your library. Therefore it couldn't find the class on runtime and that caused the error.

So the library works now. Thanks again!
