### ISSUE TITLE
Possible Bug: Texture broken inside models.

### ISSUE THREAD

**Issue by EnderTheCoder** [bernie-g/geckolib#353]
What it looks like in-game:
![2022-11-25_00 27 44](https://user-images.githubusercontent.com/47713889/203832453-987fa437-b697-47d7-8863-2611498dfe9b.png)
What it looks like in bb:
![missile_launch_facility](https://user-images.githubusercontent.com/47713889/203832482-1bfea90d-cf18-4178-b4a9-d04e74334acb.png)

**Comment by DerToaster98** [comment]
Used model: https://discord.com/channels/730912704776110121/730913831026688157/1045376906515726418

**Comment by AzureDoom** [comment]
Issue with UVs on your model, not a Geckolib issue.
