### ISSUE TITLE
Out of Bounds errors appearing in latest.log

### ISSUE THREAD

**Issue by Delfite** [bernie-g/geckolib#355]
**Game Environment**
Minecraft Version: 1.19.2
Mod Loader: Fabric
Mod Loader Version: 0.14.10
Mod Version: geckolib-fabric-1.19-3.1.37.jar

**Logs**
Errors start at Line 892: https://mclo.gs/vyr7xkb

**Description**
Not much I can say to really help here other than I downloaded the modpack "Dungeons by Daedelus [Fabric]" and added more mods to the pack. These errors didn't cause a crash or anything major that I noticed, though a warning did show up in chat saying that Geckolib has a bug that breaks animations while shaders from Iris or Optifine are active. The correlation was there for me to think that the overflow I saw in the logs had something to do with said warning (screenshot below) so I figured reporting it wouldn't hurt to do.
![2022-11-26_04 40 44](https://user-images.githubusercontent.com/23504262/204087372-949a1c5c-9759-4c90-8473-d59109ba9be0.png)

**Comment by AzureDoom** [comment]
Not our issue as everything works intended and it's Optifine/Iris changing things. Not our side to fix.
