### ISSUE TITLE
'Occultism' and 'Mana and Artifice'

### ISSUE THREAD

**Issue by Seagoddess** [bernie-g/geckolib#357]
There has been a correlation to rendering issues for both 'Mana and Artifice' constructs and 'Occultism' with the storage actuator. Why does the rendering of THIS mod keep crashing players? 

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 12/7/22, 9:13 AM
Description: Rendering Block Entity
^ This was from occultism, today

https://github.com/Mithion/Mana-And-Artifice/issues/575
^This link better explains the 'Mana and Artifice' one. 

Seriously, what is this mod doing??

**Comment by AzureDoom** [comment]
They likely need to update their mods.
