### ISSUE TITLE
[gekolib update breaking M&A] Questions and solutions to fix on other mods end

### ISSUE THREAD

**Issue by Shibva** [bernie-g/geckolib#359]
Hello, I'm aware that this has been an issue and I can only assume that many people have spam-reported this issue and any fix on this end is being refused for what I hopefully assume are valid reasons. Because of this, I have not seen anything at this time addressing why this might be the case; The issue does not exist when an older version is used, which begs to ask this question. While I'm not expecting nor asking for whatever was done to be reverted to fix this issue, I ask this as a way to possibly fix this issue on the other mods' end.

Q: why is the error occurring with entity constructs occurring, to begin with, and what sort of advice/info can be given to correct this issue on the dependent's end?

I'm hoping that addressing this and making it public info on the GitHub page may help those that are having this specific issue like with M&A and HOPEFULLY stop repetitively reporting this issue.

also, feel free to either make a new post or pin this post if you feel it necessary

**Comment by Shibva** [comment]
again, this is just asking what is likey going wrong and what/where to look for the developers to resolve this issue

**Comment by bernie-g** [comment]
I have literally no clue what issue you're talking about.

**Comment by Shibva** [comment]
refering to #324 #357 mostly, just curios on what change broke them and what could be done on the developers end (not your end) to fix these issues

**Comment by AzureDoom** [comment]
This on them to fix their mod that uses Geckolib. Not for us to fix
