### ISSUE TITLE
bad packaging

### ISSUE THREAD

**Issue by LlubNek** [bernie-g/geckolib#36]
forge-1.16.3-geckolib-3.0.0-beta.2.jar

This jar is poorly named, making it hard to find in an alphabetical list of jar files when you're looking for "geckolib".
It should be something like this:

geckolib-forge-1.16.3-3.0.0-beta.2.jar

Also, it has a pack.mcmeta file, but it's the default examplemod version.  This information shows up during game creation when choosing datapacks, and could also be helpful during debugging, if it were correctly set, but as is, it's pretty useless, and only adds to a player's confusion when things don't work.

And, you're missing the META-INF/mods.toml file, which provides mod id, version, and dependency information.  It's absence causes problems for other mods, such as Ars Nouveau ( https://github.com/baileyholl/Ars-Nouveau/issues/54#issue-735738948 ).

**Comment by bernie-g** [comment]
GeckoLib is no longer a mod in 3.0.0, therefore there is no mods.toml file. This is on purpose. Please read the wiki at https://geckolib.com.

The jar naming issue is fair enough, I'll look into renaming it.

**Comment by bernie-g** [comment]
Closing this as it's not an actual issue.
