### ISSUE TITLE
Incompartibility with new Forge, MCglTF and Ars Nouveau

### ISSUE THREAD

**Issue by uhloin** [bernie-g/geckolib#360]
Since Forge upgraded from 43.1.57 to 43.1.58 there new crash-like bug appeared. The game on start after loading screen 100% with Mojang logo, switches to empty red screen and freezes. Or sometimes just quit. There is no crush log but stderr logs have exception which refers to GeckoLib and Ars Nouveau. Also presence of MCglTF library make some influence but after I reported to owner of MCglTF he could reproduce the same exception in logs with only GeckoLib in mods folder.

I have stable reproduce of "red screen" with this configuration:
MC 1.19.2 (not 19.3)
forge-1.19.2-43.1.58-installer.jar or forge-1.19.2-43.2.0-installer.jar
geckolib-forge-1.19-3.1.38.jar
ars_nouveau-1.19.2-3.5.1.jar
curios-forge-1.19.2-5.1.1.0.jar
Patchouli-1.19.2-77.jar
TerraBlender-forge-1.19.2-2.0.1.130.jar
MCglTF-1.19.2-Forge-2.0.0.0.jar

**Comment by uhloin** [comment]
[stderr.log](https://github.com/bernie-g/geckolib/files/10199966/stderr.log)

**Comment by AzureDoom** [comment]
This is on Ars side, not ours. They are shadowing an old version of Geckolib.

**Comment by uhloin** [comment]
I can report to Ars but could you explain? What about old version if I use latest available version for 1.19.2 - geckolib-forge-1.19-3.1.38.jar? And what about Ars if somebody could reproduce exception with only geckolib im mods folder i.e. without Ars?

**Comment by AzureDoom** [comment]
The log clearly shows its used a shaded version that overrides your installation, look at the path it lists.

**Comment by uhloin** [comment]
Thank you for explanation, I will report to Ars.
