### ISSUE TITLE
AnimationFactory being deprecated 

### ISSUE THREAD

**Issue by OllyHolcombe** [bernie-g/geckolib#361]
Hey, I'm currently working on my own mod. I'm making a monster entity but for some reason every time I've tried to write this line of code:
`private final AnimationFactory factory = new AnimationFactory(this);`
I have had an error message come up,
`'AnimationFactory(software.bernie.geckolib3.core.IAnimatable)' is deprecated and marked for removal`
There is a red strike through the second AnimationFactory, I have absolutely no idea what to do or what I'm doing wrong. 
I am still learning java and have a basic understanding so if my issue is partly to do with that then I apologize. 

VERSION: 1.19:3.1.38
Link to my Git Repository: https://github.com/OllyHolcombe/MageCraft

**Comment by AzureDoom** [comment]
Look at the example entities or wiki.
