### ISSUE TITLE
Block animations do not work in latest geckolib Forge 1.16.5 (Including the ones provided by geckolib examples)

### ISSUE THREAD

**Issue by Enthusias720** [bernie-g/geckolib#363]
Here is a video showing the 2 example blocks not working:

https://user-images.githubusercontent.com/120320579/206910918-edfa6108-fe41-4c6e-a171-8ef4e85b3a5f.mp4

**Comment by Tslat** [comment]
Try other versions until you work out exactly which version of GeckoLib broke it, then let us know

**Comment by Enthusias720** [comment]
Just checked each version, they were:
Working on 'software.bernie.geckolib:geckolib-forge-1.16.5:3.0.100'
Broke on 'software.bernie.geckolib:geckolib-forge-1.16.5:3.0.101'
