### ISSUE TITLE
Latest Version (geckolib-forge-1.19-3.1.39.jar) Completely breaks GPU and crashes game (5700XT)

### ISSUE THREAD

**Issue by Art1xs** [bernie-g/geckolib#364]
I have no idea how or why it happened, but it did. The exit code and crash log are nowhere to be seen in my crash logs folder and I am unfortunately not willing to go through that again to find them. I tried resetting my graphics drivers and it did nothing to help. Once the game crashed, my entire screen went black and green repeatedly. (Graphical artifacts) and I could not even run videos on youtube of any sort. My Windows button showed nothing, not even the startup or shut-off options. I tried navigating my computer some more and had frequent periods where the screen would just shut entirely off and then flicker back on. I had to entirely turn off my pc and boot it back up. Even then, my pc did not boot properly, all I got was a black screen where my mouse was frozen in the middle. I had to turn off my PC again and safe-boot it and the issues are gone. My PC is back to normal. I used the previous version of the mod and tried to boot the game back up and have had no issues since. 

I know this sounds crazy, but I am certain that this was caused by the latest update of your mod. Probably a driver issue, considering that the 5700XT has had severe driver issues since day one. I am not sure if there is anything you can do about this, just letting you know.

**Comment by bernie-g** [comment]
This almost certainly has nothing to do with Geckolib. If you can consistently reproduce it with _**JUST**_ geckolib in your mods folder, let me know.

**Comment by AzureDoom** [comment]
Yeah, unless you can provide a log, I'm calling the biggest cap on this.

**Comment by Art1xs** [comment]
> Yeah, unless you can provide a log, I'm calling the biggest cap on this.

As I said, I am not interested in reproducing this and potentially causing damage to my computer. It is most likely a mod conflict with your mod causing this, not the version alone. 

If you read at the end, I said, "I know this sounds crazy, but I am certain that this was caused by the latest update of your mod. Probably a driver issue, considering that the 5700XT has had severe driver issues since day one. I am not sure if there is anything you can do about this, just letting you know."

But hey, you must believe that I'm lying for some reason.

**Comment by Art1xs** [comment]
> This almost certainly has nothing to do with Geckolib. If you can consistently reproduce it with _**JUST**_ geckolib in your mods folder, let me know.

Just tested it. I figured I was wrong about it having to do with my hardware, which, you're right about. The mod alone has no issue with my GPU. This means it's probably a conflict with another mod. 

Still, it's some pretty weird stuff that happened for just a mod conflict alone...

Sigh... I guess I'll give it another shot.

**Comment by Art1xs** [comment]
Damn.. It seems I have much to be concerned about. I tried to reproduce the situation, and nothing happened this time. Either I have a virus (which I scanned already, and came up clean.), or my GPU just decided to shit itself. 

I apologize for bringing this matter to you, it is unrelated, you are correct.
