### ISSUE TITLE
quilt.mod.json contributors in the wrong format

### ISSUE THREAD

**Issue by Cypher121** [bernie-g/geckolib#365]
The format for [these](https://github.com/bernie-g/geckolib/blob/main/Quilt/src/main/resources/quilt.mod.json#L11) is supposed to be `"name": "role"`, e.g. `"Gecko": "Owner"`. The current format makes it show up wrong in mod lists like launcher ones.

"I made this"
![image](https://user-images.githubusercontent.com/8020624/208242926-ec5925a3-a498-4606-bfed-49897dede20b.png)

**Comment by AzureDoom** [comment]
Fixes for 1.18.2 and 1.19.2 pushed now. 1.19.3 will come later as a few other issues are being looked into.
