### ISSUE TITLE
Crash on Startup, 1.19.3 Quilt

### ISSUE THREAD

**Issue by Minehero367** [bernie-g/geckolib#367]
Game crashes on Startup, no other mods loaded besides Quilt Api.

Link to full log: [Link](https://mclo.gs/Bp3TRtz)

GeckoLib Version: 3.1.40
Quilt Version: 0.18.1-beta.25
Quilt API Version: 5.0.0-alpha.6 + 0.69.1

**Comment by AzureDoom** [comment]
You can use 3.1 on 1.19.3

**Comment by Minehero367** [comment]
My apologies, issue is with the Prism Launcher, labels 3.1 as 1.19.3 compatible and lists it higher than 4.
