### ISSUE TITLE
Animation Priorities?

### ISSUE THREAD

**Issue by Yaumama** [bernie-g/geckolib#370]
Hello, I am making a mod and I have an attack, idle and walk animations. Whenever the attack animation plays however, only the parts that are not affected by the idle and walk animations move, can I assign animation priorities for the attack animation? Thanks in advance for the help.

**Comment by AzureDoom** [comment]
Animations on other controllers can not use the same bones

**Comment by Tslat** [comment]
I should correct this

In GeckoLib4 I made controller order deterministic.

This means that each controller will run in the order it was registered, which can be utilised to try to sort out conflicting bones in a way similar to what you're asking - in theory.

**Comment by Yaumama** [comment]
Is there any way to get this working? I tried putting all of the animations on one controller but it just didn't play, I am fairly new to modding so please bare with me here and this is my first attempt at trying to get geckolib working.

**Comment by Tslat** [comment]
Join the discord and ask in one of the help channels if you want help.
Github is not the place for community support

**Comment by Yaumama** [comment]
Ok, thanks!
