### ISSUE TITLE
Can't assign separate texture to object

### ISSUE THREAD

**Issue by DaveDee** [bernie-g/geckolib#378]
Is there a reason I can't assign a specific texture to specific cube?
I want to add an animated texture (though it's not only about animated textures) but this option doesn't work in GL format
![bbdd](https://user-images.githubusercontent.com/1294788/212758315-ad9b7e7e-8fc6-4daa-8966-ef9820e9fff5.png)

**Comment by AzureDoom** [comment]
Because this is a limitation of the bedrock format. There is an extended render for entities that has support for per bone textures via code but it's resource heavy which is why it's not a built in feature.
