### ISSUE TITLE
Easings cause animations to not play with new versions of GeckoLib 1.16.5

### ISSUE THREAD

**Issue by NerdyPuzzle** [bernie-g/geckolib#381]
I tested 3.0.100+, and animations will not play if they have easings. However, after downgrading to 3.0.96, the animations will play as they should. (Only seems to happen on 1.16.5)

Provided is the model I used to test this.
[geo_anim_texture.zip](https://github.com/bernie-g/geckolib/files/10472331/geo_anim_texture.zip)

**Comment by AzureDoom** [comment]
1.16.5 is unsupported anymore.
