### ISSUE TITLE
[1.19.2][Forge] Crash on entering a world (probably related to #364)

### ISSUE THREAD

**Issue by ParaMotor** [bernie-g/geckolib#382]
Here is what happened so far:

First I crashed when I wanted to turn of my shader (Oculus) a few days ago without crash log but with a complete Graphics Driver Crash (AMD Radeon RX 5700XT - so thats why I think it is related with #364 ). After that, the Mod Naturalist (V.2.1.1)(which uses geckolib) got corrupted and I couldn't load any world. After deleting and re-downloading the mod (Naturalist), it worked again until I again disabled my shader again after re-enabling and this time I got a crash without a full Graphics Driver Crash but again Naturalist got corrupted. The third time was today without doing something with shaders, they were disabled from the start of the game - but today a reinstall of all Mods didn't help. I keep crashing when I want to load a world. 

Removing all Mods besides Geckolib and the Mods which uses it still leads to crashes. With only Geckolib and Vinery (which worked fine before) or Naturalist, it keeps crashing. Only Geckolib works fine. 

I already tried to switch Java Versions (tried out openjdk 17, Oracle Java 17/19) didn't help. Upgrading/Downgrading Graphics Driver didn't help. On my friends PCs (GTX 1070 MAX-Q, GTX 1070, GTX 2070 and GTX 3080) the same Mods work just fine.

The last time I got a small part of a crash-report, I hope that helps (I had to type it down manually from GDLauncher because the crash-report file wasn't created again):

https://pastebin.com/skvTPJ8Z

**Comment by AzureDoom** [comment]
Then it's likely an issue with Vinery or Naturalist, not a  Geckolib issue.
