### ISSUE TITLE
shader's break animations.

### ISSUE THREAD

**Issue by netcore10** [bernie-g/geckolib#387]
Is there any kind of workaround for this, or is shaders just incompatible with any mod using geckolib? Most mobs using this, tend to just become frozen when using shaders.

**Comment by AzureDoom** [comment]
This is an issue with Iris/Optifine on how they are messing with the game time which is required for the ticks we use for transitions.

**Comment by coderbot16** [comment]
I am not aware of how Iris messes with the game time at all? Could you please provide more detail?

**Comment by coderbot16** [comment]
The only thing that I can think of that would be related would be the fact that Iris has to render things like entities twice if the shader pack has shadows... but if GeckoLib breaks with that, the issue would have to be fixed in GeckoLib.

**Comment by TheFurryDevil** [comment]
That feeling when you find a related issue and it's closed, but not fixed... sadly shaderpacks are more important than new creatures, and Naturalist is the only reason my modpack has GeckoLib.

**Comment by Tslat** [comment]
> That feeling when you find a related issue and it's closed, but not fixed... sadly shaderpacks are more important than new creatures, and Naturalist is the only reason my modpack has GeckoLib.

What?

**Comment by netcore10** [comment]
> That feeling when you find a related issue and it's closed, but not fixed... sadly shaderpacks are more important than new creatures, and Naturalist is the only reason my modpack has GeckoLib.

it's fixed on 1.19.4 gecholib.

**Comment by TheFurryDevil** [comment]
Well, I'm on 1.19.2 and it works when I disable shaders in Iris, and breaks again when enabled again.
Can't really move to .4, I hope there will be an update for the .2 version eventually

**Comment by netcore10** [comment]
> Well, I'm on 1.19.2 and it works when I disable shaders in Iris, and breaks again when enabled again. Can't really move to .4, I hope there will be an update for the .2 version eventually

most mods don't backport, especially api's, it's probably only fixed to .4 onwards
