### ISSUE TITLE
AnimationEvent#isMoving() is flipped [1.18.2-fabric]

### ISSUE THREAD

**Issue by StockiesLad** [bernie-g/geckolib#390]
![image](https://user-images.githubusercontent.com/60066663/218924010-4a555cd3-ef73-43a9-a3ba-f354714bb374.png)
I had to manually change this in creeper overhaul because it was getting annoying. Could this be fixed or atleast changed to "isNotMoving".

**Comment by FluffyBumblebees** [comment]
Oops forgot to mention im using 

geckolib-fabric-1.18-3.0.80

**Comment by Cr1pter** [comment]
Try removing the exclamation mark in front of event.isMoving(), it flips the value around, so true becomes false

**Comment by AzureDoom** [comment]
Is working correctly with my mods that use isMoving for 1.18.2. Your speed threshold is likely too low.
