### ISSUE TITLE
crash client 1.19.2 fabric

### ISSUE THREAD

**Issue by MrJorman** [bernie-g/geckolib#393]
[2023-02-21-3.log](https://github.com/bernie-g/geckolib/files/10787842/2023-02-21-3.log)
[crash-2023-02-21_00.19.18-client.txt](https://github.com/bernie-g/geckolib/files/10787843/crash-2023-02-21_00.19.18-client.txt)

**Comment by AzureDoom** [comment]
Not a Geckolib bug
