### ISSUE TITLE
⚠️𝗖𝗥𝗔𝗦𝗛⚠️𝘎𝘦𝘤𝘬𝘰𝘓𝘪𝘣 𝘤𝘢𝘶𝘴𝘦𝘴 𝘮𝘺 𝘨𝘢𝘮𝘦 𝘵𝘰 𝘤𝘳𝘢𝘴𝘩!

### ISSUE THREAD

**Issue by User4716** [bernie-g/geckolib#394]
**GeckoLib** mod (geckolib-forge-1.19-3.1.39.jar) crashes my game.

**I use Forge 43.2.4 - 1.19.2**

When I load up my game, there is a total of 13 errors

![2023-02-21_12 52 45](https://user-images.githubusercontent.com/97033682/220325743-8cfab0f9-1c9c-49ac-896f-a0e779d2409b.png)

![2023-02-21_12 54 53](https://user-images.githubusercontent.com/97033682/220325945-0ff102fb-bc47-4f3f-8ac6-bb5ca25d743a.png)

**I dont even know if GeckoLib is really the mod that crashes my game, but it was associated with the crash report so I came here to see if someone would be kind enough to help me!**

And i'm just trying to figure out how to fix each error one by one. 
(This is the second issue I posted today)

**Here is the latest.log**
[latest.log](https://github.com/MehVahdJukaar/Supplementaries/files/10792802/latest.log)
**And crash.log**
[crash-2023-02-21_12.30.33-fml.txt](https://github.com/MehVahdJukaar/Supplementaries/files/10792845/crash-2023-02-21_12.30.33-fml.txt)

**Below is the error message that this mod gave me. But please check the log files above to get full logs.**

> -- MOD geckolib3 --
> Details:
> Caused by 0: java.lang.reflect.InvocationTargetException
> at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
> at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
> at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
> at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
> at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
> at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.4.jar%23491!/:?] {}
> at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.4.jar%23490!/:?] {}
> at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
> at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
> at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
> at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
> at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:mixin,re:computing_frames}
> at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:mixin,re:computing_frames}
> at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}
> 
> Mod File: /C:/Users/PRIVATE/curseforge/minecraft/Instances/1.19.2 Adventure/mods/geckolib-forge-1.19-3.1.39.jar
> Failure message: GeckoLib (geckolib3) has failed to load correctly
> java.lang.reflect.InvocationTargetException: null
> Mod Version: 3.1.39
> Mod Issue URL: https://github.com/bernie-g/geckolib/issues
> Exception message: java.lang.NoClassDefFoundError: Could not initialize class net.minecraftforge.network.NetworkDirection
> 
> Stacktrace:
> at software.bernie.geckolib3.network.messages.SyncAnimationMsg.register(SyncAnimationMsg.java:26) ~[geckolib-forge-1.19-3.1.39.jar%23384!/:3.1.39] {re:classloading}
> at software.bernie.geckolib3.network.GeckoLibNetwork.initialize(GeckoLibNetwork.java:42) ~[geckolib-forge-1.19-3.1.39.jar%23384!/:3.1.39] {re:classloading}
> at software.bernie.geckolib3.GeckoLib.initialize(GeckoLib.java:38) ~[geckolib-forge-1.19-3.1.39.jar%23384!/:3.1.39] {re:classloading}
> at software.bernie.example.GeckoLibMod.<init>(GeckoLibMod.java:43) ~[geckolib-forge-1.19-3.1.39.jar%23384!/:3.1.39] {re:classloading}
> at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
> at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
> at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
> at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
> at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
> at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:68) ~[javafmllanguage-1.19.2-43.2.4.jar%23491!/:?] {}
> at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.2.4.jar%23490!/:?] {}
> at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
> at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
> at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
> at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
> at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:mixin,re:computing_frames}
> at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:mixin,re:computing_frames}
> at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}

**Please can someone help me with this, I am not sure how to fix this..**

**Comment by AzureDoom** [comment]
Whatever mod is using Geckolib in your modpack is not updated for the latest version. Not an issue with Geckolib.
