### ISSUE TITLE
Entity animations are not working for forge 1.19.3

### ISSUE THREAD

**Issue by superfastscyphozoa** [bernie-g/geckolib#399]
Despite properly coding my custom entity class (I think lol), my custom entity simply does not play any animations?
I am at a complete loss, if anyone could help, I'd appreciate it.

Here is my entity class:
https://pastebin.com/XBwadaXS

**Comment by AzureDoom** [comment]
Because you are overriding the tick and setting it to 0.

**Comment by allusive-dev** [comment]
What should the tick be set to for it to work?
I tried 5 and 20 neither fix the animations not working. I have very similar code to the OP.

**Comment by Tslat** [comment]
Don't override it at all?

**Comment by allusive-dev** [comment]
I also tried not overriding it, Still dosen't work.
Here is my code:
https://pastebin.com/uRBNkSy4

**Comment by Tslat** [comment]
Out of curiosity
What happens if you override `aiStep` and put in `updateSwingTime`
