### ISSUE TITLE
1.16 Fabric version

### ISSUE THREAD

**Issue by CammiePone** [bernie-g/geckolib#4]
Hello, so I just got done porting the 1.15 Fabric branch to 1.16, and was wondering if you would be able to make a fabric-1.16 branch I can make a PR for.

A few friends and I were in need of an animation library for Fabric 1.16, and when we found out about GeckoLib we were excited, especially since it's actively developed still, but since there wasn't already a 1.16 Fabric port, but there was a 1.15 Fabric port, I decided to go ahead and do it myself. Animations for the example entities included still work, so I'm assuming I did everything right.

Thank you so much for making this btw, this is a life saver.

EDIT: just so you can see it working without needing to set up a workspace for it (probably should've included the other two in the recording come to think of it):
[https://youtu.be/jIgfqSyXpxE](https://youtu.be/jIgfqSyXpxE)

**Comment by CammiePone** [comment]
Gonna go ahead and close this, since 1.16 is on its way and there's gonna be new features I didn't know about. I'm extremely excited to see how this goes :3

**Comment by fadookie** [comment]
Thanks for the effort!

**Comment by fadookie** [comment]
We just started a discord for the project at https://discord.gg/MNQcKxB - please drop by!
