### ISSUE TITLE
Log errors related to java(?)

### ISSUE THREAD

**Issue by Puffadillo** [bernie-g/geckolib#402]
Minecraft `1.19.2`
Fabric `0.14.17`
Fabric API `0.75.1`
GeckoLib `3.1.40`
Java `0.17.6 by Oracle Corporation`

I've noticed my game log having large quantities of red errors caused by GeckoLib, possibly related to Java? The game seems to run fine, but I am still slightly concerned. Tested in a fresh instance with only the above mods and no custom JVM arguments: https://gist.github.com/Puffadillo/f337cdae474ba9947fb0f55cc5a415c1

I don't know anything about Java; I just install and use whatever the recommended version is, so please let me know if this is a problem on my end, but GeckoLib is the only mod in my large pack throwing these errors.

**Comment by MelrikBirchJr** [comment]
its happening for me aswell but for 1.19.3 geckolib-fabric-1.19-3.1.40

**Comment by AzureDoom** [comment]
> its happening for me aswell but for 1.19.3 geckolib-fabric-1.19-3.1.40

That is not a valid 1.19.3 build. 



> Minecraft `1.19.2` Fabric `0.14.17` Fabric API `0.75.1` GeckoLib `3.1.40` Java `0.17.6 by Oracle Corporation`
> 
> I've noticed my game log having large quantities of red errors caused by GeckoLib, possibly related to Java? The game seems to run fine, but I am still slightly concerned. Tested in a fresh instance with only the above mods and no custom JVM arguments: https://gist.github.com/Puffadillo/f337cdae474ba9947fb0f55cc5a415c1
> 
> I don't know anything about Java; I just install and use whatever the recommended version is, so please let me know if this is a problem on my end, but GeckoLib is the only mod in my large pack throwing these errors.

the `[23:36:32] [Worker-Main-14/INFO]: [STDERR]: java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 0` is a known issue and safe to ignore as it's just a log file for a Geckolib animation file.
