### ISSUE TITLE
Infinite Loading into Main Menu

### ISSUE THREAD

**Issue by MelrikBirchJr** [bernie-g/geckolib#403]
when ever geckolib for 1.19.3 is in my mods folder it causes a infinite load and its geckolib-fabric-1.19-3.1.40 causing it idk why and how but it just does it and idk what to do i cannot load without it for mods.. please help or find a fix

**Comment by AzureDoom** [comment]
That version of Geckolib does not work with 1.19.3, 1.19.2 mods don't work with 1.19.3
