### ISSUE TITLE
Mods that Utilize v4

### ISSUE THREAD

**Issue by ItsLushotology** [bernie-g/geckolib#409]
Hello There!:)

Since the Wiki is still in progress for v4, I was wondering if anyone knew of a few mc 1.19.3 mods that use GeckoLib v4, so I can try to correct errors comparatively. More specifically, I'm looking for any mods that have new animal or pet entities.

Thank you in advance!:)

**Comment by AzureDoom** [comment]
The best place will always be the example entities, outside of this, you would need look at the mods that require Geckolib and are 1.19.3+.

**Comment by ItsLushotology** [comment]
Thank you so much for your reply! I appreciate all your effort on this project.
The examples are great, however I am unable to locate where the ExtendedRendererEntity example was moved to. Are you able to point me in the right direction?

> The best place will always be the example entities, outside of this, you would need look at the mods that require Geckolib and are 1.19.3+.
