### ISSUE TITLE
"Missing GeckoLib3"

### ISSUE THREAD

**Issue by ItsLushotology** [bernie-g/geckolib#411]
Apologies, I'm a newbie, so another question. Upon running a test client run in IntelliJ, I am faced with the following error:

**Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install geckolib3, version 3.1.0 or later.
Unmet dependency listing:
	 - Mod requires version 3.1.0 or later of geckolib3, which is missing!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:192)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)**

I also attempted to compile the mod and run it through my regular minecraft launcher, which has fabric api and geckolib installed and am faced with the same error.

My gradle.properties are:
![1](https://user-images.githubusercontent.com/128506807/227053525-dac18f9c-a9bf-4be2-aecf-caca54069e64.jpg)

And my gradle.build repository is:
repositories {
	maven { url 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/' }

And the dependencies are:
![image](https://user-images.githubusercontent.com/128506807/227054492-ec90b487-0c4d-474b-8f84-2b1abe1ac875.png)

Loom is 1.1 if that helps.
 THANK YOU!!!!

**Comment by ItsLushotology** [comment]
![image](https://user-images.githubusercontent.com/128506807/227692270-85ae6008-7db7-4224-9210-ffbe965b520b.png)
 
Additional info

**Comment by AzureDoom** [comment]
make sure to update your fabric.mod.json for the namespace of just geckolib

**Comment by ItsLushotology** [comment]
> make sure to update your fabric.mod.json for the namespace of just geckolib

Thank you, I fuckin love you
