### ISSUE TITLE
Animated Ranged Items are not possible and this is bad because,

### ISSUE THREAD

**Issue by VKHSD** [bernie-g/geckolib#412]
If one were to make an animated ranged item that is unique as in, the tick @override method is modified, a tick update within the projectile will never be called if spawned from the Animated Item. This is why a few others and I request the development of Animated Ranged Items. 

Unless there is a very simple way that went over my head, I believe there is no correct way to do this, it would still be very appreciated and helpful if this was developed.

**Comment by bernie-g** [comment]
Please show your code (specifically include the class where you overrode the tick method).
