### ISSUE TITLE
Wiki has been wrong for 4.0 on installation for forge

### ISSUE THREAD

**Issue by AquaticTyphoon** [bernie-g/geckolib#413]
//NOTE THIS IS FOR FORGE!
//Install at the repo / dependencies at the bottom of your build.gradel like so and check for the latest update as it isn't stated in the //wiki.

//In build.gradel

repositories {
    +maven { url 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/' }
}

// NOTE YOUR VERSION MAY DIFFER FOR WHAT YOU MOD
dependencies {
    +minecraft 'net.minecraftforge:forge:1.19.4-45.0.22'
    +implementation fg.deobf('software.bernie.geckolib:geckolib-forge-1.19.4:4.1.2')
}

//And the wiki fails to state you need this in with where items, blocks, and entities are registered.

//Under ModItems.register(modEventBus);
+GeckoLib.initialize();

**Comment by AzureDoom** [comment]
That isn't needed anymore.
