### ISSUE TITLE
Entity .geo.json not found although file is in correct geo folder. 

### ISSUE THREAD

**Issue by JonahLocken001** [bernie-g/geckolib#415]
When I am loading into my world, I get the following error: 
software.bernie.geckolib3.geo.exception.GeckoLibException: thorium:geo/gresk.geo.json: Could not find model. If you are getting this with a built mod, please just restart your game. 

My folder structure looks as follows:

![image](https://user-images.githubusercontent.com/128866437/227660214-0d9f558a-d96c-4ac9-9eff-2a8d2ab2536a.png)

and my procedure follows the guidelines as per the geckolib guide posted on the mcreator forums.

**Comment by AzureDoom** [comment]
MCraptor isn't supported.
