### ISSUE TITLE
game crashes after playing kind of animation that has an if is check

### ISSUE THREAD

**Issue by Alpha1424828** [bernie-g/geckolib#418]
i dont know whats wrong i did this but if i spawn my entity it crashes
![Screenshot 2023-04-03 130410](https://user-images.githubusercontent.com/128643517/229491745-80308564-9fbc-4ab3-9cfb-20c1061df6ce.png)

**Comment by Alpha1424828** [comment]
it also crashes with this 
![image](https://user-images.githubusercontent.com/128643517/229727004-3789043c-da5a-4731-af97-9f84e345fbcb.png)

**Comment by bernie-g** [comment]
We don't support MCreator. Please ask the authors of the plugin.
