### ISSUE TITLE
Class not found expectation while using Java 14 

### ISSUE THREAD

**Issue by UnRealDinnerbone** [bernie-g/geckolib#42]
The console gets spammed with class not found exceptions when trying to use java 14

https://paste.ee/p/IpTD4
Minecraft: 1.16.4
Forge: 35.1.3
Mod: forge-1.16.4-geckolib-3.0.0-beta.10

**Comment by bernie-g** [comment]
Show your build.gradle. Is this in production or dev?

**Comment by UnRealDinnerbone** [comment]
This is the production running a 1.16 pack

**Comment by bernie-g** [comment]
@UnRealDinnerbone I need to see your build.gradle.

**Comment by UnRealDinnerbone** [comment]
I dont have a build.gradle this is running as a built jar in a 1.16.4 modpack
