### ISSUE TITLE
Geckolib "Invalid Player Data"

### ISSUE THREAD

**Issue by cryflow3r** [bernie-g/geckolib#421]
Hello, I'm encountering an issue, it's related to origins mod and its addons. My game says Haema needs geckolib, but as soon as I add it to the mods folder the game takes horrendously long time to load, and when I want to enter single player world it says "invalid player data" and it kicks me to server list. This problem only occurs when I have geckolib in in my mods. I'm also adding my mod list here. Can someone help me with that?
![error](https://user-images.githubusercontent.com/129997193/230199672-cc91dab7-d92b-4c29-8122-26d7fab7039a.png)

**Comment by Tslat** [comment]
Provide your latest.log file
