### ISSUE TITLE
[1.16.5] Crashes with MCDoom and Rigoranthus Emortis Reborn mod.

### ISSUE THREAD

**Issue by BigBoiSub** [bernie-g/geckolib#422]
I’ve been having this issue with client crashes for a while now, but I’m unsure what the root of the issue is. 

It seems that some mobs particularly from the mods MCDoom and Rigoranthus Emortis Reborn consistently cause client crashing to the point I’ve had to disable some of the entities from both of these mods. That being said, I’m currently unsure if this is the individual mod’s issues or if this is perhaps a GeckoLib issue. I have gone to MCDoom in the past about other issues, but all I’ve received back is that they no long support 1.16.5.

Rigor crash:
[rigor_crash.txt](https://github.com/bernie-g/geckolib/files/11172112/rigor_crash.txt)

MCDoom crash:
[doom_crash.txt](https://github.com/bernie-g/geckolib/files/11172114/doom_crash.txt)

**Comment by Tslat** [comment]
Make sure your geckolib is fully up to date (you're currently a few versions outdated)
If the crash continues, report it to the mod dev, as it is the result of them not updating to the changes in newer versions of geckolib
