### ISSUE TITLE
Animated Blocks Causing Decreased Mining Speed Issue in Geckolib3

### ISSUE THREAD

**Issue by VKHSD** [bernie-g/geckolib#423]
Hello,

I am experiencing an issue with the mining speed of my animated blocks in my mod. I am using the GeckoLib library to create the animations, and I have noticed that when I mine the blocks, the mining speed is significantly slower than it should be.

I have narrowed down the issue to the use of the GeckoLib library, as when I remove the animations and use regular blocks, the mining speed is normal.

I would appreciate it if someone from the GeckoLib development team could provide some insight into why this might be happening and if there is a solution.

Thank you.

**Comment by Tslat** [comment]
Closing due to usage of the Mcreator plugin
We cannot assist with mcreator usage
