### ISSUE TITLE
Minecraft is saying Geckolib3 is not installed

### ISSUE THREAD

**Issue by BalloonSC** [bernie-g/geckolib#424]
I have geckolib 1.19.4-4.1.3 in my forge mod folder, but whenever I try to use a mod that requires geckolib, Minecraft says:

 Mod [Whatever mod it is] requires geckolib3 3.1.9 or above
Currently, geckolib3 is not installed

I even tried using an older version of geckolib but that would just crash. I am using forge 1.19.4

**Comment by Tslat** [comment]
Geckolib3 is for Minecraft 1.19.2 and below.
Either you have a mod with the wrong version in your list, or a mod has done their mod info file wrong

This has nothing to do with us

**Comment by Helpfilguy** [comment]
Also if you go into the mod, and then press download, you can choose the version, and the mod launcher, and then it will be the right one.
