### ISSUE TITLE
Where's GeckoLib3?

### ISSUE THREAD

**Issue by N1ceV0id** [bernie-g/geckolib#428]
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install geckolib3, version 3.1.0 or later.
Unmet dependency listing:
	 - Mod 'Rat's Mischief' (ratsmischief) 1.4.0 requires version 3.1.0 or later of geckolib3, which is missing!

**Comment by Tslat** [comment]
just grab the latest version of geckolib off curseforge for your minecraft version
