### ISSUE TITLE
Version 4.1.3 unusable as a dependency in mods

### ISSUE THREAD

**Issue by NeoSaysMeow** [bernie-g/geckolib#429]
![image](https://user-images.githubusercontent.com/113204549/232888015-f0585657-6353-4a04-864e-09ed4230665b.png)
After updating my mod, it turns out that GeckoLib absolutely breaks it. Removing GeckoLib makes it work again. Everything is rectangles and the game crashes when loading into a world.

**Comment by Tslat** [comment]
Provide the crash report
