### ISSUE TITLE
Crashing / Conflict with another mod "Headed"

### ISSUE THREAD

**Issue by AmibeSkyfy16** [bernie-g/geckolib#432]
If the two mod are present (Headed amd GeckoLib), a crash will occur if you try to type "bee" in the creative gui menu
I report the issue here: https://github.com/Pedro270707/headed/issues/4

Fabric 1.19.4 - 0.14.9
Latest version of both  (Headed amd GeckoLib)

**Comment by Tslat** [comment]
Provide an error with just those two mods present and we'll have a look

As it stands, anything could be coming in the way
