### ISSUE TITLE
[1.19.2-3.1.40] Stacktrace at ResourceListener.java:9 | reflect.InvocationTargetException: null | NoSuchMethodError: net.minecraft.client.Minecraft.m_91087_()

### ISSUE THREAD

**Issue by DancerVlt69** [bernie-g/geckolib#437]
If I will start MC 1.19.2 / Forge 43.2.11/ GeckoLib3 3.1.40 in/via IntelliJ (2022.3.3) I'll got this crash 
With/in Fabric all works fine. 

![image](https://github.com/bernie-g/geckolib/assets/49952690/7dc114cd-cd57-4d29-9cfc-31544c31101e)

[crash-2023-05-29_20.25.42-fml.txt](https://github.com/bernie-g/geckolib/files/11593593/crash-2023-05-29_20.25.42-fml.txt)

**Comment by Tslat** [comment]
java.lang.NoSuchMethodError: 'net.minecraft.client.Minecraft net.minecraft.client.Minecraft.m_91087_()'

Why does Minecraft.instance() not exist? lol

**Comment by DancerVlt69** [comment]
Solved
Thanks for the non-directly hint @Tslat 
I've added the *implementation* of the dependencies by myself aaaand...  forgot the ***fg.deobf***
