### ISSUE TITLE
[1.19.4-4.2] Forge - build.gradle dependency issue

### ISSUE THREAD

**Issue by 77wisher77** [bernie-g/geckolib#441]
Ii followed the documentation for installing 4.0+ geckolib and could not resolve this issue; I'm getting a bunch of errors along the lines of 

- `Exception in thread "main" java.lang.module.ResolutionException: Modules org.jetbrains.annotations and geckolib export package org.intellij.lang.annotations to module xaeronbtslotids`
- `Exception in thread "main" java.lang.module.ResolutionException: Modules org.jetbrains.annotations and geckolib export package org.intellij.lang.annotations to module minecraft`

The precise conflicitng modules change each time i run `runClient`, I suspect this has something to do with the mixins? They aren't something i've dealt with before

Here's links my gradle layout, i have a rootproject with 2 subprojects, my API and my main mod files. I have skipped linking the API since it doesnt touch geckolib

#### Root Project

[build.gradle](https://gitlab.com/Wisher/Onion-Adventures/-/blob/95fdf32227be41e0fb67675de2afab85a609c6fb/build.gradle)

[gradle.properties](https://gitlab.com/Wisher/Onion-Adventures/-/blob/95fdf32227be41e0fb67675de2afab85a609c6fb/gradle.properties)

[settings.gradle](https://gitlab.com/Wisher/Onion-Adventures/-/blob/95fdf32227be41e0fb67675de2afab85a609c6fb/settings.gradle)

#### Sub-Project Core

[build.gradle](https://gitlab.com/Wisher/Onion-Adventures/-/blob/95fdf32227be41e0fb67675de2afab85a609c6fb/core/build.gradle)

**Comment by Tslat** [comment]
You shouldn't be using cursemaven for dev work
Use the actual maven - follow the instructions on the wiki for setting up your dev space
