### ISSUE TITLE
[1.20.1] crashing during gameplay

### ISSUE THREAD

**Issue by MrKashew** [bernie-g/geckolib#446]
[crash-2023-06-20_20.22.19-client.txt](https://github.com/bernie-g/geckolib/files/11811914/crash-2023-06-20_20.22.19-client.txt)

**Comment by MrKashew** [comment]
reproduced this crash again with physics mod pro ocean, diving into the water

**Comment by Tslat** [comment]
Need to work out which mod is causing it

**Comment by whatthedrunk** [comment]
Getting the same crash and it might be  Iron's Spells 'n Spellbooks

**Comment by Tslat** [comment]
It's caused by Entity Culling mod I think
you can disable its entity culling thing in config I believe which should fix it

You can also consider reporting it to them as a bug

**Comment by MrKashew** [comment]
will test both creeper overhaul and entity culling as I have both in my current pack

**Comment by Vernkidd** [comment]
Hello my friends, I get the same exact crash log and removing creeper overhaul from my mods folder stops the crashing

**Comment by MrKashew** [comment]
looks like its been patched by linked issue, closing this issue
