### ISSUE TITLE
[1.20.1] Lighting is baked incorrectly for rotated item models

### ISSUE THREAD

**Issue by baileyholl** [bernie-g/geckolib#448]
Sword model from 1.19, geckolib 3 with correct lighting:
![image](https://github.com/bernie-g/geckolib/assets/13970203/3f36bc3a-6945-40eb-8029-17eeaf38dcbb)

1.20.1/geckolib 4
Item models with incorrect lighting. The book with rotated (2nd), book without rotations and correct lighting (third) sword with incorrect lighting, unchanged from 1.19/g3 (4th)

![image](https://github.com/bernie-g/geckolib/assets/13970203/33838ce3-0d73-455d-9fd1-5e66c268aba5)

Item model file: https://github.com/baileyholl/Ars-Nouveau/blob/1.20/src/main/resources/assets/ars_nouveau/models/item/enchanters_sword.json

Sword geo model: 
https://github.com/baileyholl/Ars-Nouveau/blob/1.20/src/main/resources/assets/ars_nouveau/geo/sword.geo.json

Reproduce with any geckolib geo item:
Make item model without rotations
Make item with dramatic rotations for GUI
Expected: should render with brightness from the same angle for both items like in 1.19

Differing rendertypes don't matter, the only reproduction is to take the same item model and remove rotations, and it will render with correct vanilla lighting again.

**Comment by Tslat** [comment]
I've added a toggle to use the alternate entity gui lighting model in GeoItemRenderer in the next update

MC keeps changing their lighting handling which makes stuff like this hard to rectify without it breaking someone else's thing
