### ISSUE TITLE
[1.20.1] Block entities have weird/inconsistent shadows

### ISSUE THREAD

**Issue by baileyholl** [bernie-g/geckolib#449]
From 1.19 geckolib 3 using EntityCutout rendertype:
![image](https://github.com/bernie-g/geckolib/assets/13970203/049276f5-4d8b-44a8-acb6-c43be976f0bc)

1.20 geckolib 4 using EntityCutout rendertype:
![image](https://github.com/bernie-g/geckolib/assets/13970203/b8d3b81c-81c8-425f-8296-0e012d7d3845)

1.20 but from below, the lighting actually does look correct. 
![image](https://github.com/bernie-g/geckolib/assets/13970203/e9475bcd-ecb1-4448-843e-0ebb5af5d94e)

Tried various render types, nothing is unchagned.

It looks like the lighting is baked in from the wrong rotation? As if it were upside down? 

possibly related to #448?

**Comment by baileyholl** [comment]
Looks like this also applies to models held in the hand, for items as well (including the latest fix for GUI lighting

![image](https://github.com/bernie-g/geckolib/assets/13970203/b29af795-df2d-46b7-a4b6-e99b11df4e52)

**Comment by Tslat** [comment]
Very interesting

Can you join the discord so it's easier to communicate lol

**Comment by Tslat** [comment]
@baileyholl You'll be happy to know I finally fixed this lol
