### ISSUE TITLE
Bug: weird helmet texture glitch

### ISSUE THREAD

**Issue by MJRamon** [bernie-g/geckolib#457]
minecraft_version=1.19.2
yarn_mappings=1.19.2+build.28
loader_version=0.14.12

geckolib_version=1.19:3.1.40

WHen equipped with helmet, frontal part of mob face is replaced with part of helmet texture (overlay stays as it should be).
Same bug occures with example entity `geckolib3:extendedrendererentity`.

If it's too late to update 1.19.2, I'd like to know how can I fix it.

![2023-07-14_03 45 21](https://github.com/bernie-g/geckolib/assets/2642227/51739cfb-aee7-4640-a86d-f1a44e8b12c1)
![2023-07-14_03 45 27](https://github.com/bernie-g/geckolib/assets/2642227/a780e146-e89f-462c-9b75-5056ba909b4e)
![2023-07-14_03 45 03](https://github.com/bernie-g/geckolib/assets/2642227/b51c75eb-1825-4cdd-a813-1afcddc59702)
![2023-07-14_03 44 52](https://github.com/bernie-g/geckolib/assets/2642227/acd5876e-9a04-4772-a4d1-55b09ef2446f)
![2023-07-14_03 48 39](https://github.com/bernie-g/geckolib/assets/2642227/34ffdd13-bdd1-4c23-acdb-6d5f37df9268)

**Comment by Tslat** [comment]
Bring it to the discord
