### ISSUE TITLE
Not supporting minecraft forge < 1.18.2 anymore?

### ISSUE THREAD

**Issue by AllanAdrian** [bernie-g/geckolib#460]
I have the following minecraft forge version in my build.gradle file: 'net.minecraftforge:forge:1.18-38.0.4'

Then I followed the installation instructions for minecraft 1.18, which says adding the following as dependency:
implementation fg.deobf('software.bernie.geckolib:geckolib-forge-1.18:3.0.57')

I created a mod using this and the source code has no errors. However, when launching minecraft I got this:
Mod File geckolib-forge-1.18-3.0.57_mapped_official_1.18.jar needs language provider javafml:40 or above to load. We have found 38.

I googled around and it seems to suggest that my minecraft version (1.18) is too low. Indeed according to https://www.curseforge.com/minecraft/mc-mods/geckolib,  geckolib-forge-1.18:3.0.57 is for minecraft 1.18.2.  The gecko version for minecraft 1.18 seems to be 1.18:3.0.0 and 1.18:3.0.1. However, the installation instruction does not say how to install these earlier versions.

Is it possible to give instructions about how to use gecko for minecraft version < 1.18.2?
Thanks!

Z

**Comment by Tslat** [comment]
No

The general expectation is that you mod on the latest minor version of your chosen major version, at the very least

1.18.0 does not and will not have explicit support
