### ISSUE TITLE
[1.20.1] Geckolib Display Issues on Legendary Tooltips

### ISSUE THREAD

**Issue by Dr-WeiAL** [bernie-g/geckolib#466]
https://github.com/iron431/Irons-Spells-n-Spellbooks/issues/119
Reposted here because Irons-Spells-n-Spellbooks says it's Geckolib's issue

**Comment by Tslat** [comment]
It's not their issue, yeah

But I'm not sure it's geckolib's either
I'd be looking at legendary tooltips for this

Either way I don't see what geckolib is doing that would be causing this at a glance - and since it's in legendary tooltips that it's broken, I'd be reporting it to them too
