### ISSUE TITLE
[1.18.2] Deadloop crash at runtime in RawGeometryTree#getGroupFromHierarchy

### ISSUE THREAD

**Issue by 3093FengMing** [bernie-g/geckolib#467]
About HashMap
[debug.zip](https://github.com/bernie-g/geckolib/files/12195233/debug.zip)
Including. log file and. jfr file.
How to solve it?

**Comment by Tslat** [comment]
I don't see anything in those logs?

And 1.18 seems to be working fine for everyone else

**Comment by 3093FengMing** [comment]
> I don't see anything in those logs?
> 
> And 1.18 seems to be working fine for everyone else

You might want to take a look at the. jfr file, as the CPU usage has reached 100%

**Comment by YOM667** [comment]
I'm also having the bug. when i import geckolib dependency, I'll get stuck in the screen
![image](https://github.com/bernie-g/geckolib/assets/78844634/c4078a2c-3db2-4491-a3c7-f0628667b6f2)

**Comment by 3093FengMing** [comment]
> I don't see anything in those logs?
> 
> And 1.18 seems to be working fine for everyone else

please reopen this issue

**Comment by Tslat** [comment]
Feel free to keep discussing it

**Comment by 3093FengMing** [comment]
> Feel free to keep discussing it

We need a solution

**Comment by Tslat** [comment]
I don't have one

I'm not sure what's causing this, and 1.18.2 is an old version
