### ISSUE TITLE
[1.20.1] java.lang.NullPointerException crash after playing for few minutes (Fabric)

### ISSUE THREAD

**Issue by gamerpotion** [bernie-g/geckolib#469]
Hi one of our users has reported they crash after 10 mins of playing with below crash log. This is on geckolib-fabric-1.20.1-4.2.1.jar on the DarkRPG modpack

Crashlog - https://pastebin.com/yEQ3cGXY

Have you heard this before?

**Comment by Tslat** [comment]
Nope

Does it happen with no other mods installed

**Comment by gamerpotion** [comment]
> Nope
> 
> Does it happen with no other mods installed

Hi I think i might have narrowed it down if you want to try and replicate perhaps

if you install geckolib 
then https://www.curseforge.com/minecraft/mc-mods/dark-chidori-origin-origins-addon
making sure origins is also installed https://www.curseforge.com/minecraft/mc-mods/origins
also try with Sodium https://modrinth.com/mod/sodium
all on 1.20.1
(Dark Chidori is also my own mod)

Could it be the desaturation effect that is conflicting perhaps?

**Comment by gamerpotion** [comment]
Just had another user comment that they were using another origin and it had the same crash

https://pastebin.com/8pJJKRGZ

does this look like an origin mod issue or geckolib?

**Comment by Tslat** [comment]
Report it to origins

I'm not sure whose fault it is yet - but it is a very unusual bug that shouldn't really happen unless someone's doing something odd
idk what origins does, it might be something on them

**Comment by gamerpotion** [comment]
> Report it to origins
> 
> I'm not sure whose fault it is yet - but it is a very unusual bug that shouldn't really happen unless someone's doing something odd idk what origins does, it might be something on them

hi, i havent heard back from origins dev yet, but in the mean time ive tried to replicate the issue. 
while trying to replicate similar thing happened but this time it mentioned

```Caused by: java.lang.OutOfMemoryError: Failed to resize buffer from 2145388032 bytes to -2147482112 bytes```

full log - https://pastebin.com/8sRYXvP0

any idea if that would help resolve it?

Im starting to think it might be linked to this mod as well maybe - https://legacy.curseforge.com/minecraft/mc-mods/mariums-soulslike-weaponry
since I was equiping a chaos helmet

**Comment by Tslat** [comment]
Running out of memory is a problem o nyour side, not any mod's lol

**Comment by gamerpotion** [comment]
Ah ok,  
From line 2969 (https://pastebin.com/8sRYXvP0) it says that but then mentions geckolib?
does that mean its running out of memory trying to load something to do with gekolib?

**Comment by Tslat** [comment]
Doesn't really matter

Running out of memory is on your side - and anything else in that log becomes invalid as soon as that's present

**Comment by gamerpotion** [comment]
ok i see.  However in this log - https://pastebin.com/yEQ3cGXY
there was no memory mention so does that mean the issue is still present but without a memory problem?

**Comment by gamerpotion** [comment]
I think i might have found the issue. Its to do with anything that uses geckolib, so in my example it was the Soulslike weapon mod armor, but then there seems to be some conflict with the Origins mod self glow power..   if i remove that it fixes the issue.
maybe its a memory leak or maybe something else, im not entirely sure which mod is responsible.
For now I will remove the self glow from all my origin mods, but this bug still remains out there for other origins that may be using self glow with geckolib items
