### ISSUE TITLE
software.bernie.geckolib3.core.manager.AnimationData.getAnimationControllers()Ljava/util/HashMap; CRASH

### ISSUE THREAD

**Issue by jureflex** [bernie-g/geckolib#471]
game crashes mid fighting normal mobs like skeletons and zombies

error in launcher: 
The game crashed whilst unexpected error
Error: java.lang.NoSuchMethodError: software.bernie.geckolib3.core.manager.AnimationData.getAnimationControllers()Ljava/util/HashMap;

crash file attached:
[crash-2023-08-03_23.14.57-client.txt](https://github.com/bernie-g/geckolib/files/12255163/crash-2023-08-03_23.14.57-client.txt)

**Comment by Tslat** [comment]
Take this to ars nouveau
