### ISSUE TITLE
[1.19.2] Oculus and Geckolib Armor issue

### ISSUE THREAD

**Issue by iron431** [bernie-g/geckolib#475]
Under certain conditions, geckolib armor that you or other entities are wearing is rendered ~100 blocks out. It's unclear if this is a geckolib or oculus issue, but here it is for official tracking. I haven't personally tested with Iris Shaders.
![image](https://github.com/bernie-g/geckolib/assets/34083081/8c5dae04-4895-45f1-9f87-9c56ac512553)

**Comment by Tslat** [comment]
This bug was fixed in Geckolib4, but Geckolib3 is sunset. This is just an issue people will have to deal with if they don't want to update their MC versions
