### ISSUE TITLE
Unable to Load Model [Fabric 1.20.1]

### ISSUE THREAD

**Issue by cheicen** [bernie-g/geckolib#477]
https://github.com/cheicen/dungeonbosses

trying to make a custom mob for the first time, seem to have gotten to the point where it crashes every time I summon the mob for it can't find the geo file. 

Any help is greatly appreciated

**Comment by Dariensg** [comment]
Given that the linked repo has zero content on it, can't really help. This is also an issue that would probably be handled better through support channels in the Discord, since GitHub issues are typically for issues with the library itself, not your mod using the library.
