### ISSUE TITLE
Rendering issue, if an entity gets rendered a second time and there are multiple instances

### ISSUE THREAD

**Issue by fayer3** [bernie-g/geckolib#478]
when an entity has multiple instances, and they are rendered multiple times, when they are rendered the second time, all instances use the animation state of the last rendered entity in the first pass.
this happens with iris shaders, and with vivecraft
happens with both forge and fabric

using geckolib 1.20.1 4.2.1

for iris 1.20.1 1.6.5
with sodium 0.5.0

for vivecraft 1.20.1 1.0.1

using the example bat entity in those screenshots.
for iris, the shadows are rendered first, so they have the right animation, but the actual render that is the second pass, has both bats in the standing pose, which is the pose from the second bat
![2023-08-10_16 03 45](https://github.com/bernie-g/geckolib/assets/8282299/57da8829-4fd4-4074-8fec-ee91a560f6cf)
for vivecraft, the left  half of the image is the first pass, and the right the second pass.
in the left the bats have their correct animation state, but in the right all are stuck in the flying post of the last one
![image](https://github.com/bernie-g/geckolib/assets/8282299/6c0a12c6-cb53-418f-a8bd-52616e768030)

**Comment by fayer3** [comment]
I made a workaround fix myself for the time, if someone wants it https://github.com/fayer3/geckolib_hotfix
it increments the time slightly each time an entity is rendered, to force a reprocessing of the animation

**Comment by fayer3** [comment]
with 4.2.4, the entities are now stuck in a no animation state with shaders, so it's not really fixed
![grafik](https://github.com/bernie-g/geckolib/assets/8282299/4fd423fd-9ac2-4394-bab4-3544178114c5)

**Comment by Tslat** [comment]
It's specific to entity shadows, and it's a different issue entirely

I'm also not sure how it's happening cus all I did was revert the changes that broke it originally

The new issue is here
https://github.com/bernie-g/geckolib/issues/512
