### ISSUE TITLE
Converting "Java Block" to "Geckolib Animated Model" in Blockbench breaks model UVs

### ISSUE THREAD

**Issue by byteManiak** [bernie-g/geckolib#479]
Hi. I'm trying to convert a Java block model to a Geckolib model in Blockbench. The model itself looks fine, however the  face UVs are all oriented towards the same direction, which breaks texturing.

The original block looks like this:

![machinegun_ammo_box](https://github.com/bernie-g/geckolib/assets/4543110/305dad44-6c30-40da-bcc4-b2f344d0c5ba)

And after the conversion it looks like this:

![machinegun_ammo_box - Converted](https://github.com/bernie-g/geckolib/assets/4543110/72aadaad-69c2-46c9-ad5a-56d1686b276f)

I tried manually editing the per-UV "rotation" property in the .bbmodel file, but that didn't change anything.

**Comment by Tslat** [comment]
I'm gonna merge this with #482 since it's technically a duplicate
