### ISSUE TITLE
Geo armor rendering using the ItemArmorLayer is broken

### ISSUE THREAD

**Issue by DerToaster98** [bernie-g/geckolib#480]
The armor is not scaled and aligned correctly on the entity.

Interestingly, the moment the armor gets rendered at least once on a non-geckolib entity (i.e. using the vanilla armor layer), the position and scaling fixes itself.

https://streamable.com/jk5uxy

This applies to every armor registered *individually*. 

So if i equip the lizard example armor on the gremlin, it will appear misaligned, then i equip the armor (any piece) on a armor stand. Then the armor is fixed on the gremlin.

Now, if we equip the wolf armor on the gremlin, it will be misaligned, until any piece is rendered on a player, zombie, skeleton, armor stand etc.

**Comment by Tslat** [comment]
This is absolutely bizarre
