### ISSUE TITLE
Cannot rotate uv in a geckolib model

### ISSUE THREAD

**Issue by ghasto69** [bernie-g/geckolib#482]
This is necessary for some models and currently not having it makes me unable to animate my block.

**Comment by ghasto69** [comment]
Why enchancement I think it’s an issue

**Comment by bernie-g** [comment]
> Why enchancement I think it’s an issue

It's not an issue, geckolib has never had support for uv rotations because the bedrock schema that geckolib for models uses does not support uv rotations. May add this in the future

**Comment by Tslat** [comment]
Geckolib now supports this in 4.7+
