### ISSUE TITLE
Duplicated item models when “Bovines and Buttercups” installed

### ISSUE THREAD

**Issue by Ania54** [bernie-g/geckolib#483]
Minecraft 1.20.1
Fabric loader 0.14.21
Fabric API 0.86.1
Bovines and Buttercups 1.9.0 (latest)
Geckolib 4.2.1 (latest)

Some items, most notably bowls of nectar, have a copy of the item model near them in inventory, in item frames, as dropped items, etc. The copy seems to be shifted by a few pixels to the upper left corner and a bit backwards (it appears to be behind the item frame).
This occurs only when Geckolib is installed. Without it, the items render correctly.
Affected items include: all bowls of nectar and custom flower, custom mushroom, custom mushroom block in the item form (not placed).

A zombie holding the item:
![2023-08-18_16 38 03](https://github.com/MerchantPug/bovines-and-buttercups/assets/105673239/b57cd50b-df6e-4d97-986a-76dace8bfe7c)
Items in item frames:
![2023-08-18_16 35 30](https://github.com/MerchantPug/bovines-and-buttercups/assets/105673239/9ac453ce-7094-4d27-89c7-f1422b93b84f)
Items in invisible item frames:
![2023-08-18_16 35 43](https://github.com/MerchantPug/bovines-and-buttercups/assets/105673239/00309ece-af48-4b47-81a1-8680b76cdd8b)
Items laying on the ground with hitboxes shown:
![2023-08-18_16 37 08](https://github.com/MerchantPug/bovines-and-buttercups/assets/105673239/b697e5e3-ec1b-457d-8017-d83f1c85f39e)
![2023-08-18_16 37 18](https://github.com/MerchantPug/bovines-and-buttercups/assets/105673239/ae32b464-8e64-4520-ad00-8667c9764f31)
Other items:
![Screenshot from 2023-08-18 16-48-53](https://github.com/MerchantPug/bovines-and-buttercups/assets/105673239/20592fa7-40c8-481b-b573-c65f6c51996e)

**Comment by Tslat** [comment]
Do me a favour and test this again after the next update
I believe this is something I've already fixed but haven't yet released

**Comment by Ania54** [comment]
Fixed, thank you!
