### ISSUE TITLE
cant launch minecraft from intellij while geckolib is in dependencies

### ISSUE THREAD

**Issue by Shajden** [bernie-g/geckolib#487]
minecraft starts then crashes before i even see menu screen
[crash-2023-08-24_19.55.15-client.txt](https://github.com/bernie-g/geckolib/files/12432161/crash-2023-08-24_19.55.15-client.txt)

**Comment by Tslat** [comment]
You need to follow the installation instructions properly

https://github.com/bernie-g/geckolib/wiki/Installation-(Geckolib4)
