### ISSUE TITLE
[1.20.1] Armor Render bug with Iris shaders

### ISSUE THREAD

**Issue by ZsoltMolnarrr** [bernie-g/geckolib#488]
**Minecraft version** - 1.20.1
**Mod loader** - Fabric 0.14.22
**Mod version** - geckolib-fabric-1.20.1-4.2.2

The issue is present on 1.20.1 at least since Sodium 0.5.0 + Iris 1.6.5.

**Describe the bug**
When using any Iris shader, GeckoLib re-renders the Gecko armor worn by the client player in the distance.
![image](https://github.com/bernie-g/geckolib/assets/4989469/003a03a2-597a-4f43-a4fc-ce8fb3797a4c)
![image](https://github.com/bernie-g/geckolib/assets/4989469/661d8540-010f-46d2-bd7b-47d7b3ccd238)
![image](https://github.com/bernie-g/geckolib/assets/4989469/1e884ed0-3b1a-49cb-a3d7-f3a54607a51b)

https://github.com/bernie-g/geckolib/assets/4989469/cec8a9d4-1806-4d3d-a373-3405b10ba8c3

This issue does not occur when wearing armor sets with vanilla armor model.

**To Reproduce**
1. Install any mod (and all of its dependencies) that uses GeckoLib Armor Renderer featurset AND the latest version of Sodium and Iris. (In this example I install my own mod: Wizards and all of its depencies.)
2. Install Sodium 0.5.2 and Iris 1.6.8
3. Install any shaderpack (for example Complementary Shaders)
4. Enter the game, equip a Gecko rendered armor set
5. Look at the sky

The full modlist that was used to reproduce this scenario:
- cloth-config-11.1.106-fabric.jar
- fabric-api-0.87.0+1.20.1.jar
- geckolib-fabric-1.20.1-4.2.2.jar
- iris-mc1.20.1-1.6.8.jar
- player-animation-lib-fabric-1.0.2-rc1+1.20.jar
- runes-fabric-0.9.10+1.20.1.jar
- sodium-fabric-mc1.20.1-0.5.2.jar
- spell_engine-fabric-0.9.29+1.20.1.jar
- spell_power-fabric-0.9.15+1.20.1.jar
- trinkets-3.7.1.jar
- wizards-fabric-0.9.20+1.20.1.jar

Note: This modlist is long due to how many dependencies Wizards has, any mod that is using GeckoLib armor renderer can reproduce this alongside Iris shaders.

**Expected behavior**
Worn armor rendered on the actual player model only, nowhere else in the viewport.

**Comment by chorbintime** [comment]
Vouch - this is a very common issue

**Comment by ZsoltMolnarrr** [comment]
![image](https://github.com/bernie-g/geckolib/assets/4989469/087900b1-4e63-4219-8331-97f1fe6eb87a)

**Comment by ZsoltMolnarrr** [comment]
Change https://github.com/bernie-g/geckolib/blob/main/Fabric/src/main/java/software/bernie/geckolib/renderer/GeoArmorRenderer.java#L267 to `mc.levelRenderer.renderBuffers.bufferSource()` which will require an AW for Fabric and an AT for Forge for LevelRenderer#renderBuffers

AW needed: 
```
accessible field net/minecraft/client/renderer/LevelRenderer renderBuffers Lnet/minecraft/client/renderer/RenderBuffers;
mutable field net/minecraft/client/renderer/LevelRenderer renderBuffers Lnet/minecraft/client/renderer/RenderBuffers;
```

AT needed:
```
public-f net.minecraft.client.renderer.GameRenderer f_109064_ # renderBuffers
```

**Comment by Tslat** [comment]
They're the same buffers

They're literally passed from mc to levelrenderer for storage
What's the context of this solution?

**Comment by ZsoltMolnarrr** [comment]
This thread explains:
https://discord.com/channels/774352792659820594/1146850409735016498/1146850409735016498

**Comment by Tslat** [comment]
I'm not in that discord

**Comment by Tslat** [comment]
Fixed in https://github.com/bernie-g/geckolib/commit/af3a0bd93d3367b283c9c97ca288a0bcd84e1ca8
