### ISSUE TITLE
Crash with latest Fabric version

### ISSUE THREAD

**Issue by YuRaNnNzZZ** [bernie-g/geckolib#49]
https://gist.github.com/YuRaNnNzZZ/d82b236fef2a4c1716a8dfa099a10e30
Crash with only Fabric Loader, Fabric API and GeckoLib installed, equip iron armor and inventory (or anything else that shows player's model) will crash the game.
Minecraft: 1.16.4, Fabric Loader: 0.10.8, Fabric API: 0.27.1, GeckoLib: 3.0.0-beta.7

**Comment by DBotThePony** [comment]
Looks like Fabric API tries to access non existing property [here](https://github.com/FabricMC/fabric/blob/9a6c758109e930780509bf9b046888b4e274cc97/fabric-rendering-v1/src/main/java/net/fabricmc/fabric/mixin/client/rendering/MixinItem.java#L36), which produce such weird traceback.

I believe this is Fabric API and Minecraft versions mismatch (or Fabric API contain 1.17 exclusive changes on 1.16 branch). If so, please tell us to open issue on Fabric API repository, thank you.

**Comment by bernie-g** [comment]
This will be fixed in a few days once curseforge is non-readonly.
