### ISSUE TITLE
Geckolib not working

### ISSUE THREAD

**Issue by Spiltdestructor** [bernie-g/geckolib#491]
Hi,I'm working on a mod through MCreator and I have seen that it's not my mod that doesn't work,but Geckolib that doesn't,the mod,even tho i tried 1.19.2 and 1.19.4 doesn't work,when I press create a new world in single players it just dies,closes it self up in 1.19.4,in 1.19.2 it says when I press single player that the data packs have not been verified so,1.19.4 does the same when I try entering a pre-existing world and tells me to enter in safe mode, Minecraft says that Geckolib is out of date,1.19.2 and 1.19.4,I'm gonna try 1.20 and see if it does the same,yes I tried using Forge whit Geckolib only to see if it worked but nothing,please solve the issue

**Comment by Spiltdestructor** [comment]
Im not asking for help whit MCreator,I'm asking to get the issue fixed,the plugin that I use Is not your issue but mine if it doesn't work,but we are talking about the mod,even all alone whit the correct version installed whit CurseForge,in Forge doesn't work,so the issue is not my mod,the plugin or MCreator,I have seen other MCreator posts asking for help,so that's why,if I want help whit the plugin for MCreator I go ask at the right people that know everything about it,you do a great work whit this mod and make life easier for everyone,thanks for that

**Comment by Tslat** [comment]
We do'nt support Mcreator here

The mod works fine normally
If it doesn't work with Mcreator, seek help on the Mcreator forums

**Comment by Spiltdestructor** [comment]
The thing is the mod normally,it doesn't work,not whit MCreator,I wrote it in the Disclaimer too
