### ISSUE TITLE
1.20.1 shaders compatibility: armor and iron golem reflections

### ISSUE THREAD

**Issue by jackg2527** [bernie-g/geckolib#493]
Hi there, I noticed that shader reflections stopped working on armor (and iron golems), and finally narrowed it down to optifine + GeckoLib. I'm using:
- Forge 1.20.1-47.1.46
- OptiFine_1.20.1_HD_U_I6_pre6_MOD
- Kappa_v5.1 
- geckolib-forge-1.20.1-4.2.2
- No other mods
- Patrix resource pack

The first/top picture is without GeckoLib. Second pic shows what happens when I add GeckoLib: no reflections from armor or iron golem, but golden sword (in hand or item frame) and diamond block reflections are not affected. I also tried with Complementary v4.7.2 and got exactly the same results. 

I joined your Discord but didn't see this exact issue being discussed. It's also clear that you guys are beyond busy...any assistance you could provide would be greatly appreciated (and please let me know if I can send any other pics/info that could be helpful).

Thanks in advance for your help! 

![Kappa No Gecko](https://github.com/bernie-g/geckolib/assets/23530614/d3abe7e8-ccf5-434a-8055-bf23a5382fd3)
![Kappa Yes Gecko](https://github.com/bernie-g/geckolib/assets/23530614/315de26b-6eae-4773-9153-5d88eee7b8e7)

**Comment by Tslat** [comment]
What's your discord username?

**Comment by Tslat** [comment]
Can you test this on 4.1.3 for me?

**Comment by jackg2527** [comment]
> Can you test this on 4.1.3 for me?

Yes...and it worked! See pics below. 

It's funny I was going back to older GeckoLib versions for 1.20, and was thinking about trying 1.19.4 when I got your message. 
- 1.19.4-forge-45.1.0
- OptiFine_1.19.4_HD_U_I4_MOD
- Kappa shader with Patrix
- without vs. with geckolib-forge-1.19.4-4.1.3

Hope this helps with a solution. I'm sure it's a pain dealing with shader "stuff" but some of us are addicted so thanks for supporting our habit :)

![1 19 4 no GeckoLib](https://github.com/bernie-g/geckolib/assets/23530614/fff16c5e-bf38-4602-b983-1f9ec62c278b)
![1 19 4 with geckolib-forge-1 19 4-4 1 3](https://github.com/bernie-g/geckolib/assets/23530614/12728f69-1caf-48f7-9f92-6e319336f72d)

**Comment by Tslat** [comment]
Definitely gives a pretty significant lead

thanks

**Comment by jackg2527** [comment]
Hi, just wanted to let you know I tried your latest release geckolib-forge-1.20.1-4.2.3. Unfortunately got same results as in the pics (geckolib-forge-1.20.1-4.2.2): block and item reflections look great, no reflections for armor and iron golems. Just sharing this info in case it's helpful.

**Comment by Tslat** [comment]
Thanks for the update
I'll keep looking into it then

**Comment by jackg2527** [comment]
much appreciated!

**Comment by 909oce** [comment]
Just spent over an hour combing through my 150 mods trying to figure out why armor wasnt reflective, aswell as experience orbs weren't emitting light. Finally figured out it was GeckoLib and then came here to see someone already reported it. Please let me know if there is a fix as one of my mods requires this library but I don't want to give up my nice visuals.

**Comment by Tslat** [comment]
Not yet

Optifine is a pain to work with, and the issue is in a tricky spot to fix

**Comment by jackg2527** [comment]
Thanks for trying to fix this. I assume lack of access to Optifine code
made it difficult to impossible. I'll try Fabric/Iris/Continuity when I am
ready for a fresh batch of mods.

**Comment by Tslat** [comment]
Nah I have a fix for this coming, at least for optifine

I've confirmed it working on my side

**Comment by jackg2527** [comment]
Cool!

**Comment by jackg2527** [comment]
Hi, sorry to bring this up again, but same armor reflection issue with Oculus. Everything else works great. Last tried with: 
oculus-mc1.20.1-1.6.15
geckolib-forge-1.20.1-4.4
embeddium-0.3.1+mc1.20.1

Is there a fix and/or should I contact the Oculus guys? Performance blows away optifine and can get ctm from fabric Continuity mod using Sinytra Connector.

Thanks! (again)

**Comment by Tslat** [comment]
why not 4.4.2?

**Comment by jackg2527** [comment]
Thanks for the reply.

I tried 4.4.2 with latest versions of embeddium, oculus, continuity, lazurite (indium alternative). Same issue as above.

Right now I have about 200 mods so I'll try just geckolib with minimum for shaders and get back to you. Please let me know if you want me to test out anything else.

**Comment by jackg2527** [comment]
oops my bad. seeing issue with latest versions of oculus/embeddium, etc (NO GeckoLib).  Sorry about that.
