### ISSUE TITLE
1.12.2 - The most recent armour formats are partially incompatible

### ISSUE THREAD

**Issue by Sorax5** [bernie-g/geckolib#494]
Hi, I'm currently working on a **1.12.2** mod with Geckolib.

- forge 1.12.2-14.23.5.2860
- forge-1.12.2-geckolib 3.0.26

I've noticed a few incompatibilities in **1.12.2** with the most **recent BlockBench** 1.12.0 plugin format (or at least what I've deduced **from it**).
In particular, the **arm and leg bones** don't **strictly follow the limbs or even the body** that moves forward when a player Sneaks.

I'd also like to say that I've checked that **I haven't touched the pivots** by comparing the **data on the github** wiki.

I think it's a **format incompatibility** because when I use the **old wolf_armor model** present on the **1.12 branch** I don't have any problems and when I test my model on one of my mods in **1.16.5** I don't have **any problems either**.

**Body exemple**
![image](https://github.com/bernie-g/geckolib/assets/52173496/3b72b752-535a-4cb9-94de-9395571b82db)
![image](https://github.com/bernie-g/geckolib/assets/52173496/486a1b91-d01c-4a87-a337-086a8530f989)

**My test model**
```json
{
	"format_version": "1.12.0",
	"minecraft:geometry": [
		{
			"description": {
				"identifier": "geometry.test",
				"texture_width": 64,
				"texture_height": 64,
				"visible_bounds_width": 2,
				"visible_bounds_height": 3.5,
				"visible_bounds_offset": [0, 1.25, 0]
			},
			"bones": [
				{
					"name": "bipedHead",
					"pivot": [0, 24, 0]
				},
				{
					"name": "armorHead",
					"parent": "bipedHead",
					"pivot": [0, 24, 0]
				},
				{
					"name": "bipedBody",
					"pivot": [0, 24, 0]
				},
				{
					"name": "armorBody",
					"parent": "bipedBody",
					"pivot": [0, 24, 0],
					"cubes": [
						{"origin": [-4, 12, -2.1], "size": [8, 12, 4.2], "uv": [-2, -2]}
					]
				},
				{
					"name": "bipedLeftArm",
					"pivot": [-4, 22, 0]
				},
				{
					"name": "armorLeftArm",
					"parent": "bipedLeftArm",
					"pivot": [-4, 22, 0]
				},
				{
					"name": "bipedRightArm",
					"pivot": [4, 22, 0]
				},
				{
					"name": "armorRightArm",
					"parent": "bipedRightArm",
					"pivot": [4, 22, 0]
				},
				{
					"name": "bipedLeftLeg",
					"pivot": [-2, 12, 0]
				},
				{
					"name": "armorLeftLeg",
					"parent": "bipedLeftLeg",
					"pivot": [-2, 12, 0]
				},
				{
					"name": "armorLeftBoot",
					"parent": "bipedLeftLeg",
					"pivot": [-2, 12, 0]
				},
				{
					"name": "bipedRightLeg",
					"pivot": [2, 12, 0]
				},
				{
					"name": "armorRightLeg",
					"parent": "bipedRightLeg",
					"pivot": [2, 12, 0]
				},
				{
					"name": "armorRightBoot",
					"parent": "bipedRightLeg",
					"pivot": [2, 12, 0]
				}
			]
		}
	]
}
```

I don't know if my deductions are good but I hope they are and that even if 1.12.2 is an old version that works a bit badly it would still be possible to fix!

Thanks for reading!

**Comment by Tslat** [comment]
1.12 is done

Update if you want updates
