### ISSUE TITLE
1.19.2

### ISSUE THREAD

**Issue by thororen1234** [bernie-g/geckolib#495]
[latest.log](https://github.com/bernie-g/geckolib/files/12641213/latest.log)
3 main errors
java.lang.reflect.InvocationTargetException
Caused by: java.lang.Exception: Function 'null' requires at least 3 arguments. 1 are given!
java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 0

**Comment by Tslat** [comment]
If it's not causing any issues then you can ignore it
