### ISSUE TITLE
Question : Clarification on if This is possible

### ISSUE THREAD

**Issue by DePhoegon** [bernie-g/geckolib#496]
https://github.com/DePhoegon/delchoco-fabric/blob/master/src/main/java/com/dephoegon/delchoco/client/models/armor/ChocoDisguiseModel.java

I am currently in need of being able to swap the identifier for the texture of the armor on the fly (by color), and I would to know how [if possible] it would be done.  (Currently 1.18.2)

I've spent a ... absurd amount of time porting from forge (and just gave up and used Gekolib for the model render) and would really love to be able to maintain the feature/effect of changing the colors of the worn armor.

Thanks for your time.

**Comment by Tslat** [comment]
Just return a different value?

If you want usage help, join the discord
