### ISSUE TITLE
[1.19.2] geckolib crashing?

### ISSUE THREAD

**Issue by ANormalRaft** [bernie-g/geckolib#499]
v 3.1.40
forge 43.2.23

When I was testing around with the Enemy Expansion mod, I got at least 2 crashes when rendering wild mobs from their mod, so I removed that mod, filed an issue (which has been since removed by me) and looked for other mob mods to test. I then installed Born in Chaos and then it crashed on me as well when it was rendering a mob from that mod (the pastebin below). All 3 crashes had a similar syntax and all 3 mention geckolib in the stacktrace.

The thing is, it never crashes when rendering a new world. But it often does when returning to an existing world.

https://pastebin.com/jnfsV05B

**Comment by Tslat** [comment]
This is not a geckolib issue
This is a mod issue
