### ISSUE TITLE
Blocks Models are very slightly offset

### ISSUE THREAD

**Issue by iglee42** [bernie-g/geckolib#500]
Hello I was working on my mod with geckolib models when I noticed that my models was very slightly offset compared to a classic block

This is not a fail from my models it's really a mod bug (I check my models on blockbench)

And also this is not a fail from my animations 

My models 
https://pastebin.com/gEtNmM2K
https://pastebin.com/kdZK5VDm

![2023-09-22_22 57 48](https://github.com/bernie-g/geckolib/assets/50081542/71854dd0-705d-4db1-8962-8c05c6795234)
![2023-09-22_22 57 59](https://github.com/bernie-g/geckolib/assets/50081542/8723dbf8-d258-437b-82ee-48088052ce92)

**Comment by Tslat** [comment]
This was fixed in Geckolib4

You can translate them back down in your renderer if needed
