### ISSUE TITLE
The game crashed！

### ISSUE THREAD

**Issue by Qee1y** [bernie-g/geckolib#501]
[crash-2023-10-02_12.32.29-client.txt](https://github.com/bernie-g/geckolib/files/12779681/crash-2023-10-02_12.32.29-client.txt)

**Comment by Tslat** [comment]
Possibly a mod conflict
Hard to tell with that modlist

Start removing mods to see when it gets fixed

**Comment by Qee1y** [comment]
When I replaced rubidium with embeddium, I never crashed due to geckolib rendering animation

**Comment by Tslat** [comment]
So it's a rubidium bug
