### ISSUE TITLE
Broken Mob Animations When Using Geckolib Mods with Iris Shaders

### ISSUE THREAD

**Issue by Moozipan** [bernie-g/geckolib#507]
I found this same issue in a previously closed (and supposedly fixed) post from a previous version, but it's still a thing.
Basically any mod with geckolib dependencies will have animation bugs, when using Iris shaders *with* Entity Shadows enabled. Mobs are still able to move around, but their animations are frozen or erratic, no idle animations, no moving legs, etc. Turning off Entity Shadows fixes the animations again.

When only one (geckolib modded) mob is in frame, sometimes the animations work properly even with Entity Shadows enabled, but as soon as you spawn a second mob next to it, the first one freezes and the only the second one has proper animations.

In my tests I was using Forge 1.20.1, Iris Shaders 1.6.10, BSL Shaders 8.2.06, Creeper Overhaul 3.0.1 and Geckolib 4.2.3
![creeper_test](https://github.com/bernie-g/geckolib/assets/67471468/506a1cde-d059-4560-b71e-3b7236a24f58)

**Comment by Tslat** [comment]
Sigh

**Comment by NolanHewitt** [comment]
Can  replicate this issue on my end as well.

**Comment by Tslat** [comment]
Yeah see how it goes after the next update
