### ISSUE TITLE
Iris Shader with Entity Shadows break entity animations using Geckolib 4.2.4

### ISSUE THREAD

**Issue by NolanHewitt** [bernie-g/geckolib#512]
With entity shadows on animations from mods using this lib will not play, but as soon as entity shadows are disabled animations work again. Using the 4.2.4 fabric version of geckolib for 1.20.1

**Comment by Tslat** [comment]
Excellent.. good to know we just can't win with shaders lol

**Comment by SaltSouls** [comment]
Same thing is happening with Oculus on forge 1.20.1 with geckolib 4.2.1-4.2.4.

**Comment by necromancerpigeon** [comment]
I had a similar issue in which my horse from SWEM mod started to T pose until i turned of the shadows on Complementary Shaders. 

It seem downgrading to 4.2.3

BTW I am using ( Oculus + Embeddium )

**Comment by SiverDX** [comment]
you may already know this but something about invoking the entity renderer twice is the problem

https://github.com/IrisShaders/Iris/blob/e8a625222920f9b9e8249b7adb285a83abf9bbda/src/main/java/net/coderbot/iris/pipeline/ShadowRenderer.java#L498-L502

example on what it looks like with oculus

![image](https://github.com/bernie-g/geckolib/assets/22003703/912655b8-86f1-42a7-ac63-fa3444e423ec)

**Comment by Tslat** [comment]
Yeah that's pretty much expected

The issue is we don't know why that's causing them to lock up yet

**Comment by justsomedragon** [comment]
can confirm. noticed this issue with Naturalist mod today, walking animations seem to break when iris shaders are enabled. head turns / wing flaps work just fine though, for some reason it's only the legs. i've been having this issue with a few playthroughs recently so figured i'd contribute to the post, hope this helps. (also sorry if this is the wrong place to post, i am not familiar with github)

mc: 1.20.1
fabric: 0.15.3
geckolib: 4.3.1

**Comment by zanyahtzee** [comment]
[looks like there's a fix out](https://legacy.curseforge.com/minecraft/mc-mods/geckoanimfix/download/5015552)

**Comment by SiverDX** [comment]
that seems to just re-introduce this
https://github.com/bernie-g/geckolib/commit/6204ee15862052ac63f79e2759f7ea92c9bed4c8

and there was probably a reason why it was removed

**Comment by Tslat** [comment]
Try 4.4

**Comment by NolanHewitt** [comment]
Version 4.4 looks like it fixed this issue! Thank you.
