### ISSUE TITLE
[1.20.1] Crash With Entity Culling

### ISSUE THREAD

**Issue by SaltSouls** [bernie-g/geckolib#513]
## Description:
The game will occasionally crash when using entity culling in combination with geckolib. This seems to occur at seemingly random intervals and happens when wandering around the world.

## Version:

- Minecraft: 1.20.1
- Forge: 47.2.4
- Geckolib: 4.2.4
- EntityCulling: 1.6.2

## Logs:
[latest.log](https://github.com/bernie-g/geckolib/files/13258595/latest.log) | [debug.log](https://github.com/bernie-g/geckolib/files/13258596/debug.log)

**Comment by MikiP98** [comment]
I had the same problem, but the game would almost instantly crash when I loaded a world created in a different game session.
I don’t know why that is the case, but it makes Entity Culling completely incompatible.

**Comment by Tslat** [comment]
Fixed in next release
