### ISSUE TITLE
Trying to play mod for Cave Dweller: Reimagined and it says that I am missing Geckolib3 and it requires Geckolib 3.1.40 or above to work

### ISSUE THREAD

**Issue by mirrorwolf99** [bernie-g/geckolib#514]
I have downloaded geckolib and everything is the correct version

**Comment by mirrorwolf99** [comment]
please provide a link of the correct thing to download. I am trying to play this on 1.19.2. I am using windows 10 and java

**Comment by Tslat** [comment]
The files are all available on CurseForge

Make sure you're downloading the right version, for the right modding platform
