### ISSUE TITLE
-1 error on loadup 1.19.2

### ISSUE THREAD

**Issue by AlienLoser** [bernie-g/geckolib#517]
everywhere i go, everyone i ask says its a geckolib error, despite what the error log says, below is the copy pasted error from the launcher
any help would be greatly appreciated

The game crashed whilst initializing game
Error: java.lang.IllegalAccessError: class forge.org.figuramc.figura.model.rendering.texture.RenderTypes$FiguraRenderType tried to access method 'net.minecraft.client.renderer.RenderType$CompositeRenderType net.minecraft.client.renderer.RenderType.m_173209_(java.lang.String, com.mojang.blaze3d.vertex.VertexFormat, com.mojang.blaze3d.vertex.VertexFormat$Mode, int, net.minecraft.client.renderer.RenderType$CompositeState)' (forge.org.figuramc.figura.model.rendering.texture.RenderTypes$FiguraRenderType is in module figura@0.1.2+1.19.2 of loader 'TRANSFORMER' @79476a4e; net.minecraft.client.renderer.RenderType is in module minecraft@1.19.2 of loader 'TRANSFORMER' @79476a4e)

**Comment by Tslat** [comment]
Nothing to do with Geckolib, take this to Figura
