### ISSUE TITLE
Problem with 4.3 shipped library -> class file for ... not found

### ISSUE THREAD

**Issue by SiverDX** [bernie-g/geckolib#520]
Project is set up for NeoForge
Am I missing something?

Tried it with Maven and CurseForge

```gradle
(...)
maven { /* GeckoLib */ url "https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/" }
(...)
implementation fg.deobf("software.bernie.geckolib:geckolib-forge-${minecraft_version}:${geckolib_version}")
// or 
implementation fg.deobf("curse.maven:geckolib-388172:4925805")
```

it won't resolve the jar-in-jar library (even if I start it in the IDE)

```log
error: cannot access MathBuilder
		parser.setValue("query.delta_y", () -> deltaMovement.y);
		      ^
  class file for com.eliotlash.mclib.math.MathBuilder not found
```

![image](https://github.com/bernie-g/geckolib/assets/22003703/04ef892c-259f-4e26-b11b-9c568874b15b)

![image](https://github.com/bernie-g/geckolib/assets/22003703/f9f36238-ccd1-4edd-8f95-e721758f9ccb)

I ran `clean`, reloaded all gradle projects, ran `genIntellijRuns`

If I load it myself it works: `implementation "com.eliotlash.mclib:mclib:20"`

**Comment by Witixin1512** [comment]
Can you post your full build.gradle

**Comment by SiverDX** [comment]
https://github.com/SiverDX/DragonSurvival/blob/1.20.1/build.gradle

**Comment by Tslat** [comment]
We are having.. significant issues trying to replicate this

We just can't get it to happen lol

**Comment by Tslat** [comment]
Ok worked out the root of the issue (Or at least, Witixin found it)

Basically, if you're using Mclib at compiletime (I.E. molang in your own mod), jarjar doesn't cater to you.
This will be automatically fixed once GeckoLib moved to multiloader, but for the time being you'll jsut need to implement the mclib library yourself if this error occurs

`implementation "com.eliotlash.mclib:mclib:20"`
