### ISSUE TITLE
Animation of item prevent the geckolib animation

### ISSUE THREAD

**Issue by GaylordFockerCN** [bernie-g/geckolib#522]
I use geckolib to build a gun,and everything is well when i right click air it can perform fire animation.But when i try to put the NBT to save the ammo count, i found that once you put tag,the fire animation will perform with a drop(which i think it's NBT's problem)How can I prevent that?Sorry for my poor Enghlish.

**Comment by Tslat** [comment]
Join the Geckolib discord, and provide your code
