### ISSUE TITLE
[1.18.2] Bug synchronized method with world (geckolib 3.0.57 latest 1.18.2 forge version)

### ISSUE THREAD

**Issue by ZUHOWKS** [bernie-g/geckolib#528]
Hello,

I have a bug with my Blockling Entity Class. I check in my `predicate()` method if it's the night in the world to do a specific animation with a shouldSleep() method:

```java
    // in BlocklingEntity class
    public boolean shouldSleep() {
        return !this.getCommandSenderWorld().isDay();
    }
```

This method return always false in my `predicate()` method even though it's the night.

```java
    // in BlocklingEntity class
    public boolean shouldSleep() {
        return !this.getCommandSenderWorld().isDay();
    }

    private  <E extends IAnimatable> PlayState predicate(AnimationEvent<E> event) {

        if (event.isMoving() && this.shouldSleep()) {
            event.getController().setAnimation(new AnimationBuilder().addAnimation("animation.blockling.walk2", ILoopType.EDefaultLoopTypes.LOOP));
        } else {
            event.getController().setAnimation(new AnimationBuilder()
                    .addAnimation("animation.blockling.idle3", ILoopType.EDefaultLoopTypes.PLAY_ONCE)
                    .addAnimation("animation.blockling.idle4", ILoopType.EDefaultLoopTypes.LOOP)
            );

        }

        return PlayState.CONTINUE;
    }
```
(So the animations in the else{...}  are all time set)

My class is extends to `Animal` and implements `IAnimatable, IAnimationTickable`. I noticed that only the methods coming from the Entity super class like `getOnPos()` or `interactAt()` are synchronized and return the values ​​synchronized with the game (or the server but I don't know precisely):

```java
     // in BlocklingEntity class
    private boolean shouldSleep = false; 
     
    @Override
    public @NotNull InteractionResult interactAt(@NotNull Player p_19980_, @NotNull Vec3 p_19981_, @NotNull InteractionHand hand) {
        if (hand == InteractionHand.MAIN_HAND) {
            this.shouldSleep= !this.shouldSleep; // Work !
        }

        return super.interactAt(p_19980_, p_19981_, hand);
    }
    
    private  <E extends IAnimatable> PlayState predicate(AnimationEvent<E> event) {

        if (event.isMoving() && this.shouldSleep) { // Work !
            event.getController().setAnimation(new AnimationBuilder().addAnimation("animation.blockling.walk2", ILoopType.EDefaultLoopTypes.LOOP));
        } else {
            event.getController().setAnimation(new AnimationBuilder()
                    .addAnimation("animation.blockling.idle3", ILoopType.EDefaultLoopTypes.PLAY_ONCE)
                    .addAnimation("animation.blockling.idle4", ILoopType.EDefaultLoopTypes.LOOP)
            );

        }

        return PlayState.CONTINUE;
    }
    
```

I know your are not supporting this version but, consider this ticket to resolve the problem for all. Thank you !

**Comment by ZUHOWKS** [comment]
I set the night in the world. you can see in the console first the position and in next the value return by the method `shouldSleep`
![image](https://github.com/bernie-g/geckolib/assets/73846641/b48eddae-2c3b-41f0-8b03-3c9687be99a7)

The position value are updated. The value return by the method is always false
![image](https://github.com/bernie-g/geckolib/assets/73846641/546abe25-c854-4dc6-9f7b-cfa0fa399125)

But in the baseTick method, the method return true:
![image](https://github.com/bernie-g/geckolib/assets/73846641/a76e0e63-a847-4ce5-b134-ce8f5c528be1)
![image](https://github.com/bernie-g/geckolib/assets/73846641/66515ca3-abfc-4035-9e39-4c1a2f703640)

I up some boolean but nothing work. How to fix it ?

**Comment by Dwinovo** [comment]
yes bro,today i meet the same problem ，so could you please tell me how do you work it out？

**Comment by ZUHOWKS** [comment]
Hello ! I come back to you with the repositery (if I'll find it). I believe I fixed it in the past.
