### ISSUE TITLE
Quilt incompatibility (1.20.1)

### ISSUE THREAD

**Issue by akirapink** [bernie-g/geckolib#533]
Starting MC+Quilt 1.20.1 with Geckolib and a mod that has it as a dependency crashes complaining that `GeckoLib 4 requires version [0.91.0+1.20.1, ∞) of fabric-api, which is missing!`

**Comment by Witixin1512** [comment]
Geckolib still requires Fabric api or QFapi

**Comment by akirapink** [comment]
but...i have QFAPI installed

**Comment by Witixin1512** [comment]
![image](https://github.com/bernie-g/geckolib/assets/73248264/43afbbbf-253a-47c6-b6f9-268c117cd2d5)
It's working fine for me, would you mind dropping by the Geckolib discord with the full log?: https://discord.gg/Bt3p6kA6TK

**Comment by akirapink** [comment]
UPD: figured it out, i had to downgrade geckolib
