### ISSUE TITLE
Right-clicking causes a crash

### ISSUE THREAD

**Issue by d39052** [bernie-g/geckolib#535]
I run a server with mohist-1.20.1-517-server. I have both geckolib-forge-1.20.1-4.4 and EpicFight-20.6.3 on the client and server. when I right click with the weapon, everything works fine on the server, but the client pops up with the following prompt and can no longer access the server. The server doesn't have any error messages either.
![DB22CE1CC25063E8E3AAB722DF3FD09A](https://github.com/bernie-g/geckolib/assets/157216847/3ed4552c-a9a4-4a41-a3c0-cef9a830e947)

**Comment by Witixin1512** [comment]
I'm not sure why this is being reported here. This is either a Mohist issue or an EpicFight issue.

If it does not happen in a regular forge server, it's a Mohist issue.
If it happens in a regular forge server, report it to Epic Fight.

Is there anything in particular that makes you think this is related to geckolib? The error seems network related...

**Comment by d39052** [comment]
I’m sorry to bother you again. I understand what you are saying, that you don’t think it’s a Geckolib problem. But after my tests, after removing Geckolib, everything works fine on both the server and the client, and pressing the right mouse button doesn&apos;t bring up that error. So I have reason to wonder if there is a feature in Geckolib that is incompatible with epic battles or the server that is causing the problem.
从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2024年1月20日 20:46
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [bernie-g/geckolib] Right-clicking causes a crash (Issue #535)


I'm not sure why this is being reported here. This is either a Mohist issue or an EpicFight issue.

If it does not happen in a regular forge server, it's a Mohist issue.
If it happens in a regular forge server, report it to Epic Fight.

Is there anything in particular that makes you think this is related to geckolib? The error seems network related...

―

**Comment by Tslat** [comment]
Provide the latest.log from the client that crashed then
