### ISSUE TITLE
My Mod with Geckolib isn't working in my minecraft server.

### ISSUE THREAD

**Issue by Turbinho** [bernie-g/geckolib#538]
For some reason, the mod that i made is not working in the server because:
Failure message: VSSMP (vssmp) has failed to load correctly
		java.lang.RuntimeException: Cannot find class net/minecraft/client/model/HumanoidModel
And the singleplayer is working normal, can someone pls help me?

**Comment by Witixin1512** [comment]
Looks like you're classloading client only classes in the server, where they're missing. This is most likely a mistake on your side. You should make sure not to load client only code on the server.

Join a modding discord for more help, as Github is not an ideal place for support
