### ISSUE TITLE
[BUG/ISSUE] Can't make GeckoLib work in Multiloader with Forge.

### ISSUE THREAD

**Issue by CerbonXD** [bernie-g/geckolib#539]
Basically, I'm trying to add GeckoLib as a dependency of my project, but it crashes when I open the game with Forge. I'm using Architecture loom.

NeoForge works fine; Didn't test with Fabric because I'm not going to support it.

Minecraft Version: 1.20.4
Forge Version: 49.0.19
GeckoLib Version: 4.4.2

[Main Build.gradle](https://pastecode.io/s/45okvarz)
[Forge Build.gradle](https://pastecode.io/s/sy0nxvbn)
[Latest Log](https://pastecode.io/s/cx2vaop7)

I already tried cleaning my cache and regenerate the runs.

**Comment by Tslat** [comment]
You'll need to add mclib as an explicit dependency in your build.gradle.

Come to the discord if you need more info
