### ISSUE TITLE
Could not find parent software/bernie/shadowed/fasterxml/jackson

### ISSUE THREAD

**Issue by Sunekaer** [bernie-g/geckolib#54]
forge-1.16.4-geckolib-3.0.0.jar
forge 35.1.11

https://paste.feed-the-beast.com/view/cb8dc237

**Comment by bernie-g** [comment]
@Sunekaer Is this in a dev environment?

**Comment by Sunekaer** [comment]
No, this is in a modpack

**Comment by bernie-g** [comment]
@Sunekaer Which modpack?

**Comment by Sunekaer** [comment]
One im making

**Comment by Sunekaer** [comment]
What info do you need?

**Comment by bernie-g** [comment]
I need to know the mod you're using that depends on GeckoLib, and what version of the mod you're using.

**Comment by Sunekaer** [comment]
ars nouveau version 1.16.3-1.8.1

**Comment by Sunekaer** [comment]
and Mana and Artifice 1.1.0.4

**Comment by bernie-g** [comment]
Use [this file instead.](https://www.curseforge.com/minecraft/mc-mods/geckolib/files/3135745)
