### ISSUE TITLE
Shader with real-time Shadows break animations using Geckolib 4.4.2

### ISSUE THREAD

**Issue by HaktyGaona** [bernie-g/geckolib#541]
I am using the Vic's Point Blank module, and the first person animation does not work when real-time lighting is activated. However, the module author claims that it is an issue with GeckoLib.
 (I am not the mod author, but I am very distressed that I cannot use shadows and mods together) =(

**Comment by Tslat** [comment]
Break?

Need more info

**Comment by HaktyGaona** [comment]
> Break?
> 
> Need more info

MInecraft Version: 1.20.1 Forge 47.2.20
Mods list: embeddium-0.2.18+mc1.20.1
                 oculus-mc1.20.1-1.6.13
                 geckolib-forge-1.20.1-4.4.2
                 pointblank-1.20.1-1.0.2 (Useing geckolib)
Shaderpacks: ComplementaryReimagined_r5.1.1

**Comment by HaktyGaona** [comment]
> Break?
> 
> Need more info

Animation does not work when real-time shadows start.
This mod only has first person animations.

**Comment by HammerBones** [comment]
> > Break?
> > Need more info
> 
> MInecraft Version: 1.20.1 Forge 47.2.20 Mods list: ·embeddium-0.2.18+mc1.20.1 ·oculus-mc1.20.1-1.6.13 ·geckolib-forge-1.20.1-4.4.2 ·pointblank-1.20.1-1.0.2 (Using geckolib) Shaderpacks: ComplementaryReimagined_r5.1.1

Potential fix but there is the compatibility mod on curseforge you could try.
[https://www.curseforge.com/minecraft/mc-mods/geckoanimfix](url)

**Comment by HaktyGaona** [comment]
> > > Break?
> > > Need more info
> > 
> > 
> > MInecraft Version: 1.20.1 Forge 47.2.20 Mods list: ·embeddium-0.2.18+mc1.20.1 ·oculus-mc1.20.1-1.6.13 ·geckolib-forge-1.20.1-4.4.2 ·pointblank-1.20.1-1.0.2 (Using geckolib) Shaderpacks: ComplementaryReimagined_r5.1.1
> 
> Potential fix but there is the compatibility mod on curseforge you could try. [https://www.curseforge.com/minecraft/mc-mods/geckoanimfix](url)

I have already tried before which is why I was here.

**Comment by Tslat** [comment]
It doesn't solve or do anything lol, it's just replacing geckolib code with the same geckolib code
That mod really should just be deleted at this stage

Your issue is a completely different one

**Comment by Tslat** [comment]
Can this be tested in 1.20.6+ pls

**Comment by HaktyGaona** [comment]
> Can this be tested in 1.20.6+ pls

Okey. This will take some time to test other mods.

**Comment by Tslat** [comment]
> Okey. This will take some time to test other mods.
> (I have updated all mods to the latest version. And then this issue has been resolved. ;) Thank you.)

It's fixed in 1.20.6+?

**Comment by HaktyGaona** [comment]
> > Okey. This will take some time to test other mods.
> > (I have updated all mods to the latest version. And then this issue has been resolved. ;) Thank you.)
> 
> It's fixed in 1.20.6+?

No, Pointblank only 1.20.1.
