### ISSUE TITLE
Problem with updating geckolib from 1.18.2 to 1.20.1

### ISSUE THREAD

**Issue by minebloxhd** [bernie-g/geckolib#542]
Hi! I've wanted to update my dedicated minecraft forge server from 1.18.2 to 1.20.1 but when I tried to start the server, it says in line 5.666: "Missing data pack mod:geckolib3" but I have geckolib for 1.20.1 in the mods folder. I've included the log.
[latest.log](https://github.com/bernie-g/geckolib/files/14210054/latest.log)

**Comment by Tslat** [comment]
You have far, far more issues here than geckolib
Join a modding help server and ask for assistance
