### ISSUE TITLE
Running under Velocity Proxy error

### ISSUE THREAD

**Issue by ptcd1548** [bernie-g/geckolib#545]
Hi! This happened to me. I'm using Velocity with Forge Server 1.20.1. I have no plugin installed on Velocity and some mods on servers ( [Proxy Compatible Forge](https://modrinth.com/mod/proxy-compatible-forge), The Man from The Fog, GeckoLib ). 
When I try to join servers through proxy it kicks me with the error: 

`Netty Epoll Server IO #2/ERROR] [ne.mi.ne.NetworkRegistry/NETREGISTRY]: Channels [man:man,geckolib:main] rejected vanilla connections`

Some logs here:
Velocity: [Here](https://filesharing.minelabs.cloud/share/logs/velocity-20.2.2024-11.16pm.txt)
Forge Server: [Here](https://filesharing.minelabs.cloud/share/logs/forgeserver-20.2.2024-11.16pm.txt)
Velocity Config: [Here](https://filesharing.minelabs.cloud/share/logs/velocity.toml-20.2.2024-11.16pm.txt)

**Comment by Tslat** [comment]
> This server has mods that require Forge to be installed on the client. Contact your server admin for more details.
