### ISSUE TITLE
Shader Armor Reflections incompatible

### ISSUE THREAD

**Issue by wisefries** [bernie-g/geckolib#546]
When using Iris shaders supporting labPBR resource packs, armor reflections are not present.

Active mods:
- GeckoLib 4.2.4
- Iris
- QFAPI
- Sodium

To replicate, use any shader with labPBR resource pack support, e.g. [Complementary Reimagined](https://modrinth.com/shader/complementary-reimagined), and a resource pack with PBR formatted textures, e.g. [DefaultPBR](https://modrinth.com/resourcepack/defaultpbr). (Modrinth links)

Intended effect, with Iris and Sodium:
![Iris](https://github.com/bernie-g/geckolib/assets/93115856/248570a6-8f6f-46d3-a65a-727e97cf6bb9)
When GeckoLib is present:
![Gecko](https://github.com/bernie-g/geckolib/assets/93115856/07cc0805-2ce0-4f11-8680-c4c89c8c4f1a)

**Comment by Tslat** [comment]
Update the mod then?

**Comment by wisefries** [comment]
my mistake, I mistyped 4.2.4 instead of the current version, 4.4.2. It's just a minor incompatibility that I thought I should mention.

**Comment by pnk2u** [comment]
I'm having the same issue with the same mods. Both POM and reflections (from resource packs using labPBR) on all movable entities (e.g. boats, minecarts, etc.) do not render.

**Comment by Tslat** [comment]
If you disable geckolib's mixins by removing the mixins from the mixins.json in the jar, does it fix it?

**Comment by pnk2u** [comment]
Yes, doing that fixes it. The POM and reflections render normally.

**Comment by Tslat** [comment]
I see

**Comment by Tslat** [comment]
Can this be tested in 1.20.6+ pls

**Comment by pnk2u** [comment]
Using 1.20.6 (v4.5.2): No change, same issue

**Comment by Tslat** [comment]
Damn

**Comment by blunderbust** [comment]
I also ran into this issue. I was running Patrix textures and noticed that the squids and iron golems were no longer reflective/shine. I tested all versions of Geckolib available on Modrinth (4.2.1 to 4.4.6).  None fixed the issue.

Like it was suggested earlier, I opened the geckolib.mixins.json file contained in the .jar file, removed the entries in the "client" section so it is a set of empty brackets [ ].  

For those interested you can open a .jar file by changing the .jar to .zip and then open the archive. You can then open the .json file with a text editor like notepad. save the edited .json file to your desktop, and then drop and replace the old .json in the .zip file.  when done, rename the .zip file back to .jar.

This fixed the issue.  If there is a better way to temp patch this mod let me know.  I can also test any potential fixes here as well.

MC 1.20.1
Fabric
Iris
Sodium
Lithium
Indium
Continuity
Entity Model Features
Entity Texture Features
Vanadium (colormatic replacement)

BSL shaders
Patrix texture pack

**Comment by pnk2u** [comment]
Actually, and since you asked, you can only remove the "client.TextureManagerMixin" (and the comma in the line above), you don't need to remove all of them.

**Comment by Tslat** [comment]
I can't seem to replicate this on 1.21 4.5.5?

![image](https://github.com/bernie-g/geckolib/assets/7098525/e7fa8ee8-7e05-4d41-9c77-c447241acf2a)
