### ISSUE TITLE
latest version of geckolib crashing have tested all mods out and geko is causing the issue

### ISSUE THREAD

**Issue by JaxTheCowboy** [bernie-g/geckolib#547]
![image](https://github.com/bernie-g/geckolib/assets/160982836/d3fcdf9e-beb1-457e-9a88-797b0dc5ce79)
![image](https://github.com/bernie-g/geckolib/assets/160982836/4fb7868c-6dd5-4118-a076-ba1d85cc4da7)

**Comment by JaxTheCowboy** [comment]
all previous too. might be an issue with my computer

**Comment by Tslat** [comment]
It's your computer

Your AMD graphics drivers are out of date
