### ISSUE TITLE
Incompatibility with Gilded Netherite

### ISSUE THREAD

**Issue by Snivyer1910** [bernie-g/geckolib#55]
This is either Gilded Netherite is incompatible with GeckoLib, GeckoLib is incompatible with Gilded or GeckoLib is borke

anyway I'll post this issue on both GeckoLib and Gilded Netherite to make sure that both developers are aware of this issue

https://paste.ee/p/6CzLB

**Comment by Snivyer1910** [comment]
scaldings/gilded-netherite-fabric#5

**Comment by bernie-g** [comment]
This will be fixed next update.

**Comment by Snivyer1910** [comment]
> This will be fixed next update.

Thanks, I'll be waiting for it!

**Comment by AzureDoom** [comment]
This should be fixed in the 3.0.1 update.
