### ISSUE TITLE
[1.20.1] Minecraft stuck when loading from intellij while geckolib is in dependencies

### ISSUE THREAD

**Issue by FenlFenl** [bernie-g/geckolib#552]
When I add geckolib I can successfully refresh the gradle project and then use the classes from geckolib in pmy code. But then when I try  to run the client, it gets stuck when the Minecraft Progress bar is almost full after:

 "REGISTRING minecraft:worldgen/biome" and all I can find in the console is "class io.netty.util.internal.PlatformDependent0$7 (in module io.netty.common) cannot access class jdk.internal.misc.Unsafe (in module java.base) because module java.base does not export jdk.internal.misc to module io.netty.common"
 
Since I am modding in 1.20.1 i modified :
"implementation fg.deobf('software.bernie.geckolib:geckolib-forge-1.20.4:4.4.2')" 
To:
 "implementation fg.deobf('software.bernie.geckolib:geckolib-forge-1.20.1:4.4.2')"

It's been some hours I try and I still haven't found anything that could help. So thanks for your time

**Comment by Tslat** [comment]
This isn't a geckolib bug, this is somehting wrong with your project
Join the discord and ask for help
