### ISSUE TITLE
Geckolib Example Mod Crashes My Data Generator.

### ISSUE THREAD

**Issue by eehunter** [bernie-g/geckolib#553]
I'm working on a mod integration addon for Dragon Survival and Spectrum. As the former is Forge-only and the latter is Fabric-only, this addon depends on Sinytra Connector. The addon does not itself require Geckolib, but Dragon Survival does. Somehow, the combination of Geckolib's Example Mod, Additional Entity Attributes (a dependency of Spectrum), and Sinytra Connector causes my runData configuration to crash with the following log: [latest.log](https://github.com/bernie-g/geckolib/files/14530305/latest.log)

Would it be possible to add a way to disable the Geckolib Example Mod in a workspace where it isn't needed (or if there's already a way to do this, add it to the documentation?), or provide a maven artifact that doesn't include it? I've spent a few hours already trying to fix this issue on my end and have yet to find a solution.

**Comment by eehunter** [comment]
I should note that this issue does _not_ affect runClient. I have yet to test it on runServer.

**Comment by Tslat** [comment]
I mean.. I don't really have any control over what sinytra might be breaking
Geckolib works perfectly fine in datagen, and if sinytra breaks it, then maybe they should be fixing it..

**Comment by eehunter** [comment]
After further testing, I have found that Dragon Survival causes the same issue, so disabling the Geckolib Example Mod would be pointless. This needs to be fixed from either Sinytra or Dafuqs's end.
