### ISSUE TITLE
[1.20.1] AutoGlowingGeoLayer on armor shows up completely black

### ISSUE THREAD

**Issue by KaptainQKool** [bernie-g/geckolib#554]
I'm new to modding, and I don't know exactly what I'm doing, but I'm trying to create a custom armor model with emissive parts. I have the armor model, textures, etc. working, but when I add an AutoGlowingGeoLayer to my armor renderer, then the pixels on the glowmask show up completely black instead of actually glowing.
Here's my code for the renderer:
`public QrazyKoolArmorRenderer() {
    super(new QrazyKoolArmorModel());
    addRenderLayer(new AutoGlowingGeoLayer<QrazyKoolArmorItem>(this));
}`
![2024-03-09_11 47 21](https://github.com/bernie-g/geckolib/assets/110294153/50ebc617-afa1-43b4-ba8e-f8c2a608200a)
![2024-03-09_11 47 33](https://github.com/bernie-g/geckolib/assets/110294153/f7e5b390-e810-4d5f-9e19-2a0363c2675f)
![2024-03-09_11 47 45](https://github.com/bernie-g/geckolib/assets/110294153/dc7623db-a2da-405c-8a11-391e84e0193d)
![qrazykool](https://github.com/bernie-g/geckolib/assets/110294153/8802a72c-dc74-4575-a4eb-18244820b1df)
![qrazykool_glowmask](https://github.com/bernie-g/geckolib/assets/110294153/ba4b4af6-4916-49f5-9da6-4174219c51d1)

**Comment by Tslat** [comment]
Can you join the discord and ask for help there
We need to look at a few things to work this out
