### ISSUE TITLE
In-game crash

### ISSUE THREAD

**Issue by Qee1y** [bernie-g/geckolib#556]
mc1.20.1 
forge 47.2.20
geckolib-fabric-1.20.1-4.4.2.jar
Why use fabric? Because a mod requires a fabric version
[latest.log](https://github.com/bernie-g/geckolib/files/14605263/latest.log)

**Comment by Tslat** [comment]
take this issue to ironsspellbooks

**Comment by Qee1y** [comment]
> 把这个问题带到 Ironsspellbooks

ok
