### ISSUE TITLE
Typo in Wiki

### ISSUE THREAD

**Issue by UnhappyCodings** [bernie-g/geckolib#558]
Hey!

Just saw there's a typo here:
[https://github.com/bernie-g/geckolib/wiki/Geckolib-Armor-(Geckolib4)#example-renderer-class](https://github.com/bernie-g/geckolib/wiki/Geckolib-Armor-(Geckolib4)#example-renderer-class)

Under the code tab at "Example Renderer Class"
The constructors name is not the class' name.

Nothing big, just wanted to mention!

**Comment by Tslat** [comment]
👍
