### ISSUE TITLE
Crashing when rendering: "Cannot read field "bone" because "snapshot" is null"

### ISSUE THREAD

**Issue by goldrat1** [bernie-g/geckolib#561]
Hi there,
I've had this issue happen multiple times with a few different mods that both use GeckoLib; once with Plenty of Golems and once with Enderman Overhaul. It evidently happens when rendering specific entities.
When the game tries to render these entities in some worlds/scenarios, the screen freezes, then turns white, then the game crashes.
I can render these mobs fine in other worlds (like in a Superflat testing world) and I've rendered them fine before, but in some scenarios it'll completely crash the game, bricking entire worlds.

I've attached two crash logs that both point to GeckoLib as the problem. They both have the same error message:
`java.lang.NullPointerException: Cannot read field "bone" because "snapshot" is null`

[crash-2024-03-17_15.41.09-client.txt](https://github.com/bernie-g/geckolib/files/14626398/crash-2024-03-17_15.41.09-client.txt)
[crash-2024-03-17_16.14.08-client.txt](https://github.com/bernie-g/geckolib/files/14626399/crash-2024-03-17_16.14.08-client.txt)

In a different thread that was also seeing NullPointerExceptions you recommended to remove EntityCulling, I did this and the issue still persists. Is there other mods that would affect this?

Please help, this is driving me crazy and making my worlds unplayable!

**Comment by goldrat1** [comment]
[crash-2024-03-17_22.11.41-client.txt](https://github.com/bernie-g/geckolib/files/14627326/crash-2024-03-17_22.11.41-client.txt)
It's now happening with Unusual Prehistory mobs as well. It seems almost any mob that uses GeckoLib as a library for it's animations is causing this.

**Comment by goldrat1** [comment]
4.4.4 fixed it! Thank you so much!

**Comment by Axalord** [comment]
Thanks for the help
