### ISSUE TITLE
Animation Glitches

### ISSUE THREAD

**Issue by DogeKingChris** [bernie-g/geckolib#565]
I have a modpack with a few mods which have creatures using this mod. In the same modpack, mob from those packs are glitching and freezing (in animation only). Like, they'll be walking but only the idle animation is playing. I've tested all other mods which add mobs on my modpack, and only the ones depending on GeckoLib are glitched like this. I'm not sure how to show this to you, or how to replicate this other than saying this: On Fabric 0.15.9 for Minecraft 1.20.1, download any mod which depends on geckolib, for example Useless Reptile or Naturalist. Spawn in a mob from the mods with summon or a spawn egg. Try to find a natural spawning mob from those mods too. For some reason, it happens more on naturally spawned mobs.

**Comment by Tslat** [comment]
You haven't even listed your geckolib version lol

**Comment by DogeKingChris** [comment]
The latest version on 1.20.1 fabric at that time, duh

**Comment by DogeKingChris** [comment]
> You haven't even listed your geckolib version lol
geckolib-fabric-1.20.1-4.4.4.jar

**Comment by Tslat** [comment]
Got any videos?
Can't replicate
