### ISSUE TITLE
How to get entity's target in controller.

### ISSUE THREAD

**Issue by wellwhz** [bernie-g/geckolib#567]
I try to use entity.getTarget() in the controller function, but it returns null. And I use entity.playSound(), it also make no sense.
Version:
forge 47.2.20
geckolib 1.20.1 4.4.4

**Comment by Tslat** [comment]
Not possible, the entity doesn't have a target on the client side

Also, this is not a geckolib issue, this is just you asking dev questions. Move to the discord
