### ISSUE TITLE
Attempting to set a bone's rotation to both its own rotation and the entity's head rotation in neoforge 1.20.4 results in the bone freaking out

### ISSUE THREAD

**Issue by NerdyPuzzle** [bernie-g/geckolib#570]
Trying to use both the bone's own rotation along with the entity's head rotation seems to result in the bone spinning around wildly or being rotated incorrectly. This is not the case if only the bone's rotation or the entity's rotation is used. (setting it to bone.getRotX/Y or headPitch * DEG TO RAD only). This is not the case in forge 1.20.1.

![image](https://github.com/bernie-g/geckolib/assets/112079900/cd9c9fc7-7e78-47de-9a7b-85c4740b421d)

Here is an example of the issue (Ignore the broken texture, that is unrelated)

https://imgur.com/iTBcX7U

**Comment by NerdyPuzzle** [comment]
Strangely this only happens when both head pitch/yaw and rotation is added together but no separately? Not sure why that suddenly started being the case in 1.20.4 but the issue isn't head rotation being incorrect.

**Comment by Tslat** [comment]
This was not changed in 1.20.4 lol

Something's going on on your end

**Comment by NerdyPuzzle** [comment]
This exact calculation doesn't make the head freak out in 1.20.1

**Comment by Tslat** [comment]
I mean it works fine in 1.20.4

![image](https://github.com/bernie-g/geckolib/assets/7098525/2a05b4f4-c9f9-446c-bb87-0fb2d9ea807d)

**Comment by Tslat** [comment]
Join the GeckoLib Discord and ask there for help

I'll reopen this if it proves to be an actual GeckoLib issue
Currently it does not look to be one
