### ISSUE TITLE
Some mixins will fail to apply in dev if Yarn mappings are used with Geckolib 4.5

### ISSUE THREAD

**Issue by NordAct** [bernie-g/geckolib#571]
Tested with clean Fabric project for 1.20.5 generated via MC Dev plugin. 
Yarn mappings version 1.20.5+build.1
Latest log: https://gist.github.com/NordAct/459fbd5277796ee31116437f523811e4
Crash log: https://gist.github.com/NordAct/feb9238b43f81d03b892090a46a9d043
Switching to Mojmaps does help to fix this

**Comment by Tslat** [comment]
Goddamnit yarn

**Comment by Tslat** [comment]
> Tested with clean Fabric project for 1.20.5 generated via MC Dev plugin. Yarn mappings version 1.20.5+build.1 Latest log: https://gist.github.com/NordAct/459fbd5277796ee31116437f523811e4 Crash log: https://gist.github.com/NordAct/feb9238b43f81d03b892090a46a9d043 Switching to Mojmaps does help to fix this

Provide your build.gradle file (or git link if you have it)

**Comment by NordAct** [comment]
> > Tested with clean Fabric project for 1.20.5 generated via MC Dev plugin. Yarn mappings version 1.20.5+build.1 Latest log: https://gist.github.com/NordAct/459fbd5277796ee31116437f523811e4 Crash log: https://gist.github.com/NordAct/feb9238b43f81d03b892090a46a9d043 Switching to Mojmaps does help to fix this
> 
> Provide your build.gradle file (or git link if you have it)

https://gist.github.com/NordAct/89ab7fdac240ac0c5dfd4a110407c510
