### ISSUE TITLE
Ram leak 

### ISSUE THREAD

**Issue by Gniewko112** [bernie-g/geckolib#577]
4.3 version and up creates ram leak

**Comment by Tslat** [comment]
Got anything to back that up?
Any logs? screenshots? anything?

**Comment by Gniewko112** [comment]
![Bez tytułu](https://github.com/bernie-g/geckolib/assets/168778403/6b07d306-39c2-472e-baf7-c79299ec3219)
![Bez tytułu2](https://github.com/bernie-g/geckolib/assets/168778403/1979a191-8d30-4cd3-9cee-136ed8e06669)

**Comment by Tslat** [comment]
Strip out all but Geckolib and one geckolib-using mod and compare

then do it again but with a different geckolib-using mod and compare

Screenshots pls

**Comment by Gniewko112** [comment]
well now i have to add 70 mods one by one xD 
![444](https://github.com/bernie-g/geckolib/assets/168778403/ece60214-4872-401f-b758-8f7a469d2194)

**Comment by Gniewko112** [comment]
Found it problem is caused by Fancy menu mod (3.1.7) first i tried it's dependancies and ram leak only occurs when fancy menu is in mods folder even with diseabled custom animated menu that the mod is for

**Comment by Gniewko112** [comment]
I was wrong, problem is caused by mod loadmyresources 1.0.4
