### ISSUE TITLE
Armor Reflections and Mob reflections/emissive textures not working for oculus shaders.

### ISSUE THREAD

**Issue by mandude345** [bernie-g/geckolib#578]
I spent a couple of hours trying to figure out what was causing the reflections on my armor and mob reflections not to show up. I ended up figuring out that it was geckolib but im not sure how to fix it. I am also using a recourse pack called ModernArch.

I would love to get to the bottom of this since geckolib is a great mod and most modded mobs require this mod.

**Comment by mandude345** [comment]
Oh im on version 1.20.1 and using latest geckolib version.

**Comment by Tslat** [comment]
Pretty sure this is a duplicate of #546 

I'd be curious to know if 4.5+ fixes this if you ever get the chance to check
