### ISSUE TITLE
Geckolib 4.5 fails to resolve some math expressions that older Geckolib versions could resolve

### ISSUE THREAD

**Issue by NordAct** [bernie-g/geckolib#579]
If you try to add some "offset" for either sin or cos functions, this will result in Geckolib not resolving those functions correctly (or preventing querys from working correctly, idk what is exactly happening here). Like:
`25+math.sin(query.anim_time*360/4-90)*3` - being passed as angle, this will result in bone being constantly angled at 25 degrees on axis where this expression was put and it will not change over time despite the query. Similar result also happens if you try to add value rather than substract, or use such expression for changing bone position or scaling
`25+math.sin(query.anim_time*360/4)*3` - this will work and change over time just fine

Some videos with demonstration of the bug:
- MC version 1.20.6, Geckolib 4.5.1: https://youtu.be/sSW8BL7_2o4
- MC version 1.20.4, Geckolib 4.4.4: https://youtu.be/mmWuiEUmcyI

Exact same model, exact same animation files. In Blockbench animation matches the one shown in video with Geckolib 4.4.4

Link to repos of the mod with links relevant files:
- 1.20.6, Geckolib 4.5.1:
- - Repo: https://github.com/NordAct/useless-reptile/tree/1.20.6
- - Animation file: https://github.com/NordAct/useless-reptile/blob/1.20.6/src/main/resources/assets/uselessreptile/animations/entity/lightning_chaser/lightning_chaser.animation.json
- - Model file: https://github.com/NordAct/useless-reptile/blob/1.20.6/src/main/resources/assets/uselessreptile/geo/entity/lightning_chaser/lightning_chaser.geo.json
- - Entity class: https://github.com/NordAct/useless-reptile/blob/1.20.6/src/main/java/nordmods/uselessreptile/common/entity/LightningChaserEntity.java

- 1.20.4, Geckolib 4.4.4:
- - Repo: https://github.com/NordAct/useless-reptile/tree/1.20.4
- - Animation file: https://github.com/NordAct/useless-reptile/blob/1.20.4/src/main/resources/assets/uselessreptile/animations/entity/lightning_chaser/lightning_chaser.animation.json
- - Model file: https://github.com/NordAct/useless-reptile/blob/1.20.4/src/main/resources/assets/uselessreptile/geo/entity/lightning_chaser/lightning_chaser.geo.json
- - Entity class: https://github.com/NordAct/useless-reptile/blob/1.20.4/src/main/java/nordmods/uselessreptile/common/entity/LightningChaserEntity.java

As of logs: there's no errors or warnings regarding this.

**Comment by Tslat** [comment]
Fixed in 4.5.2
