### ISSUE TITLE
What is that, why i see this?

### ISSUE THREAD

**Issue by rd-team0** [bernie-g/geckolib#580]
A problem occurred configuring root project 'extremes-1.19.4'.
> Could not resolve all files for configuration ':modImplementation'.
   > Could not find com.eliotlash.mclib:mclib:20.
     Searched in the following locations:
       - file:/E:/extremes-1.19.4/.gradle/loom-cache/remapped_mods/com/eliotlash/mclib/mclib/20/mclib-20.pom
       - file:/C:/Users/3/.gradle/caches/fabric-loom/minecraftMaven/com/eliotlash/mclib/mclib/20/mclib-20.pom
       - file:/E:/extremes-1.19.4/.gradle/loom-cache/minecraftMaven/com/eliotlash/mclib/mclib/20/mclib-20.pom
       - https://maven.fabricmc.net/com/eliotlash/mclib/mclib/20/mclib-20.pom
       - https://libraries.minecraft.net/com/eliotlash/mclib/mclib/20/mclib-20.pom
       - https://libraries.minecraft.net/com/eliotlash/mclib/mclib/20/mclib-20.jar
       - https://repo.maven.apache.org/maven2/com/eliotlash/mclib/mclib/20/mclib-20.jar
       - https://repo.maven.apache.org/maven2/com/eliotlash/mclib/mclib/20/mclib-20.pom
     Required by:
         project : > software.bernie.geckolib:geckolib-fabric-1.19.4:4.2
   > Could not find com.eliotlash.mclib:mclib:20.
     Searched in the following locations:
       - file:/E:/extremes-1.19.4/.gradle/loom-cache/remapped_mods/com/eliotlash/mclib/mclib/20/mclib-20.pom
       - file:/C:/Users/3/.gradle/caches/fabric-loom/minecraftMaven/com/eliotlash/mclib/mclib/20/mclib-20.pom
       - file:/E:/extremes-1.19.4/.gradle/loom-cache/minecraftMaven/com/eliotlash/mclib/mclib/20/mclib-20.pom
       - https://maven.fabricmc.net/com/eliotlash/mclib/mclib/20/mclib-20.pom
       - https://libraries.minecraft.net/com/eliotlash/mclib/mclib/20/mclib-20.pom
       - https://libraries.minecraft.net/com/eliotlash/mclib/mclib/20/mclib-20.jar
       - https://repo.maven.apache.org/maven2/com/eliotlash/mclib/mclib/20/mclib-20.jar
       - https://repo.maven.apache.org/maven2/com/eliotlash/mclib/mclib/20/mclib-20.pom
     Required by:
         project : > software.bernie.geckolib:geckolib-fabric-1.19.4:4.2 > software.bernie.geckolib:geckolib-core:2.0.4.1

**Comment by rd-team0** [comment]
i just wanted to add geckolib to my project, but i cant

**Comment by Witixin1512** [comment]
The GeckoLib maven seems to be missing entirely from the list of allowed locations. Double check that you have followed the [Installation](https://github.com/bernie-g/geckolib/wiki/Installation-(Geckolib4)) page properly.

I'd recommend you join the [discord server](https://discord.gg/Bt3p6kA6TK), as Github is not the best place for support.
