### ISSUE TITLE
fabric api just doesnt work with it

### ISSUE THREAD

**Issue by Cheezy-bip** [bernie-g/geckolib#586]
so i need fabric api for my other mods

![image](https://github.com/bernie-g/geckolib/assets/159695210/17bb724c-3891-4467-a03d-92d0b72a8f3b)

huh
i play on 1.20.1 and it would be hard to switch to another version so pls fix
I don't have much details

**Comment by Tslat** [comment]
Install the correct version of fabric api then?

**Comment by Cheezy-bip** [comment]
it says that the correct version to install is the same version as I have

**Comment by Tslat** [comment]
That's not what the message says

**Comment by cheezygt** [comment]
nevermind i am fucking blind
