### ISSUE TITLE
Play Once is forcibly when "loop": true in BB

### ISSUE THREAD

**Issue by BlackAures1** [bernie-g/geckolib#591]
On newer versions of the plugin Play Once is forcibly applied, although the file clearly states that it is "loop": true. The other animation file doesn't have this problem, but I need this particular file with my 400+ animations. What can I do to fix this automatically instead of manually?  Also, if I "fix" it manually, what prevents it from breaking everything again after restarting the software?

Animations [here](https://github.com/DragonSurvivalTeam/DragonSurvival/tree/v1.19.2/src/main/resources/assets/dragonsurvival/animations)
Model [here](https://github.com/DragonSurvivalTeam/DragonSurvival/blob/v1.19.2/src/main/resources/assets/dragonsurvival/geo/dragon_model.geo.json)

- When uninstalling the geckolib plugin there is no problem with incorrect "play once".
- Full reinstallation of plugins and blockbench did not help

![image](https://github.com/bernie-g/geckolib/assets/43911230/3103ab37-70d3-4268-b6c7-1c88f08ae27e)
![image](https://github.com/bernie-g/geckolib/assets/43911230/d399fbfd-2614-4212-b590-0ff7f915bf48)

**Comment by Tslat** [comment]
I'll look into the plugin issue - however in this case it shouldn't matter

In Geckolib3, the animation json's loop type was completely ignored - it's all determined by what loop type you use in code

**Comment by BlackAures1** [comment]
![image](https://github.com/bernie-g/geckolib/assets/43911230/99533532-c754-4977-912c-54362dba604f)
If anyone needs a fix, it looks like this

**Comment by Tslat** [comment]
That doesn't do anything
Geckolib accepts both true/false & "loop" options

**Comment by Horokai21** [comment]
Same problem 
![image](https://github.com/bernie-g/geckolib/assets/173525949/c18e43c7-519c-48de-a9e1-d6c94365935c)

**Comment by BlackAures1** [comment]
> That doesn't do anything
> Geckolib accepts both true/false & "loop" options

It has helped me personally. Maybe in newer versions there is a problem with "true". Because in old versions it was not like that. This error appeared about 1-2 weeks ago. I would also like to remind you that this problem only appears when the geckolib plugin is installed. In pure Blockbench this is not the case.

**Comment by Tslat** [comment]
Oh with the plugin

Sorry I misunderstood - I thought you meant with geckolib itself

**Comment by Horokai21** [comment]
I fixed the problem simply by installing the old plugin version 3.07

**Comment by Tslat** [comment]
Incoming fix

Sorry it's taken so long
