### ISSUE TITLE
Animation not being parsed correctly

### ISSUE THREAD

**Issue by Scouter456** [bernie-g/geckolib#593]
After updating to version 4.5.5 my animations dont seem to be working anymore.
The error is shown in here: 
https://pastebin.com/dGxJnN08

In here are the animations I was using: https://github.com/Scouter456/Nether_Depths_Upgrade/tree/nether_depths_upgrade_1.21/src/main/resources/assets/netherdepthsupgrade/animations/entity

**Comment by Tslat** [comment]
Actual link to animation
https://github.com/Scouter456/Nether_Depths_Upgrade/blob/c044cf38aaab51b78e3a2e6be44a6fefb17c3662/src/main/resources/assets/netherdepthsupgrade/animations/entity/obsidianfish.animation.json#L71

**Comment by Tslat** [comment]
This is fixed in next version, out soon
