### ISSUE TITLE
I believe commit a4ca7eb broke easings in animations

### ISSUE THREAD

**Issue by miyo6032** [bernie-g/geckolib#594]
Updated from fabric 4.5.1 to 4.5.4, and easings on all my animations broke. Debugged a bit, I believe the changes to getTripletObj broke loading easings.

**Comment by Tslat** [comment]
Got an example animation json that broke?

**Comment by miyo6032** [comment]
For example this one doesn't load the easing or the easingArgs

[levitation_block.animation.json](https://github.com/user-attachments/files/15913949/levitation_block.animation.json)

**Comment by Tslat** [comment]
Thanks

**Comment by Tslat** [comment]
This is fixed in next version, out soon
