### ISSUE TITLE
1.18.2 the latest version of gecko is not compatible

### ISSUE THREAD

**Issue by zc1108aaa** [bernie-g/geckolib#596]
[latest.log](https://github.com/user-attachments/files/16131794/latest.log)
1
[crash-2024-07-08_23.42.54-client.txt](https://github.com/user-attachments/files/16131795/crash-2024-07-08_23.42.54-client.txt)
1
[crash-2024-07-09_00.05.03-client.txt](https://github.com/user-attachments/files/16131796/crash-2024-07-09_00.05.03-client.txt)

**Comment by Tslat** [comment]
Unrelated to geckolib, you have a broken pack
