### ISSUE TITLE
cannot access BuiltinModelItemRenderer

### ISSUE THREAD

**Issue by MerlinHose** [bernie-g/geckolib#602]
At the moment I'm following the tutorial:
[LINK](https://youtu.be/pmoAtMbQYog?si=Xx65xFNE0FP73vxC)

but for some reason I keep getting this error:
`14:55:07: Executing 'runClient --info'...

The client will now receive all logging from the daemon (pid: 13724). The daemon log file: C:\Users\hoesl\.gradle\daemon\8.8\daemon-13724.out.log
Starting 9th build in daemon [uptime: 13 mins 44.066 secs, performance: 99%, GC rate: 0.02/s, heap usage: 12% of 1 GiB]
Using 16 worker leases.
Now considering [J:\JetBrains\IntelliJIDEAUltimateProjects\Mods\DigDeeper] as hierarchies to watch
Watching the file system is configured to be enabled if available
File system watching is active
Starting Build
Settings evaluated using settings file 'J:\JetBrains\IntelliJIDEAUltimateProjects\Mods\DigDeeper\settings.gradle'.
Projects loaded. Root project using build file 'J:\JetBrains\IntelliJIDEAUltimateProjects\Mods\DigDeeper\build.gradle'.
Included projects: [root project 'DigDeeper']

> Configure project :
Evaluating root project 'DigDeeper' using build file 'J:\JetBrains\IntelliJIDEAUltimateProjects\Mods\DigDeeper\build.gradle'.
Transforming fabric-loom-1.7-SNAPSHOT.jar (net.fabricmc:fabric-loom:1.7-SNAPSHOT:20240704.165201-2) with InstrumentationAnalysisTransform
Transforming commons-io-2.15.1.jar (commons-io:commons-io:2.15.1) with InstrumentationAnalysisTransform
Transforming gson-2.10.1.jar (com.google.code.gson:gson:2.10.1) with InstrumentationAnalysisTransform
Transforming stitch-0.6.2.jar (net.fabricmc:stitch:0.6.2) with InstrumentationAnalysisTransform
Transforming guava-33.0.0-jre.jar (com.google.guava:guava:33.0.0-jre) with InstrumentationAnalysisTransform
Transforming tiny-remapper-0.10.3.jar (net.fabricmc:tiny-remapper:0.10.3) with InstrumentationAnalysisTransform
Transforming asm-commons-9.6.jar (org.ow2.asm:asm-commons:9.6) with InstrumentationAnalysisTransform
Transforming asm-util-9.6.jar (org.ow2.asm:asm-util:9.6) with InstrumentationAnalysisTransform
Transforming asm-analysis-9.6.jar (org.ow2.asm:asm-analysis:9.6) with InstrumentationAnalysisTransform
Transforming asm-tree-9.6.jar (org.ow2.asm:asm-tree:9.6) with InstrumentationAnalysisTransform
Transforming asm-9.6.jar (org.ow2.asm:asm:9.6) with InstrumentationAnalysisTransform
Transforming access-widener-2.1.0.jar (net.fabricmc:access-widener:2.1.0) with InstrumentationAnalysisTransform
Transforming mapping-io-0.6.1.jar (net.fabricmc:mapping-io:0.6.1) with InstrumentationAnalysisTransform
Transforming lorenz-tiny-4.0.2.jar (net.fabricmc:lorenz-tiny:4.0.2) with InstrumentationAnalysisTransform
Transforming fabric-loom-native-0.2.0.jar (net.fabricmc:fabric-loom-native:0.2.0) with InstrumentationAnalysisTransform
Transforming mercury-0.4.1.jar (net.fabricmc:mercury:0.4.1) with InstrumentationAnalysisTransform
Transforming kotlinx-metadata-jvm-0.9.0.jar (org.jetbrains.kotlinx:kotlinx-metadata-jvm:0.9.0) with InstrumentationAnalysisTransform
Transforming failureaccess-1.0.2.jar (com.google.guava:failureaccess:1.0.2) with InstrumentationAnalysisTransform
Transforming listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar (com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava) with InstrumentationAnalysisTransform
Transforming jsr305-3.0.2.jar (com.google.code.findbugs:jsr305:3.0.2) with InstrumentationAnalysisTransform
Transforming checker-qual-3.41.0.jar (org.checkerframework:checker-qual:3.41.0) with InstrumentationAnalysisTransform
Transforming error_prone_annotations-2.23.0.jar (com.google.errorprone:error_prone_annotations:2.23.0) with InstrumentationAnalysisTransform
Transforming tiny-mappings-parser-0.3.0+build.17.jar (net.fabricmc:tiny-mappings-parser:0.3.0+build.17) with InstrumentationAnalysisTransform
Transforming at-0.1.0-rc1.jar (org.cadixdev:at:0.1.0-rc1) with InstrumentationAnalysisTransform
Transforming lorenz-0.5.7.jar (org.cadixdev:lorenz:0.5.7) with InstrumentationAnalysisTransform
Transforming bombe-0.3.4.jar (org.cadixdev:bombe:0.3.4) with InstrumentationAnalysisTransform
Transforming fabric-loom-1.7-SNAPSHOT.jar (net.fabricmc:fabric-loom:1.7-SNAPSHOT:20240704.165201-2) with InstrumentationAnalysisTransform
Transforming fabric-loom-1.7-SNAPSHOT.jar (net.fabricmc:fabric-loom:1.7-SNAPSHOT:20240704.165201-2) with MergeInstrumentationAnalysisTransform
Transforming commons-io-2.15.1.jar (commons-io:commons-io:2.15.1) with InstrumentationAnalysisTransform
Transforming commons-io-2.15.1.jar (commons-io:commons-io:2.15.1) with MergeInstrumentationAnalysisTransform
Transforming gson-2.10.1.jar (com.google.code.gson:gson:2.10.1) with InstrumentationAnalysisTransform
Transforming gson-2.10.1.jar (com.google.code.gson:gson:2.10.1) with MergeInstrumentationAnalysisTransform
Transforming fabric-loom-1.7-SNAPSHOT.jar (net.fabricmc:fabric-loom:1.7-SNAPSHOT:20240704.165201-2) with ExternalDependencyInstrumentingArtifactTransform
Transforming commons-io-2.15.1.jar (commons-io:commons-io:2.15.1) with ExternalDependencyInstrumentingArtifactTransform
Transforming stitch-0.6.2.jar (net.fabricmc:stitch:0.6.2) with InstrumentationAnalysisTransform
Transforming stitch-0.6.2.jar (net.fabricmc:stitch:0.6.2) with MergeInstrumentationAnalysisTransform
Transforming gson-2.10.1.jar (com.google.code.gson:gson:2.10.1) with ExternalDependencyInstrumentingArtifactTransform
Transforming guava-33.0.0-jre.jar (com.google.guava:guava:33.0.0-jre) with InstrumentationAnalysisTransform
Transforming guava-33.0.0-jre.jar (com.google.guava:guava:33.0.0-jre) with MergeInstrumentationAnalysisTransform
Transforming stitch-0.6.2.jar (net.fabricmc:stitch:0.6.2) with ExternalDependencyInstrumentingArtifactTransform
Transforming tiny-remapper-0.10.3.jar (net.fabricmc:tiny-remapper:0.10.3) with InstrumentationAnalysisTransform
Transforming tiny-remapper-0.10.3.jar (net.fabricmc:tiny-remapper:0.10.3) with MergeInstrumentationAnalysisTransform
Transforming guava-33.0.0-jre.jar (com.google.guava:guava:33.0.0-jre) with ExternalDependencyInstrumentingArtifactTransform
Transforming asm-commons-9.6.jar (org.ow2.asm:asm-commons:9.6) with InstrumentationAnalysisTransform
Transforming asm-commons-9.6.jar (org.ow2.asm:asm-commons:9.6) with MergeInstrumentationAnalysisTransform
Transforming tiny-remapper-0.10.3.jar (net.fabricmc:tiny-remapper:0.10.3) with ExternalDependencyInstrumentingArtifactTransform
Transforming asm-util-9.6.jar (org.ow2.asm:asm-util:9.6) with InstrumentationAnalysisTransform
Transforming asm-util-9.6.jar (org.ow2.asm:asm-util:9.6) with MergeInstrumentationAnalysisTransform
Transforming asm-commons-9.6.jar (org.ow2.asm:asm-commons:9.6) with ExternalDependencyInstrumentingArtifactTransform
Transforming asm-analysis-9.6.jar (org.ow2.asm:asm-analysis:9.6) with InstrumentationAnalysisTransform
Transforming asm-analysis-9.6.jar (org.ow2.asm:asm-analysis:9.6) with MergeInstrumentationAnalysisTransform
Transforming asm-util-9.6.jar (org.ow2.asm:asm-util:9.6) with ExternalDependencyInstrumentingArtifactTransform
Transforming asm-tree-9.6.jar (org.ow2.asm:asm-tree:9.6) with InstrumentationAnalysisTransform
Transforming asm-tree-9.6.jar (org.ow2.asm:asm-tree:9.6) with MergeInstrumentationAnalysisTransform
Transforming asm-analysis-9.6.jar (org.ow2.asm:asm-analysis:9.6) with ExternalDependencyInstrumentingArtifactTransform
Transforming asm-9.6.jar (org.ow2.asm:asm:9.6) with InstrumentationAnalysisTransform
Transforming asm-9.6.jar (org.ow2.asm:asm:9.6) with MergeInstrumentationAnalysisTransform
Transforming asm-tree-9.6.jar (org.ow2.asm:asm-tree:9.6) with ExternalDependencyInstrumentingArtifactTransform
Transforming access-widener-2.1.0.jar (net.fabricmc:access-widener:2.1.0) with InstrumentationAnalysisTransform
Transforming access-widener-2.1.0.jar (net.fabricmc:access-widener:2.1.0) with MergeInstrumentationAnalysisTransform
Transforming asm-9.6.jar (org.ow2.asm:asm:9.6) with ExternalDependencyInstrumentingArtifactTransform
Transforming mapping-io-0.6.1.jar (net.fabricmc:mapping-io:0.6.1) with InstrumentationAnalysisTransform
Transforming mapping-io-0.6.1.jar (net.fabricmc:mapping-io:0.6.1) with MergeInstrumentationAnalysisTransform
Transforming access-widener-2.1.0.jar (net.fabricmc:access-widener:2.1.0) with ExternalDependencyInstrumentingArtifactTransform
Transforming lorenz-tiny-4.0.2.jar (net.fabricmc:lorenz-tiny:4.0.2) with InstrumentationAnalysisTransform
Transforming lorenz-tiny-4.0.2.jar (net.fabricmc:lorenz-tiny:4.0.2) with MergeInstrumentationAnalysisTransform
Transforming mapping-io-0.6.1.jar (net.fabricmc:mapping-io:0.6.1) with ExternalDependencyInstrumentingArtifactTransform
Transforming fabric-loom-native-0.2.0.jar (net.fabricmc:fabric-loom-native:0.2.0) with InstrumentationAnalysisTransform
Transforming fabric-loom-native-0.2.0.jar (net.fabricmc:fabric-loom-native:0.2.0) with MergeInstrumentationAnalysisTransform
Transforming lorenz-tiny-4.0.2.jar (net.fabricmc:lorenz-tiny:4.0.2) with ExternalDependencyInstrumentingArtifactTransform
Transforming mercury-0.4.1.jar (net.fabricmc:mercury:0.4.1) with InstrumentationAnalysisTransform
Transforming mercury-0.4.1.jar (net.fabricmc:mercury:0.4.1) with MergeInstrumentationAnalysisTransform
Transforming kotlinx-metadata-jvm-0.9.0.jar (org.jetbrains.kotlinx:kotlinx-metadata-jvm:0.9.0) with InstrumentationAnalysisTransform
Transforming fabric-loom-native-0.2.0.jar (net.fabricmc:fabric-loom-native:0.2.0) with ExternalDependencyInstrumentingArtifactTransform
Transforming kotlinx-metadata-jvm-0.9.0.jar (org.jetbrains.kotlinx:kotlinx-metadata-jvm:0.9.0) with MergeInstrumentationAnalysisTransform
Transforming mercury-0.4.1.jar (net.fabricmc:mercury:0.4.1) with ExternalDependencyInstrumentingArtifactTransform
Transforming failureaccess-1.0.2.jar (com.google.guava:failureaccess:1.0.2) with InstrumentationAnalysisTransform
Transforming failureaccess-1.0.2.jar (com.google.guava:failureaccess:1.0.2) with MergeInstrumentationAnalysisTransform
Transforming kotlinx-metadata-jvm-0.9.0.jar (org.jetbrains.kotlinx:kotlinx-metadata-jvm:0.9.0) with ExternalDependencyInstrumentingArtifactTransform
Transforming listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar (com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava) with InstrumentationAnalysisTransform
Transforming listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar (com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava) with MergeInstrumentationAnalysisTransform
Transforming failureaccess-1.0.2.jar (com.google.guava:failureaccess:1.0.2) with ExternalDependencyInstrumentingArtifactTransform
Transforming jsr305-3.0.2.jar (com.google.code.findbugs:jsr305:3.0.2) with InstrumentationAnalysisTransform
Transforming jsr305-3.0.2.jar (com.google.code.findbugs:jsr305:3.0.2) with MergeInstrumentationAnalysisTransform
Transforming listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar (com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava) with ExternalDependencyInstrumentingArtifactTransform
Transforming checker-qual-3.41.0.jar (org.checkerframework:checker-qual:3.41.0) with InstrumentationAnalysisTransform
Transforming checker-qual-3.41.0.jar (org.checkerframework:checker-qual:3.41.0) with MergeInstrumentationAnalysisTransform
Transforming jsr305-3.0.2.jar (com.google.code.findbugs:jsr305:3.0.2) with ExternalDependencyInstrumentingArtifactTransform
Transforming error_prone_annotations-2.23.0.jar (com.google.errorprone:error_prone_annotations:2.23.0) with InstrumentationAnalysisTransform
Transforming error_prone_annotations-2.23.0.jar (com.google.errorprone:error_prone_annotations:2.23.0) with MergeInstrumentationAnalysisTransform
Transforming tiny-mappings-parser-0.3.0+build.17.jar (net.fabricmc:tiny-mappings-parser:0.3.0+build.17) with InstrumentationAnalysisTransform
Transforming checker-qual-3.41.0.jar (org.checkerframework:checker-qual:3.41.0) with ExternalDependencyInstrumentingArtifactTransform
Transforming error_prone_annotations-2.23.0.jar (com.google.errorprone:error_prone_annotations:2.23.0) with ExternalDependencyInstrumentingArtifactTransform
Transforming tiny-mappings-parser-0.3.0+build.17.jar (net.fabricmc:tiny-mappings-parser:0.3.0+build.17) with MergeInstrumentationAnalysisTransform
Transforming at-0.1.0-rc1.jar (org.cadixdev:at:0.1.0-rc1) with InstrumentationAnalysisTransform
Transforming at-0.1.0-rc1.jar (org.cadixdev:at:0.1.0-rc1) with MergeInstrumentationAnalysisTransform
Transforming lorenz-0.5.7.jar (org.cadixdev:lorenz:0.5.7) with InstrumentationAnalysisTransform
Transforming tiny-mappings-parser-0.3.0+build.17.jar (net.fabricmc:tiny-mappings-parser:0.3.0+build.17) with ExternalDependencyInstrumentingArtifactTransform
Transforming lorenz-0.5.7.jar (org.cadixdev:lorenz:0.5.7) with MergeInstrumentationAnalysisTransform
Transforming bombe-0.3.4.jar (org.cadixdev:bombe:0.3.4) with InstrumentationAnalysisTransform
Transforming at-0.1.0-rc1.jar (org.cadixdev:at:0.1.0-rc1) with ExternalDependencyInstrumentingArtifactTransform
Transforming bombe-0.3.4.jar (org.cadixdev:bombe:0.3.4) with MergeInstrumentationAnalysisTransform
Transforming lorenz-0.5.7.jar (org.cadixdev:lorenz:0.5.7) with ExternalDependencyInstrumentingArtifactTransform
Transforming bombe-0.3.4.jar (org.cadixdev:bombe:0.3.4) with ExternalDependencyInstrumentingArtifactTransform
Fabric Loom: 1.7.2
(kotlinx.metadata.jvm.KotlinClassMetadata) with version (0.9.0-1.9.21-40) was loaded from (/C:/Users/hoesl/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlinx/kotlinx-metadata-jvm/0.9.0/123e86fd82d3a49afd0a41df1288a40c969f11b2/kotlinx-metadata-jvm-0.9.0.jar)
(org.objectweb.asm.ClassVisitor) with version (9.6) was loaded from (/C:/Users/hoesl/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm/9.6/aa205cf0a06dbd8e04ece91c0b37c3f5d567546a/asm-9.6.jar)
(org.objectweb.asm.tree.analysis.Analyzer) with version (9.6) was loaded from (/C:/Users/hoesl/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm-analysis/9.6/9ce6c7b174bd997fc2552dff47964546bd7a5ec3/asm-analysis-9.6.jar)
(org.objectweb.asm.commons.ClassRemapper) with version (9.6) was loaded from (/C:/Users/hoesl/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm-commons/9.6/f1a9e5508eff490744144565c47326c8648be309/asm-commons-9.6.jar)
(org.objectweb.asm.tree.ClassNode) with version (9.6) was loaded from (/C:/Users/hoesl/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm-tree/9.6/c0cdda9d211e965d2a4448aa3fd86110f2f8c2de/asm-tree-9.6.jar)
(org.objectweb.asm.util.ASMifier) with version (9.6) was loaded from (/C:/Users/hoesl/.gradle/caches/modules-2/files-2.1/org.ow2.asm/asm-util/9.6/f77caf84eb93786a749b2baa40865b9613e3eaee/asm-util-9.6.jar)
(com.google.gson.Gson) with version (null) was loaded from (/C:/Users/hoesl/.gradle/caches/modules-2/files-2.1/com.google.code.gson/gson/2.10.1/b3add478d4382b78ea20b1671390a858002feb6c/gson-2.10.1.jar)
(com.google.common.base.Preconditions) with version (null) was loaded from (/C:/Users/hoesl/.gradle/caches/modules-2/files-2.1/com.google.guava/guava/33.0.0-jre/161ba27964a62f241533807a46b8711b13c1d94b/guava-33.0.0-jre.jar)
(org.apache.commons.io.FileUtils) with version (2.15.1) was loaded from (/C:/Users/hoesl/.gradle/caches/modules-2/files-2.1/commons-io/commons-io/2.15.1/f11560da189ab563a5c8e351941415430e9304ea/commons-io-2.15.1.jar)
Creating new SharedServiceManager(312670603)
Creating new SharedServiceManager(1217968181)
file or directory 'J:\JetBrains\IntelliJIDEAUltimateProjects\Mods\DigDeeper\src\main\generated', not found
:setting up loom dependencies
Applying installer data from C:\Users\hoesl\.gradle\caches\modules-2\files-2.1\net.fabricmc\fabric-loader\0.15.11\9c2be53d84ec5c4fb58bb5b8d9c8a629047c9ee9\fabric-loader-0.15.11.jar
Found another installer JSON in (C:\Users\hoesl\.gradle\caches\modules-2\files-2.1\net.fabricmc\fabric-loader\0.15.11\9c2be53d84ec5c4fb58bb5b8d9c8a629047c9ee9\fabric-loader-0.15.11.jar), ignoring
Could not find refmap definition, will be using default name: digdeeper-refmap.json
Could not find refmap definition, will be using default name: digdeeper-refmap.json
Configuring compiler arguments for Java
Adding mixin to classpath of AP config: clientAnnotationProcessor
Adding mixin to classpath of AP config: annotationProcessor
Adding mixin to classpath of AP config: testAnnotationProcessor
Could not find refmap definition, will be using default name: digdeeper-refmap.json
Closing SharedServiceManager(1217968181)
All projects evaluated.
Task name matched 'runClient'
Selected primary task 'runClient' from project :
Tasks to be executed: [task ':compileJava', task ':processResources', task ':classes', task ':compileClientJava', task ':processClientResources', task ':clientClasses', task ':generateLog4jConfig', task ':generateRemapClasspath', task ':generateDLIConfig', task ':configureLaunch', task ':downloadAssets', task ':configureClientLaunch', task ':runClient']
Tasks that were excluded: []
Resolve mutations for :compileJava (Thread[#1493,Execution worker,5,main]) started.
:compileJava (Thread[#1493,Execution worker,5,main]) started.

> Task :compileJava FAILED
Caching disabled for task ':compileJava' because:
  Build cache is disabled
Task ':compileJava' is not up-to-date because:
  Task has failed previously.
The input changes require a full rebuild for incremental task ':compileJava'.
Full recompilation is required because no incremental change information is available. This is usually caused by clean builds or changing compiler arguments.
Compiling with toolchain 'J:\JetBrains\ij-Jdk\corretto-21.0.3'.
Compiling with JDK Java compiler API.
1 actionable task: 1 executed
Watched directory hierarchies: [J:\JetBrains\IntelliJIDEAUltimateProjects\Mods\DigDeeper]
J:\JetBrains\IntelliJIDEAUltimateProjects\Mods\DigDeeper\src\main\java\de\digdeeper\item\client\DefaultPickaxeRenderer.java:6: error: cannot access BuiltinModelItemRenderer
public class DefaultPickaxeRenderer extends GeoItemRenderer<AnimatedItem> {
                                            ^
  class file for net.minecraft.client.render.item.BuiltinModelItemRenderer not found
J:\JetBrains\IntelliJIDEAUltimateProjects\Mods\DigDeeper\src\main\java\de\digdeeper\item\custom\AnimatedItem.java:4: error: package net.minecraft.client.render.item does not exist
import net.minecraft.client.render.item.BuiltinModelItemRenderer;
                                       ^
J:\JetBrains\IntelliJIDEAUltimateProjects\Mods\DigDeeper\src\main\java\de\digdeeper\item\custom\AnimatedItem.java:32: error: cannot find symbol
            public BuiltinModelItemRenderer getGeoItemRenderer() {
                   ^
  symbol: class BuiltinModelItemRenderer
J:\JetBrains\IntelliJIDEAUltimateProjects\Mods\DigDeeper\src\main\java\de\digdeeper\item\custom\AnimatedItem.java:28: error: cannot access BipedEntityModel
        consumer.accept(new GeoRenderProvider() {
                                                ^
  class file for net.minecraft.client.render.entity.model.BipedEntityModel not found
4 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --scan to get full insights.

BUILD FAILED in 947ms
14:55:08: Execution finished 'runClient --info'.
`

can someone tell me what I can do?

**Comment by Witixin1512** [comment]
This does not seem like a GeckoLib related issue, so I'd recommend hopping in the discord with your build.gradle.
