### ISSUE TITLE
GeckoLib Crashing Forge Modpack

### ISSUE THREAD

**Issue by Yostinator** [bernie-g/geckolib#603]
Hello I've created a ModPack that has run fine for weeks but recently I have been getting both exit code 255 & exit code 1. I had looked in the curse-forge discords and people speculate that it is an issue related to this mod and the version that I am running. I am using 3.1.36 version & 1.19.2. 
Here is my debug log & most recent crash log. Hope there is a way to fix this because a few mods that I have require geckolib to run. But if I have to I am willing to remove the mods that require it so I can run my pack again

[debug.log](https://github.com/user-attachments/files/16322567/debug.log)
[latest.log](https://github.com/user-attachments/files/16322568/latest.log)
Hopefully these files can be accessed ty

**Comment by Tslat** [comment]
Looks like you have a corrupt model json somewhere

**Comment by Yostinator** [comment]
How do I change or fix that?

**Comment by Tslat** [comment]
Work out which mod is causing it, then remove that mod

Geckolib is crashing because a mod is passing it a bad model file

**Comment by Yostinator** [comment]
is there a way to figure out which mod that is without manually removing and replacing mods or is that kinda my only option

**Comment by Tslat** [comment]
No real way

If you were on a newer version of geckolib the log would be more informative, but you're on an old version so yeah...

**Comment by Yostinator** [comment]
Do you know what version makes the log more informative cause I can do up to 3.1.40 but my pack is for 1.19 so I;m kinda stuck I'd think

**Comment by Tslat** [comment]
1.20.1 or 1.21 :)
