### ISSUE TITLE
[1.21] Buffer Builder Not Building! with glowing item/armor render layers on 4.5.7

### ISSUE THREAD

**Issue by iron431** [bernie-g/geckolib#606]
Neoforge 1.21 21.0.103-beta
Geckolib 4.5.7
https://gist.github.com/iron431/05bb9914a6cf994e82f77e48176a9212

GeoEntities with an `ItemArmorGeoLayer` or `BlockAndItemGeoLayer` will throw the Not Building! error when attempting to render the items/armor if the entity is glowing, seemingly due to the buffer while glowing failing the `instanceof BufferBuilder` check. Other render layers that render custom models do not experience this issue

![image](https://github.com/user-attachments/assets/de30ff38-ff43-421a-b052-0a4c6aabdcc1)

**Comment by JaisDK** [comment]
Is this supposed to have been fixed? it still happens on 4.5.8 https://mclo.gs/ZXVS32O

**Comment by Tslat** [comment]
> Is this supposed to have been fixed? it still happens on 4.5.8 https://mclo.gs/ZXVS32O

Does it happen without Embeddium enabled

**Comment by djnifos** [comment]
Got a user to remove embeddium and it still happens https://mclo.gs/yiQ2A7l

**Comment by Tslat** [comment]
This is proving to be rather an annoying bug lol

**Comment by Tslat** [comment]
> Got a user to remove embeddium and it still happens https://mclo.gs/yiQ2A7l

@djnifos 
Can you try this without any mods other than irons spellbooks & geckolib?

You have a lot of mods that could be interfering

**Comment by SolarNightx** [comment]
I tried with only downloading Gecko and Iron's through the Curse app since I was also having issues in ATM10 and I got the same result: https://mclo.gs/gMNpJ03

**Comment by djnifos** [comment]
https://mclo.gs/eGM9nxm

an hs_err_pid log from this issue

**Comment by Tslat** [comment]
This error will not generate an hs_err_pid, that is an unrelated error

**Comment by djnifos** [comment]
My bad.  I saw similar wording and jumped to the conclusion.

**Comment by djnifos** [comment]
I should add, I was leaning towards driver issue because it doesn't seem to effect my machine.

**Comment by Tslat** [comment]
Lol alright
Let's try this once more

this should be fixed once more in 4.6
