### ISSUE TITLE
[Fabric 1.20.1] Crash involving EMI and geckolib

### ISSUE THREAD

**Issue by DJteaCosy** [bernie-g/geckolib#610]
Spoke to Emi on his discord about trying to identify a crash, modpack is All of Fabric 7. The instance is crashing when a certain item/items are rendered, with the crash reading "Description: rendering item". He suggested I contact you guys, but your discord link has been set to private/I couldn't join it.

Modpack & version: All of Fabric 7 2.4.3
Minecraft version: 1.20.1
Fabric version: 0.15.11
Geckolib version: geckolib-fabric-1.20.1-4.4.7

crash report below: it always seems to be the same items, 
[crash-2024-07-24_23.31.50-client.txt](https://github.com/user-attachments/files/16381692/crash-2024-07-24_23.31.50-client.txt)

**Comment by Tslat** [comment]
Which discord link is private?

**Comment by Tslat** [comment]
This looks like someone has an invalid skullblock set up
Which item is it that's crashing?

**Comment by DJteaCosy** [comment]
the modrinth discord link is invalid (https://modrinth.com/mod/geckolib/versions) 

Issue turned out to be caused by the mod Variants & Ventures, which has since been removed from the pack. Both REI and EMI could be crashed by searching for "verdant skull". Happy to mark this issue as resolved, if you are

**Comment by Tslat** [comment]
> the modrinth discord link is invalid (https://modrinth.com/mod/geckolib/versions)

Fixed, thanks

Yeah gonna close this, as it's not actually geckolib crashing, it's the skull which they registered incorrectly
