### ISSUE TITLE
[1.20.1] Invis entities aren't translucent when they should be visible to a player

### ISSUE THREAD

**Issue by FlashFyreMods** [bernie-g/geckolib#611]
To reproduce:
- Throw an invisibility potion on any vanilla LivingEntity, and the same on a geckolib LivingEntity such as the bike
- Change to spectator gamemode
- See that the vanilla living entity is translucent and the geckolib one is fully opaque

I think this is because GeoEntityRenderer doesn't have the functionality that is in LivingEntityRenderer#getRenderType (which makes sense as GeoEntityRenderer isn't exclusive to living entities, but still, it seems like an oversight).

**Comment by Tslat** [comment]
It's actually not

Using the same rendertype as vanilla still makes it render opaque, which is very curious
I'll have to work out why that is

**Comment by Tslat** [comment]
Nvm found it lol
