### ISSUE TITLE
[forge1.20.1] Cant invoke software.bernie.geckolib.network.SerilizableDataTicket.Decode

### ISSUE THREAD

**Issue by Lingye1204** [bernie-g/geckolib#612]
![FR}@{UBRIFQS` QBCTZ`}}L](https://github.com/user-attachments/assets/09617d77-1798-471d-a762-55c5f71a9854)

This issue happened when I entered the server,but earlier it was working normally.
[latest.txt](https://github.com/user-attachments/files/16428748/latest.txt)

**Comment by Tslat** [comment]
That log does not contain the error

**Comment by Lingye1204** [comment]
this error was caused by another mod,

**Comment by Lingye1204** [comment]
this error was caused by another mod.

**Comment by Xplodin** [comment]
> this error was caused by another mod.

which mod?
