### ISSUE TITLE
I found in Forge 1.19.2 that if there are multiple armor mods in the game that depend on geckolib, the armor animation will not be triggered

### ISSUE THREAD

**Issue by MiokiQAQ** [bernie-g/geckolib#613]
I found in Forge 1.19.2 that if there are multiple armor mods in the game that depend on geckolib, the armor animation will not be triggered

**Comment by MiokiQAQ** [comment]
> multiple armour mods? 多个盔甲模组？

If two mods that depend on Geckolib both contain armor with Geckolib animations, the armor's animations will not play.

**Comment by MiokiQAQ** [comment]
> multiple armour mods? 多个盔甲模组？

I am a player from China, and my English vocabulary might not be very good. Please excuse me for that.

**Comment by Tslat** [comment]
How do you know this isn't just a bug with those mods?

**Comment by MiokiQAQ** [comment]
> How do you know this isn't just a bug with those mods?你怎么知道这不仅仅是那些模组的错误？

Because I have tried many different ways to put them together, but their commonality is that they are all made by mcreator.

**Comment by Tslat** [comment]
That seems like an mcreator problem, not a Geckolib problem

**Comment by MiokiQAQ** [comment]
> That seems like an mcreator problem, not a Geckolib problem

I understand now, thank you very much for taking the time to answer my question.
