### ISSUE TITLE
 [BUG] GeckoLib Fabric and Forge don't work together, but ONLY when I have a mod that requires GeckoLib Forge, and another that requires GeckoLib Fabric (Sinytra Connector)(1.20.1 and Latest Release) #167 

### ISSUE THREAD

**Issue by MistifyedOne** [bernie-g/geckolib#618]
Minecraft: 1.20.1
Fabric: 0.15.9
GeckoLib Fabric AND Forge via Sinytra Connector
Soulslike-Weaponry: 1.1.3

Describe the bug
 The mods in my modpack require both GeckoLib Forge and Fabric. They work fine alone, and it works fine when I have both installed plus all the Forge mods that need GeckoLib. However, when I add a mod that needs Geckolib Fabric, the game crashes due to entrypoint stage 'main'. Both Geckolib versions have different code so I need to use both.

[crash-2024-08-11_20.46.04-client.txt](https://github.com/user-attachments/files/16577200/crash-2024-08-11_20.46.04-client.txt)

**Comment by Tslat** [comment]
Known and not fixable without breaking changes

Sinytra is not meant to be a perfect solution.
