### ISSUE TITLE
[Suggestion] Add markers on animations

### ISSUE THREAD

**Issue by iglee42** [bernie-g/geckolib#619]
It could be could to add the fact that developper can add markers on animations to follow a point on the model.

The markers could be read in the code.

It can be useful to make an item renderer follow a point on the model when an animation is playing

**Comment by Tslat** [comment]
How would this work?

**Comment by iglee42** [comment]
You could add markers with a name and a position like bones, and with the AnimationState you could do state.getMarkerPos(Name); and it returns the position of the Marker at the current frame of the animation

**Comment by Tslat** [comment]
What's to stop you from doing that already with bones?

**Comment by iglee42** [comment]
I don't find how to get bones position in the code

**Comment by Tslat** [comment]
Look at the getWorldSpacePosition and similar methods in GeoBone
