### ISSUE TITLE
4.6 fails to parse some animations it was able to parse before

### ISSUE THREAD

**Issue by NordAct** [bernie-g/geckolib#622]
This results in entire animation being broken, so model just T-poses whenever this broken animation plays.
Log: https://gist.github.com/NordAct/39437306645af60edee5e1ea9eaa1685
Problematic animation and respective model files:
1) [Animation](https://github.com/NordAct/useless-reptile/blob/dev/src/main/resources/assets/uselessreptile/animations/entity/wyvern/wyvern.animation.json) | [Model](https://github.com/NordAct/useless-reptile/blob/dev/src/main/resources/assets/uselessreptile/geo/entity/wyvern/wyvern.geo.json)
2) [Animation](https://github.com/NordAct/useless-reptile/blob/dev/src/main/resources/assets/uselessreptile/animations/entity/moleclaw/moleclaw.animation.json) | [Model](https://github.com/NordAct/useless-reptile/blob/dev/src/main/resources/assets/uselessreptile/geo/entity/moleclaw/moleclaw.geo.json)
3) [Animation](https://github.com/NordAct/useless-reptile/blob/dev/src/main/resources/assets/uselessreptile/animations/entity/lightning_chaser/lightning_chaser.animation.json) | [Model](https://github.com/NordAct/useless-reptile/blob/dev/src/main/resources/assets/uselessreptile/geo/entity/lightning_chaser/lightning_chaser.geo.json)

Also want to suggest to add resource location of animation file in error print for easier identification which one exactly is broken

**Comment by Tslat** [comment]
There's always some edge cases that my testing misses :(
