### ISSUE TITLE
Memory Leak of Client Level

### ISSUE THREAD

**Issue by pietro-lopes** [bernie-g/geckolib#625]
There are 2 cases that are leaking the level (one is an entity and the other is the level itself)

Here is an entity that is still kept alive, maybe nullify after render just like `animatable = null` on `#renderToBuffer`
<https://github.com/bernie-g/geckolib/blob/8f383deb479cf375d6f01c294361539f446c4a0a/common/src/main/java/software/bernie/geckolib/renderer/GeoArmorRenderer.java#L405>

Also, here:
https://github.com/bernie-g/geckolib/blob/8f383deb479cf375d6f01c294361539f446c4a0a/common/src/main/java/software/bernie/geckolib/loading/math/MolangQueries.java#L118

This actor needs to be cleared up on level unload.

![image](https://github.com/user-attachments/assets/e48840f7-0747-43e4-bc24-0c5e2fe5b3ff)

**Comment by Tslat** [comment]
1.20.1 down

https://github.com/bernie-g/geckolib/commit/edd9f02c3fd5923d312e85cc1df2ea385698c42c

1.21.1 soon

**Comment by Tslat** [comment]
Done in 1.21.1 as of 4.6.3
