### ISSUE TITLE
setAnimData still broken

### ISSUE THREAD

**Issue by byteManiak** [bernie-g/geckolib#632]
When a SingletonGeoAnimatable is registered, the class name used by `registerSyncedAnimatable` is `com.class.name.Here`.

However, when `getSyncedAnimatable` is called, the string passed to it is instead `class com.class.name.Here`, resulting in this message:
`Attempting to retrieve unregistered synced animatable! (class com.class.name.Here)`

**Comment by Tslat** [comment]
lol. sigh.
