### ISSUE TITLE
 Desync animations

### ISSUE THREAD

**Issue by Koora7334** [bernie-g/geckolib#637]
Hello, I’ve just ported your mod (the 1.12 version) to be compatible with Minecraft 1.8.9, but I’m encountering an issue when my custom mob ticks.
Occasionally, the animations glitch and desynchronize, which results in the mob behaving erratically.

Btw I'm in survival, and not using the server sync method.
My Entity class : https://i.courat.eu/gsNQQxXFla.png

Here’s some proof of the duplicated model issue: https://i.courat.eu/7g3qqGFGwK.mp4, https://i.courat.eu/Hj9OmM36f8.mp4

**Comment by Tslat** [comment]
Sounds unrelated to us

If you've ported your own version, you're responsible for your own bugs
