### ISSUE TITLE
geckolib for 0.88 fabric api

### ISSUE THREAD

**Issue by monachwan** [bernie-g/geckolib#638]
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'GeckoLib 4' (geckolib) 4.4.7 with version 4.4 or later that is compatible with:
		 - fabric-api 0.88.1+1.20.1
More details:
	 - Mod 'GeckoLib 4' (geckolib) 4.4.7 requires version 0.92.2+1.20.1 or later of mod 'Fabric API' (fabric-api), but only the wrong versions are present: 0.88.1+1.20.1/0.83.0+1.20.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

this was the whole error, but i wanted to remain the fabric api 0.88 because it is essential to my sodium0.4.10-indium 1.20.1 but then i get this error after solving that sodium-indium error before. is there anyway? or do i have to actually change my api to 0.90+ and remove the sodium-indium stuff and go back to the version that was installed earlier?

**Comment by Tslat** [comment]
You can try changing it in the geckolib fabric.mod.json in the jar you have or something idk

Or see if there's a solution that lets your sodium thing work on newer versions (preferred solution)
