### ISSUE TITLE
MC Doom?

### ISSUE THREAD

**Issue by jexline** [bernie-g/geckolib#64]
I sent this crash report to MC Doom, but they said "It's a geckolib issue, please report with them. https://github.com/bernie-g/geckolib/issues." Honestly, I don't know how it would be an issue on your end. I thought they made the mod and forgot to include Geckolib files, but not sure. 
[crash-2020-12-28_18.55.28-client.txt](https://github.com/bernie-g/geckolib/files/5751776/crash-2020-12-28_18.55.28-client.txt)

**Comment by AzureDoom** [comment]
#66 will fix this and other issues when trying to use a Fabric version past 0.26.2+1.16 so go ahead and close this @jexline
