### ISSUE TITLE
Support for material types compatible with Bedrock?

### ISSUE THREAD

**Issue by huanmeng-qwq** [bernie-g/geckolib#640]
https://wiki.bedrock.dev/visuals/materials.html
https://wiki.bedrock.dev/visuals/structure-presentation.html

This will be the support for rendering new features

**Comment by Tslat** [comment]
This doesn't seem related to geckolib at all - this is already a thing in Vanilla Minecraft that you can do whenever you want?

**Comment by huanmeng-qwq** [comment]
If you think this request doesn't fit the original intent of the project, please `delete the issue`, sorry to disturb you.

**Comment by Tslat** [comment]
No I'm saying this _already exists_ in java minecraft
