### ISSUE TITLE
Issue with Attack Animation

### ISSUE THREAD

**Issue by DerekX01** [bernie-g/geckolib#641]
Hello community,

I'm having a problem with a mod I'm creating. I'm fairly new to this, so I don't know much about it yet. I've been learning little by little by reading documentation and watching YouTube videos on the subject. My issue is as follows: I have this entity in my mod:

https://github.com/DerekX01/GolemEntity

However, I'm encountering an issue with the attack animation. I'm not sure if I'm implementing it incorrectly or what the problem is, but the animation never seems to play. The entity appears to attack very quickly, and the mob seems to vibrate as if it's trying to perform something. I apologize if I'm not explaining this well—I'm still very much a beginner.

Thank you in advance for any help!

**Comment by Tslat** [comment]
If you want community help, join the discord

This is not a GeckoLib issue
