### ISSUE TITLE
1.12.2的缩放0异常，需要隐藏的组没有隐藏   1.12.2 zoom 0 exception, groups that need to be hidden are not hidden

### ISSUE THREAD

**Issue by WI8614ice** [bernie-g/geckolib#644]
1.12.2 zoom 0 exception, groups that need to be hidden are not hidden

**Comment by WI8614ice** [comment]
![Uploading 2fb27f7acf77f3b9cfd9bce6ebf62a2e.png…]()

**Comment by WI8614ice** [comment]
![Uploading 2fb27f7acf77f3b9cfd9bce6ebf62a2e.png…]()

**Comment by WI8614ice** [comment]
![Uploading 24cd33f0d2bef90e33112638bc44d77c.png…]()

**Comment by Tslat** [comment]
1.12 is a very old version, I'd recommend updating if you want updates
