### ISSUE TITLE
Game crashes on launch

### ISSUE THREAD

**Issue by Retrograde1** [bernie-g/geckolib#648]
Hello I have issues on loading my modpack with geckolib, I've tried multiple version and multiple versions of forge + removing some mods that might be part of a issue, however I cant resolve this on my own, so I would love some assistance from people that understand it better than I do ( which isnt difficult)
[crash-2024-11-11_21.10.48-client.txt](https://github.com/user-attachments/files/17707874/crash-2024-11-11_21.10.48-client.txt)

**Comment by Tslat** [comment]
minecraft_earth_mod is broken, remove it or get the dev to fix it
