### ISSUE TITLE
weird crash

### ISSUE THREAD

**Issue by Vadewolf** [bernie-g/geckolib#653]
[crash-2024-11-21_20.29.20-client.txt](https://github.com/user-attachments/files/17876953/crash-2024-11-21_20.29.20-client.txt)
[crash-2024-11-22_16.16.00-client.txt](https://github.com/user-attachments/files/17876954/crash-2024-11-22_16.16.00-client.txt)

i added both create mechanical extruder and stacked blocks mods and got those so info needed

**Comment by Tslat** [comment]
ars_nouveau is broken

**Comment by Vadewolf** [comment]
ok thank you
