### ISSUE TITLE
[1.21.1-Fabric] Dark model

### ISSUE THREAD

**Issue by meo209** [bernie-g/geckolib#656]
Any type of Block I add is always darker then it should be.

Ingame:
![image](https://github.com/user-attachments/assets/30722d7e-6736-420d-b99e-fb72a91d1569)

Blockbench model:
![image](https://github.com/user-attachments/assets/1154730d-d363-4536-8146-08c36b238b47)

**Comment by Tslat** [comment]
Probably because you have your block occluding light, so the game thinks it should be dark there
try using noOcclusion in your block properties, or override the allows skylight through method in your block, whatever that's called

**Comment by meo209** [comment]
Thank you. Adding `nonOpaque()` to my block settings fixed it.
