### ISSUE TITLE
The collapse caused by the incompatibility between epic fight and Geckolib

### ISSUE THREAD

**Issue by Xall0y** [bernie-g/geckolib#658]
When I was in an old save, I didn't have any special behavior, just moving or turning my head triggered a crash; In a new archive, this kind of crash will also occur, but the frequency is very low. The log display is caused by epic fight and Geckolib.
[crash-2024-12-08_06.55.44-client.txt](https://github.com/user-attachments/files/18056523/crash-2024-12-08_06.55.44-client.txt)
[debug.log](https://github.com/user-attachments/files/18056525/debug.log)
[latest.log](https://github.com/user-attachments/files/18056529/latest.log)

**Comment by Tslat** [comment]
borninchaosv mod broken, nothing to do with geckolib

**Comment by Xall0y** [comment]
thank you so much!

> borninchaosv mod broken, nothing to do with geckolib
