### ISSUE TITLE
Crash report mentions geckolib and ''couldn't find bone'' and ''rendering entity''

### ISSUE THREAD

**Issue by DeadGator** [bernie-g/geckolib#660]
Crash report: https://mclo.gs/0uyQHYe

**Comment by Compl3xlife** [comment]
Crash report  [crash-2024-12-13_21.58.48-client.txt](https://github.com/user-attachments/files/18134129/crash-2024-12-13_21.58.48-client.txt)

**Comment by Tslat** [comment]
Issue with Irons spellbooks and/or your pack

Not Geckolib related
