### ISSUE TITLE
Client crashing and connection issues

### ISSUE THREAD

**Issue by kezmodius** [bernie-g/geckolib#665]
A player on my server is having major connection issues and is crashing often. The crash report indicates a rendering issue and points at Oculus, Embeddium and Geckolib. He removed Embeddium and Oculus to test and the issue still occurred. Client crash report attached. I can get server logs if required.

https://gist.github.com/kezmodius/984ba2d313ecee7daa6d3ca3bc8f776b

**Comment by Tslat** [comment]
show me the crash without embeddium and oculus
