### ISSUE TITLE
Mixin not applying; why?

### ISSUE THREAD

**Issue by astotic** [bernie-g/geckolib#667]
im developing a mod using geckolib and the problem is that the renderthread keeps crashing when applying mixins
i have checked my gradle configs twice already and still cant figure out what im doing wrong
attached crash-report:
[crash-2024-12-22_23.53.53-client.txt](https://github.com/user-attachments/files/18223545/crash-2024-12-22_23.53.53-client.txt)

**Comment by Tslat** [comment]
gotta properly set up your buildscript for mixins

https://darkhax.net/2020/07/mixins

**Comment by astotic** [comment]
ive redone the whole build.gradle with the site you gave me and geckolibs installation instructions and still get the same error

**Comment by Tslat** [comment]
Then move to the discord for assistance
