### ISSUE TITLE
I don't know how important these errors are.

### ISSUE THREAD

**Issue by Krimatoria** [bernie-g/geckolib#668]
geckolib-forge-1.20.1-4.7.jar
https://gist.github.com/Krimatoria/5444870c72d60ae445a76d83ebd151e1

**Comment by Tslat** [comment]
Means you have an invalid animation json somewhere

**Comment by Krimatoria** [comment]
> Means you have an invalid animation json somewhere

Born in Chaos - an error appears when adding this
