### ISSUE TITLE
Adding LayerRenderers to the player where the models are animated with GeckoLib

### ISSUE THREAD

**Issue by FlashHUN** [bernie-g/geckolib#67]
Alright, this is my first time using GeckoLib and I couldn't find any documentation or examples on how to do this. Basically, I want to create a LayerRenderer that has some models in it with animations through GeckoLib, and I want to attach this LayerRenderer to the player. How could I achieve this?

**Comment by bernie-g** [comment]
You'd need to create a custom renderer as explained in the wiki. It would be almost identical to GeoArmorRenderer. Please join the discord to receive support, github issues are only for bugs/problems.
