### ISSUE TITLE
Crash forge-1.16.4-geckolib-3.0.0

### ISSUE THREAD

**Issue by HonestAngel** [bernie-g/geckolib#76]
1.16.5-forge-36.0.1 and CNB-1.16.3_4-1.2.8.2

software.bernie.geckolib3.geo.exception.GeoModelException: cnb:geo/lilytad.geo.json: Could not find model.
[crash-2021-01-21_19.40.23-client.txt](https://github.com/bernie-g/geckolib/files/5853481/crash-2021-01-21_19.40.23-client.txt)

**Comment by bernie-g** [comment]
@HonestAngel Are you the developer of "cnb"? What is that mod anyway?

**Comment by HonestAngel** [comment]
it's creatures and beasts and no it's not my mod

**Comment by HonestAngel** [comment]
There was another problem with another mod as well.... same kind of problems

https://github.com/baileyholl/Ars-Nouveau/issues/148

**Comment by AzureDoom** [comment]
This should be fixed in the newest release, if it happens again please reopen.
