### ISSUE TITLE
crash randomly when exploring

### ISSUE THREAD

**Issue by AdnanuReeves** [bernie-g/geckolib#81]
latest 1.16.5 version
https://paste.ubuntu.com/p/Q46mmgN8yw/

**Comment by AdnanuReeves** [comment]
Works fine downgrading to 3.0.0

**Comment by AzureDoom** [comment]
It will still work with latest as well, it's just a randomly bug is random and unable to reproduced in a working manner. @baileyholl it's doing it again, I don't think the fix worked.

**Comment by AzureDoom** [comment]
Confirmed fix in latest release.

**Comment by AzureDoom** [comment]
whoops wrong issue. Stupid phone

**Comment by AzureDoom** [comment]
Alright a possible fix has been pushed again to v3.0.12. Please let us know if it happens again.

**Comment by AzureDoom** [comment]
No new errors sent about this. Closing as it seems was fixed.
