### ISSUE TITLE
Sodium incompatibility(fabric)

### ISSUE THREAD

**Issue by imreallybadatnames** [bernie-g/geckolib#84]
A certain access widener(the method `renderCuboids`) makes Sodium incompatible. Consider using an [Accessor](https://fabricmc.net/wiki/tutorial:mixin_accessors) for it instead.

**Comment by imreallybadatnames** [comment]
The method belongs to the `ModelPart` class.

**Comment by imreallybadatnames** [comment]
It's method name from the official mappings is `method_22702` and the class is `class_630`.

**Comment by imreallybadatnames** [comment]
(1.16.3)

**Comment by imreallybadatnames** [comment]
The official mapping's method and class name still remain the same above this version.

**Comment by bernie-g** [comment]
@imreallybadatnames You are on a VERY old version of geckolib. Upgrade to 3.0.0.
