### ISSUE TITLE
Crashes when running in production

### ISSUE THREAD

**Issue by OroArmor** [bernie-g/geckolib#91]
https://github.com/bernie-g/geckolib/blob/f8333e39b89c8571dcc38390b8de3b1702485a0a/src/main/java/software/bernie/geckolib3/util/RegistryUtils.java#L92-L101

I just spent around 2 hours helping someone debug why their block entity crashed in production, and it was this method. This should be changed as it is extremely misleading.

**Comment by bernie-g** [comment]
This is used for geckolib example tile entities, which intentionally only work in dev. The only thing wrong here is this is in the wrong package, it should be in the example package. I will let @AzureDoom know about this.

**Comment by bernie-g** [comment]
Fixed in 3.0.13.
